//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FBSharedFramework/FBQuickPerformanceLoggerCommon.h>

@interface FBQuickPerformanceLogger : FBQuickPerformanceLoggerCommon
{
}

+ (shared_ptr_a4177b8a)sharedXplatLogger;
+ (void)setSharedLogger:(id)arg1;
+ (id)sharedLogger;
- (shared_ptr_e62c5e43)xplatLogger;

@end

