//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FBStateMachineTransition : NSObject
{
    NSString *_originState;
    NSString *_destinationState;
}

+ (id)transitionFromState:(id)arg1 toState:(id)arg2;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSString *destinationState;
@property(readonly, copy, nonatomic) NSString *originState;

@end

