//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class FNFDashSelectionMetadata, NSData;

@protocol FNFDashNetworkerDelegate
- (void)dataFailedWithMetrics:(FNFDashSelectionMetadata *)arg1 sequenceIndex:(int)arg2;
- (void)dataFinishedWithMetrics:(FNFDashSelectionMetadata *)arg1 sequenceIndex:(int)arg2;
- (void)dataFetched:(NSData *)arg1 sequenceIndex:(int)arg2;
@end

