//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGNetworkCallbacks.h"

@class NSObject<OS_dispatch_queue>;

@interface IGAsyncCallbackExecutor : NSObject <IGNetworkCallbacks>
{
    NSObject<OS_dispatch_queue> *_queue;
    id <IGNetworkCallbacks> _callbacks;
}

- (void).cxx_destruct;
- (void)_onQueue:(CDUnknownBlockType)arg1;
- (void)failure:(id)arg1 summary:(id)arg2;
- (void)success:(id)arg1;
- (void)bytesReceived:(const char *)arg1 len:(unsigned long long)arg2 totalBytesExpectedToReceive:(long long)arg3;
- (void)responseReceived:(id)arg1;
- (void)bytesSent:(long long)arg1 totalBytes:(long long)arg2 totalBytesExpectedToSend:(long long)arg3;
- (void)startHandler;
- (void)cacheHandler:(id)arg1;
- (void)retryHandler:(id)arg1;
- (id)initWithQueue:(id)arg1 callbacks:(id)arg2;

@end

