//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBARAudioSessionManaging.h"

@class MPMusicPlayerController, NSString;

@interface IGAudioSession : NSObject <FBARAudioSessionManaging>
{
    _Bool _preventSystemVolumeChange;
    _Bool _muteSwitchOn;
    long long _stickySoundState;
    MPMusicPlayerController *_musicPlayerController;
    double _previousVolume;
    id <FBARAudioSessionManagingClient> _client;
    long long _outputType;
}

+ (id)sharedInstance;
@property(nonatomic) long long outputType; // @synthesize outputType=_outputType;
@property __weak id <FBARAudioSessionManagingClient> client; // @synthesize client=_client;
@property(nonatomic) _Bool muteSwitchOn; // @synthesize muteSwitchOn=_muteSwitchOn;
@property(nonatomic) double previousVolume; // @synthesize previousVolume=_previousVolume;
@property(retain) MPMusicPlayerController *musicPlayerController; // @synthesize musicPlayerController=_musicPlayerController;
@property(nonatomic) long long stickySoundState; // @synthesize stickySoundState=_stickySoundState;
@property(nonatomic) _Bool preventSystemVolumeChange; // @synthesize preventSystemVolumeChange=_preventSystemVolumeChange;
- (void).cxx_destruct;
- (void)unregisterDeactivatingClient:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)reloadStateForActiveClient:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)registerActivatingClient:(id)arg1 completion:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) long long currentOutputType;
- (void)_audioSessionRouteChange:(id)arg1;
- (void)_updateOutputType;
- (void)_muteSwitchChanged:(id)arg1;
- (void)_volumeChanged:(id)arg1;
- (void)_didEnterBackground;
- (void)_willResignActive;
- (void)_didBecomeActive;
@property(readonly, nonatomic) unsigned long long categoryOptions;
@property(readonly, copy, nonatomic) NSString *category;
- (void)initializeMusicPlayer;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

