//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGStoryAsset.h"
#import "NSCopying.h"
#import "NSSecureCoding.h"

@class NSString;

@interface IGDynamicOverlayModel : NSObject <IGStoryAsset, NSCopying, NSSecureCoding>
{
    map_4edb12f9 _regionCache;
    id <IGDynamicOverlayImageProvider> _imageProvider;
}

+ (_Bool)supportsSecureCoding;
+ (struct IGRegion)interpolatedRegionForTimeKey:(int)arg1 inCache:(const map_4edb12f9 *)arg2;
+ (void)load;
@property(readonly, nonatomic) id <IGDynamicOverlayImageProvider> imageProvider; // @synthesize imageProvider=_imageProvider;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)storyAssetDiffableIdentifier;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)_dictionaryFromRegionCache;
- (struct IGRegion)regionForTime:(CDStruct_1b6d18a9)arg1;
- (id)initWithFixedRegion:(struct IGRegion)arg1 imageProvider:(id)arg2;
- (id)initWithRegionCache:(const map_4edb12f9 *)arg1 imageProvider:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

