//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGEmptyFeedViewDelegate.h"
#import "IGInfoViewDelegate.h"

@class IGEmptyFeedView, IGFeedStatusConfig, IGInfoView, NSObject<IGFeedStatusViewDataSource>, NSObject<IGFeedStatusViewDelegate>, NSString;

@interface IGFeedStatusView : UIView <IGInfoViewDelegate, IGEmptyFeedViewDelegate>
{
    IGEmptyFeedView *_emptyView;
    IGInfoView *_infoView;
    IGFeedStatusConfig *_config;
    _Bool _canHideSelf;
    _Bool _shouldOnlyShowForLoadingMore;
    _Bool _showBlankFeedStatusView;
    NSObject<IGFeedStatusViewDataSource> *_dataSource;
    NSObject<IGFeedStatusViewDelegate> *_delegate;
}

@property(nonatomic) __weak NSObject<IGFeedStatusViewDelegate> *delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak NSObject<IGFeedStatusViewDataSource> *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) _Bool showBlankFeedStatusView; // @synthesize showBlankFeedStatusView=_showBlankFeedStatusView;
@property(nonatomic) _Bool shouldOnlyShowForLoadingMore; // @synthesize shouldOnlyShowForLoadingMore=_shouldOnlyShowForLoadingMore;
@property(nonatomic) _Bool canHideSelf; // @synthesize canHideSelf=_canHideSelf;
- (void).cxx_destruct;
- (void)emptyViewPrimaryButtonWasTapped:(id)arg1;
- (void)infoViewWasTapped:(id)arg1;
- (void)updateFeedStatusView;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

