//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IGLassoUserInfo : NSObject
{
    NSString *_userID;
    NSString *_handleName;
}

@property(readonly, nonatomic) NSString *handleName; // @synthesize handleName=_handleName;
@property(readonly, nonatomic) NSString *userID; // @synthesize userID=_userID;
- (void).cxx_destruct;
- (id)initWithUserID:(id)arg1 handleName:(id)arg2;

@end

