//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FBSharedFramework/FBIvarBasedEqualityObject.h>

@class NSString;

@interface IGNetworkTraceConfig : FBIvarBasedEqualityObject
{
    unsigned long long _subtype;
    NSString *_sampled_uuid;
}

+ (id)sampledWithUuid:(id)arg1;
+ (id)notSampled;
- (void).cxx_destruct;
- (void)matchNotSampled:(CDUnknownBlockType)arg1 sampled:(CDUnknownBlockType)arg2;

@end

