//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <FBSharedFramework/FBAnnouncerBase.h>

#import "IGNetworkBandwidthRecorderListener.h"

@class NSString;

@interface IGNetworkBandwidthRecorderListenerAnnouncer : FBAnnouncerBase <IGNetworkBandwidthRecorderListener>
{
}

- (void)bandwidthChangedWithBytesReceived:(long long)arg1 overTimeInterval:(double)arg2 totalBandwidthMeasured:(CDStruct_3f75b8dd)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

