//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGNetworkBandwidthRecorderListener.h"

@class NSString, NSURL;

@protocol IGQueueTimeObserving <IGNetworkBandwidthRecorderListener>
- (void)requestDidFinishWithIdentifier:(NSString *)arg1;
- (void)requestDidEnterNetworkWithIdentifier:(NSString *)arg1;
- (void)requestDidEnterQueueWithIdentifier:(NSString *)arg1 type:(NSString *)arg2 url:(NSURL *)arg3 module:(NSString *)arg4 isOnscreen:(_Bool)arg5;
- (void)setShouldLogURLS:(_Bool)arg1;
- (void)setEnabled:(_Bool)arg1;
@end

