//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGTwitterUtil : NSObject
{
}

+ (void)_loadProfilePictureForACAccount:(id)arg1 delegate:(id)arg2 networker:(id)arg3;
+ (void)_removeHandler:(id)arg1;
+ (id)_accountStore;
+ (void)tweetWithSystemTwitterAccountFeedItem:(id)arg1 permalink:(id)arg2 userPK:(id)arg3 viewController:(id)arg4;

@end

