//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGListDiffable.h"
#import "IGSmartStickerModelType.h"
#import "IGStickerModelType.h"
#import "NSSecureCoding.h"

@class CLLocation, IGLocation, NSArray, NSString;

@interface IGUniversalLocationStickerModel : NSObject <IGListDiffable, IGStickerModelType, IGSmartStickerModelType, NSSecureCoding>
{
    NSString *_pk;
    IGLocation *_location;
    NSArray *_stickers;
    CLLocation *_mediaEXIFLocation;
}

+ (_Bool)supportsSecureCoding;
+ (id)placeholderLocation;
+ (id)defaultLocationSticker;
@property(readonly, nonatomic) CLLocation *mediaEXIFLocation; // @synthesize mediaEXIFLocation=_mediaEXIFLocation;
@property(readonly, copy, nonatomic) NSArray *stickers; // @synthesize stickers=_stickers;
@property(readonly, nonatomic) IGLocation *location; // @synthesize location=_location;
@property(readonly, copy, nonatomic) NSString *pk; // @synthesize pk=_pk;
- (void).cxx_destruct;
- (unsigned long long)smartStickerType;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(readonly) unsigned long long hash;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) _Bool includeInRecent;
- (void)configureWithLocation:(id)arg1;
- (id)initWithDict:(id)arg1;
- (id)initWithPk:(id)arg1 stickers:(id)arg2 mediaEXIFLocation:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

