//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGVideoPlaybackLoggingConfig;

@interface IGVideoPlaybackSimpleLogger : NSObject
{
    IGVideoPlaybackLoggingConfig *_config;
    double _lastVideoStartedPlayingTime;
    id <IGAnalyticsEventLoggingProtocol> _analyticsLogger;
}

- (void).cxx_destruct;
- (id)_eventWithName:(id)arg1 representationId:(id)arg2;
- (void)logVideoPlayedTimeWithRepresentationId:(id)arg1 extras:(id)arg2;
- (void)notifyVideoStartedPlaying;
- (id)initWithConfig:(id)arg1 analyticsLogger:(id)arg2;

@end

