//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CADisplayLink, IGViewpointSnapshotTrackableCircularBuffer, IGViewpointUpdater, NSNotificationCenter, NSObject<OS_dispatch_queue>;

@interface IGViewpointManager : NSObject
{
    NSNotificationCenter *_nc;
    double _lastTick;
    CADisplayLink *_displayLink;
    unsigned long long _currentReason;
    _Bool _backgroundFrameCalculationEnabled;
    NSObject<OS_dispatch_queue> *_frameCalculationBackgroundQueue;
    IGViewpointSnapshotTrackableCircularBuffer *_snapshotTrackableCircularBuffer;
    IGViewpointUpdater *_updater;
    double _updateInterval;
}

+ (id)sharedManager;
@property(nonatomic) double updateInterval; // @synthesize updateInterval=_updateInterval;
@property(readonly, nonatomic) IGViewpointUpdater *updater; // @synthesize updater=_updater;
- (void).cxx_destruct;
- (id)impressionActionNames;
- (id)currentlyTrackedDataForActionNames:(id)arg1;
- (struct CGRect)viewport;
- (double)lastImpressionTimeForActionKey:(id)arg1;
- (void)stopTrackingItem:(id)arg1;
- (void)stopTrackingItem:(id)arg1 withActions:(id)arg2;
- (void)startTrackingItem:(id)arg1 withActions:(id)arg2;
- (void)_applicationWillResignActiveNotification:(id)arg1;
- (void)_applicationDidBecomeActiveNotification:(id)arg1;
- (_Bool)_shouldUpdateFrame;
- (void)_tick;
- (void)_calculateframeUpdate;
- (void)_backgroundTick;
- (void)_stopWithReason:(unsigned long long)arg1;
- (void)_startWithReason:(unsigned long long)arg1;
- (void)dealloc;
- (id)initWithUpdater:(id)arg1 updateInterval:(double)arg2 backgroundFrameCalculationEnabled:(_Bool)arg3;
- (id)initWithUpdateInterval:(double)arg1;

@end

