//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGServiceHelperProtocol.h"
#import "IGWeiboAuthDelegate.h"

@class IGUserDefaults, NSString;

@interface IGWeiboHelper : NSObject <IGWeiboAuthDelegate, IGServiceHelperProtocol>
{
    _Bool _isAvailableForSharing;
    _Bool _wantsToShare;
    _Bool _disabled;
    IGUserDefaults *_sessionUserDefaults;
    id <IGAPIClient> _networker;
    NSString *_accessToken;
    NSString *_refreshToken;
}

+ (id)shortServiceName;
+ (id)sharedHelperForUserSession:(id)arg1;
@property(copy, nonatomic) NSString *refreshToken; // @synthesize refreshToken=_refreshToken;
@property(copy, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
@property(retain, nonatomic) id <IGAPIClient> networker; // @synthesize networker=_networker;
@property(retain, nonatomic) IGUserDefaults *sessionUserDefaults; // @synthesize sessionUserDefaults=_sessionUserDefaults;
@property(nonatomic) _Bool disabled; // @synthesize disabled=_disabled;
@property(nonatomic) _Bool wantsToShare; // @synthesize wantsToShare=_wantsToShare;
@property(nonatomic) _Bool isAvailableForSharing; // @synthesize isAvailableForSharing=_isAvailableForSharing;
- (void).cxx_destruct;
- (void)weiboAuthControllerLoginFailed:(id)arg1;
- (void)weiboAuthController:(id)arg1 didLoginWithAccessToken:(id)arg2 andRefreshToken:(id)arg3;
- (void)_saveAccessToken:(id)arg1 andRefreshToken:(id)arg2;
- (void)_saveNewRefreshToken:(id)arg1;
- (void)_saveNewAccessToken:(id)arg1;
- (int)_tokenLife;
- (void)_reauthorize;
- (_Bool)_hasEverBeenConfigured;
- (id)sharingInfo;
- (id)shareKey;
- (id)serviceName;
- (_Bool)requiresLocationCoordinate;
- (_Bool)supportsMediaType:(long long)arg1;
- (_Bool)isAvailableInCurrentLocale;
- (void)setupServerLinkage:(id)arg1;
- (void)reauthorizeIfNeeded;
- (_Bool)needsToReauthorize;
- (id)detailText;
- (_Bool)isConfiguredForCrossPosting;
- (_Bool)shouldUseSubtitleCellStyle;
- (_Bool)hidden;
- (_Bool)isConfiguredOnlyOnServer;
- (_Bool)isConfigured;
- (void)logout;
- (void)logoutAndUnlink;
- (id)viewControllerForAdvancedOptionsWithUserSession:(id)arg1;
@property(readonly, nonatomic) _Bool accessTokenExpired;
- (id)authURL;
- (id)callbackURLString;
- (id)clientID;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

