//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBAnimationPerformanceDisplayLinkTrackingSourceDelegate.h"

@class FBAnimationPerformanceDisplayLinkTrackingSource, FBAnimationPerformanceFrameDropCalculator, NSString;

@interface FBAnimationPerformanceTracker : NSObject <FBAnimationPerformanceDisplayLinkTrackingSourceDelegate>
{
    FBAnimationPerformanceDisplayLinkTrackingSource *_trackingSource;
    FBAnimationPerformanceFrameDropCalculator *_frameDropCalculator;
    struct FBAnimationPerformanceTrackerConfiguration _configuration;
    _Bool _tracking;
    id <FBAnimationPerformanceTrackerDelegate> _delegate;
}

+ (struct FBAnimationPerformanceTrackerConfiguration)standardConfiguration;
@property(nonatomic) __weak id <FBAnimationPerformanceTrackerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)trackingSourceDidUpdateActualFrameTime:(double)arg1 idealFrameTime:(double)arg2;
- (struct FBAnimationPerformanceTrackingResult)stop;
- (_Bool)start;
- (id)initWithConfiguration:(struct FBAnimationPerformanceTrackerConfiguration)arg1;
- (id)initWithConfiguration:(struct FBAnimationPerformanceTrackerConfiguration)arg1 trackingSource:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

