//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBIvarBasedEqualityObject.h"

@class NSString;

@interface FBARNativeUIControlServicePickerConfigurationItem : FBIvarBasedEqualityObject
{
    unsigned long long _subtype;
    NSString *_remoteItem_imageUri;
    NSString *_localItem_textureFileName;
}

+ (id)remoteItemWithImageUri:(id)arg1;
+ (id)localItemWithTextureFileName:(id)arg1;
- (void).cxx_destruct;
- (void)matchRemoteItem:(CDUnknownBlockType)arg1 localItem:(CDUnknownBlockType)arg2;

@end

