//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBARPlatformEventsInput : NSObject
{
    struct shared_ptr<msqrd::dataprovider::platform_events::PlatformEventsInput> _xplatEventInput;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)enqueueEventWithData:(id)arg1;
@property(readonly, nonatomic) shared_ref_4ba0611f xplatEventInput;
- (id)init;

@end

