//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBAutoupdaterDriver.h"

@class NSDateFormatter, NSFileManager;

@interface FBAutoupdaterUpdateDriver : FBAutoupdaterDriver
{
    NSDateFormatter *_dateFormatter;
    NSFileManager *_fileManager;
}

- (void).cxx_destruct;
- (_Bool)_createPathIfNeeded:(id)arg1 error:(id *)arg2;
- (id)_generateTemporaryPath:(id)arg1;
- (id)_generateAppliedDeltaUpdatePath;
- (id)_generateExtractPath;
- (id)_generateDownloadPath;
- (void)_generatingPathForUpdate:(id)arg1;
- (void)removeAllInactiveUpdatesAndResetActiveUpdate;
- (void)_unapplyAppliedUpdate;
- (_Bool)applyUpdate:(id)arg1 error:(id *)arg2;
- (id)initWithDelegate:(id)arg1 delegateQueue:(id)arg2 host:(id)arg3 cleaner:(id)arg4 downloader:(id)arg5 unarchiver:(id)arg6 deltaApplier:(id)arg7 preparer:(id)arg8 verifier:(id)arg9 infoUpdater:(id)arg10 installer:(id)arg11 compatibilityChecker:(id)arg12;

@end

