//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, NSURL;

@protocol FBBusinessExtensionLogging <NSObject>
@property(readonly, nonatomic) unsigned long long instanceID;
- (void)logEvent:(NSString *)arg1 websiteURL:(NSURL *)arg2 messageName:(NSString *)arg3 extra:(NSDictionary *)arg4;
- (void)configureLoggerWithPageID:(NSString *)arg1 logSource:(NSString *)arg2 adID:(NSString *)arg3 appID:(NSString *)arg4 clickSource:(NSString *)arg5;
@end

