//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface FBFileUnarchiverProviderBuilder : NSObject
{
    NSMutableDictionary *_unarchiverByType;
}

- (void).cxx_destruct;
- (id)build;
- (id)registerFileUnarchiver:(id)arg1 forCompressionType:(long long)arg2;
- (id)init;

@end

