//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSError, NSString;

@protocol FBLiveTraceLoggerProtocol
- (void)logEncodingError:(NSError *)arg1;
- (void)logEmbedLiveTraceID:(unsigned int)arg1 bitrate:(int)arg2 framerate:(int)arg3 pts:(CDStruct_1b6d18a9)arg4 dts:(CDStruct_1b6d18a9)arg5;
- (void)logBroadcastInterruptionEnded;
- (void)logBroadcastInterruption:(unsigned long long)arg1;
- (void)logLiveSwapBack;
- (void)logLiveSwap;
- (void)logSessionFailed:(NSString *)arg1 error:(NSError *)arg2;
- (void)logSessionEnded:(NSString *)arg1;
- (void)logSessionStarted:(NSString *)arg1;
@end

