//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBMPOutput.h"

@class FBMPBaseConsumerPort, NSString;

@interface FBMPDataCapturer : NSObject <FBMPOutput>
{
    Class _dataType;
    FBMPBaseConsumerPort *_port;
    struct FBMPDataCapturerCompletionContext _captureCompletionContext;
    struct mutex _lock;
    unsigned long long _dataId;
}

@property(readonly, nonatomic) unsigned long long dataId; // @synthesize dataId=_dataId;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_captureData:(id)arg1 context:(const struct FBMPDataCapturerCompletionContext *)arg2;
- (_Bool)_isCapturingDataWithContext:(const struct FBMPDataCapturerCompletionContext *)arg1;
- (void)captureDataWithCallbackQueue:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)handleData:(id)arg1 withUniqueId:(unsigned long long)arg2;
- (id)consumerPorts;
- (id)initWithDataType:(Class)arg1 dataId:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

