//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBMPFilter.h"
#import "FBMPPermissiveOutput.h"

@class NSArray, NSString;

@interface FBMPCompositeFilter : NSObject <FBMPFilter, FBMPPermissiveOutput>
{
    id <FBMPFilter> _innerFilter;
}

+ (id)newWithFilter:(id)arg1;
- (void).cxx_destruct;
- (void)invalidate;
- (void)sessionDisconnectedPort:(id)arg1 context:(id)arg2;
- (void)sessionConnectedPort:(id)arg1 context:(id)arg2;
- (void)sessionWillStop:(id)arg1;
- (void)sessionWillStart:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *producerPorts;
- (_Bool)allowsConnectionsWithConsumerPortMapping:(id)arg1;
- (id)consumerPorts;
- (id)initWithFilter:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

