//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FBMPFilterHolder : NSObject
{
    id <FBMPFilter> _filter;
}

@property(nonatomic) __weak id <FBMPFilter> filter; // @synthesize filter=_filter;
- (void).cxx_destruct;

@end

