//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBMPCameraUserInterfaceData.h"

@interface FBMPCameraPointOfInterestData : FBMPCameraUserInterfaceData
{
    struct CGRect _bounds;
}

@property(readonly, nonatomic) struct CGRect bounds; // @synthesize bounds=_bounds;
- (id)initWithPOIBounds:(struct CGRect)arg1;

@end

