//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class FBMQTTSocketConfig, NSString, NSURL;

@interface FBMQTTClientConfiguration : FBValueObject <NSCoding, NSCopying>
{
    NSString *_clientID;
    NSString *_regionPreference;
    FBMQTTSocketConfig *_socketConfig;
    NSString *_clientType;
    NSString *_connectionMergeHost;
    NSString *_connectionMergeHostCname;
    NSString *_appID;
    NSURL *_PACFileCheckURL;
}

@property(readonly, copy, nonatomic) NSURL *PACFileCheckURL; // @synthesize PACFileCheckURL=_PACFileCheckURL;
@property(readonly, copy, nonatomic) NSString *appID; // @synthesize appID=_appID;
@property(readonly, copy, nonatomic) NSString *connectionMergeHostCname; // @synthesize connectionMergeHostCname=_connectionMergeHostCname;
@property(readonly, copy, nonatomic) NSString *connectionMergeHost; // @synthesize connectionMergeHost=_connectionMergeHost;
@property(readonly, copy, nonatomic) NSString *clientType; // @synthesize clientType=_clientType;
@property(readonly, copy, nonatomic) FBMQTTSocketConfig *socketConfig; // @synthesize socketConfig=_socketConfig;
@property(readonly, copy, nonatomic) NSString *regionPreference; // @synthesize regionPreference=_regionPreference;
@property(readonly, copy, nonatomic) NSString *clientID; // @synthesize clientID=_clientID;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithClientID:(id)arg1 regionPreference:(id)arg2 socketConfig:(id)arg3 clientType:(id)arg4 connectionMergeHost:(id)arg5 connectionMergeHostCname:(id)arg6 appID:(id)arg7 PACFileCheckURL:(id)arg8;

@end

