//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@class FBAudioConfig, FBSegmentConfig, FBVideoConfig, NSDictionary;

@interface FBVideoTranscoderConfig : NSObject <NSCopying>
{
    NSDictionary *_config;
    FBVideoConfig *_videoConfig;
    FBAudioConfig *_audioConfig;
    FBSegmentConfig *_segmentConfig;
}

@property(readonly, copy, nonatomic) FBSegmentConfig *segmentConfig; // @synthesize segmentConfig=_segmentConfig;
@property(readonly, copy, nonatomic) FBAudioConfig *audioConfig; // @synthesize audioConfig=_audioConfig;
@property(readonly, copy, nonatomic) FBVideoConfig *videoConfig; // @synthesize videoConfig=_videoConfig;
- (void).cxx_destruct;
- (id)config;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithVideoConfig:(id)arg1 audioConfig:(id)arg2 segmentConfig:(id)arg3;
- (id)initWithDictionary:(id)arg1;

@end

