//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGAccountPrivacyChangeListener.h"
#import "IGAccountSettingsAccountPrivacyViewDelegate.h"

@class IGAccountSettingsAccountPrivacyView, IGUserSession, NSString, UITapGestureRecognizer, UIView;

@interface IGAccountSettingsAccountPrivacyViewController : IGViewController <IGAccountPrivacyChangeListener, IGAccountSettingsAccountPrivacyViewDelegate>
{
    IGUserSession *_userSession;
    IGAccountSettingsAccountPrivacyView *_privacyView;
    _Bool _appearingTransitionCompleted;
    UIView *_maskView;
    _Bool _shouldDismissSelfUponNextAppearance;
    UITapGestureRecognizer *_tapToDismissGesture;
}

- (void).cxx_destruct;
- (id)analyticsModule;
- (void)_dismissSelf;
- (void)_backgroundTap:(id)arg1;
- (void)accountPrivacyViewDidSelectCancel:(id)arg1;
- (void)accountPrivacyViewDidSelectSettings:(id)arg1;
- (void)accountPrivacyView:(id)arg1 didTapSavePrivacyStatus:(long long)arg2;
- (void)didAcknowledgePrivacyToggleWarning;
- (void)userSession:(id)arg1 didChangeToPrivacyStatus:(long long)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)prefersTabBarHidden;
- (_Bool)prefersNavigationBarHidden;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

