//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGAdActivityParser : NSObject
{
}

+ (id)parseLastTimeTimestamp:(id)arg1;
+ (_Bool)parseMoreAvailable:(id)arg1;
+ (id)parseNextMaxId:(id)arg1;
+ (id)parseReels:(id)arg1;
+ (id)parseFeedItems:(id)arg1;
+ (id)parseItemWithFeedDict:(id)arg1 reelDict:(id)arg2;

@end

