//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGUsertagCell.h"

@class UIButton;

@interface IGAddPartnerTagCell : IGUsertagCell
{
    UIButton *_removeBtn;
    id <IGAddPartnerTagCellDelegate> _addPartnerTagCellDelegate;
}

@property(nonatomic) __weak id <IGAddPartnerTagCellDelegate> addPartnerTagCellDelegate; // @synthesize addPartnerTagCellDelegate=_addPartnerTagCellDelegate;
@property(retain, nonatomic) UIButton *removeBtn; // @synthesize removeBtn=_removeBtn;
- (void).cxx_destruct;
- (void)_onRemoveTapped;
- (void)configureCellWithDelegate:(id)arg1;
- (void)setShowRemoveButton:(_Bool)arg1;
- (void)layoutSubviews;
- (void)prepareForReuse;

@end

