//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol IGAnalyticsConfiguration <NSObject>
- (_Bool)preventDoubleUploadEnabled;
- (long long)retryDelayTimeInSeconds;
- (_Bool)diagnosticsEventEnabled;
- (_Bool)pigeonSessionFixEnabled;
- (_Bool)retryOffProcessRequestsOnColdStart;
- (double)offProcessTimeout;
- (_Bool)useOffProcessUploader;
- (_Bool)waitForTasksToCompleteOnTermination;
- (_Bool)stripNonJSON;
- (long long)sessionType;
- (_Bool)uploadLogsAfterCleanup;
- (long long)periodicUploadInterval;
- (_Bool)retryUploadIndefinitelyForCertainErrors;
- (_Bool)useSharedContainer;
- (float)postCleanupRetentionRatio;
- (long long)maxNumberOfRetries;
- (long long)logFileBatchSize;
- (long long)maxNumberOfLogFiles;
- (_Bool)aldrinMode;
- (NSString *)facebookID;
- (NSString *)userID;
- (NSString *)deviceID;
- (NSString *)appID;
- (NSString *)clientToken;
- (NSString *)key;
@end

