//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGAnimatedImageViewDelegate.h"
#import "IGDynamicSurfaceStickerViewType.h"
#import "IGStoryOverlayFlippable.h"

@class IGAnimatedImageView, IGAnimatedStickerModel, NSString, UIBezierPath;

@interface IGAnimatedStickerContentView : UIView <IGAnimatedImageViewDelegate, IGDynamicSurfaceStickerViewType, IGStoryOverlayFlippable>
{
    IGAnimatedImageView *_lowQualityImageView;
    IGAnimatedImageView *_highQualityImageView;
    UIBezierPath *_cachedOutlinePath;
    _Bool _outlinePathComputationInProgress;
    IGAnimatedStickerModel *_model;
    id <IGAnimatedStickerContentViewDelegate> _delegate;
}

@property(nonatomic) __weak id <IGAnimatedStickerContentViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) IGAnimatedStickerModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)stickerView;
- (id)loggingId;
- (_Bool)isFlipped;
- (void)flipHorizontally;
- (void)animatedImageView:(id)arg1 didUpdateDownloadProgress:(double)arg2;
- (void)_recomputeOutlinePath;
- (id)outlinePath;
- (id)dynamicOverlayImageProvider;
- (id)storyAssetDiffableIdentifier;
@property(readonly, nonatomic) IGAnimatedImageView *currentAnimatedImageView;
- (void)configureWithModel:(id)arg1 enableHighQualityGIF:(_Bool)arg2;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

