//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGGestureHandler.h"
#import "MAISKStoreProductViewControllerDelegate.h"

@class IGAppStoreLoggingContext, IGUserSession, MAISKStoreProductViewController, NSString, UIView;

@interface IGAppStoreViewController : IGViewController <MAISKStoreProductViewControllerDelegate, IGGestureHandler>
{
    NSString *_iTunesItemIdentifier;
    MAISKStoreProductViewController *_storeProductViewController;
    IGUserSession *_userSession;
    _Bool _isFromPreloading;
    _Bool _shouldUseThreadOptimization;
    UIView *_contentWrapperView;
    UIView *_dismissingSnapshot;
    IGAppStoreLoggingContext *_loggingContext;
    _Bool _fullscreenExperienceEnabled;
    id <IGAppStoreViewControllerDelegate> _delegate;
}

@property(nonatomic, getter=isFullscreenExperienceEnabled) _Bool fullscreenExperienceEnabled; // @synthesize fullscreenExperienceEnabled=_fullscreenExperienceEnabled;
@property(nonatomic) __weak id <IGAppStoreViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_clearStoreProductViewController;
- (_Bool)canRespondToGesture:(id)arg1;
- (id)analyticsModule;
- (void)maiProductViewControllerDidLoad:(id)arg1;
- (void)maiProductViewControllerDidFinish:(id)arg1;
- (void)_setupStoreProductViewController:(_Bool)arg1;
- (void)_loadStoreProductViewControllerIsOnScreen:(_Bool)arg1;
@property(readonly, nonatomic) NSString *iTunesItemIdentifier;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithITunesItemIdentifier:(id)arg1 feedItem:(id)arg2;
- (id)initWithITunesItemIdentifier:(id)arg1 feedItem:(id)arg2 userSession:(id)arg3 isFromPreloading:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

