//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGUserSessionObject.h"

@class IGAppStoreLogger, MAIAppStoreManager, MAISpringPresentationController, NSString;

@interface IGAppStoreManager : NSObject <IGUserSessionObject>
{
    MAIAppStoreManager *_appStoreManager;
    IGAppStoreLogger *_logger;
    MAISpringPresentationController *_presentationController;
}

- (void).cxx_destruct;
- (void)clearAllAppStoreCaches;
- (void)clearAppStoreCacheForFeedItem:(id)arg1;
- (void)startAppStorePrefetchForFeedItem:(id)arg1 shouldUseBackgroundThread:(_Bool)arg2;
- (void)presentAppStoreForITunesIdentifier:(id)arg1 feedItem:(id)arg2 hostViewController:(id)arg3 shouldModallyPresent:(_Bool)arg4 completionBlock:(CDUnknownBlockType)arg5 dismissBlock:(CDUnknownBlockType)arg6;
- (id)initWithConfiguration:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

