//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGAPIRequestBuilder.h"

@interface IGAPIRequestBuilder (Ad)
- (id)addPhoneIDParameter;
- (id)addAdsPaginationParameterWithItems:(id)arg1;
- (id)addBatteryContextParameters;
- (id)addSoundStateParameterForRequestSurface:(unsigned long long)arg1;
- (id)addDeviceIDHeader;
- (id)addAdsHeader;
- (id)addCommonAdParametersAndHeadersForRequestSurface:(unsigned long long)arg1;
@end

