//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSFileManager, NSURL;

@interface IGARFileURLEvictor : NSObject
{
    NSURL *_rootURL;
    unsigned long long _sizeLimit;
    NSFileManager *_fileManager;
}

- (void).cxx_destruct;
- (_Bool)trimToAddSize:(unsigned long long)arg1 error:(id *)arg2;
- (void)updateAccessDateForURL:(id)arg1;
- (id)initWithRootURL:(id)arg1 sizeLimit:(unsigned long long)arg2;

@end

