//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSString;

@interface IGAREffectProfileCTAViewModel : FBValueObject <NSCopying, NSCoding>
{
    NSString *_username;
    NSString *_effectName;
    NSString *_effectID;
    NSString *_mainThumbnailURL;
    NSString *_secondaryThumbnailURL;
    unsigned long long _numberOfEffects;
}

@property(readonly, nonatomic) unsigned long long numberOfEffects; // @synthesize numberOfEffects=_numberOfEffects;
@property(readonly, copy, nonatomic) NSString *secondaryThumbnailURL; // @synthesize secondaryThumbnailURL=_secondaryThumbnailURL;
@property(readonly, copy, nonatomic) NSString *mainThumbnailURL; // @synthesize mainThumbnailURL=_mainThumbnailURL;
@property(readonly, copy, nonatomic) NSString *effectID; // @synthesize effectID=_effectID;
@property(readonly, copy, nonatomic) NSString *effectName; // @synthesize effectName=_effectName;
@property(readonly, copy, nonatomic) NSString *username; // @synthesize username=_username;
- (void).cxx_destruct;
- (id)initWithUsername:(id)arg1 effectName:(id)arg2 effectID:(id)arg3 mainThumbnailURL:(id)arg4 secondaryThumbnailURL:(id)arg5 numberOfEffects:(unsigned long long)arg6;

@end

