//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGAREffectNativeUIControlHandler, IGAREffectNativeUIPickerConfiguration;

@protocol IGAREffectNativeUIControlDelegate
- (void)nativeUIControlServiceHandler:(IGAREffectNativeUIControlHandler *)arg1 shouldChangeSliderValue:(double)arg2;
- (void)nativeUIControlServiceHandlerShouldHideSlider:(IGAREffectNativeUIControlHandler *)arg1;
- (void)nativeUIControlServiceHandler:(IGAREffectNativeUIControlHandler *)arg1 shouldShowSliderWithValueChangedCallback:(void (^)(double))arg2;
- (void)nativeUIControlServiceHandler:(IGAREffectNativeUIControlHandler *)arg1 shouldSelectPickerIndex:(unsigned long long)arg2;
- (void)nativeUIControlServiceHandlerShouldHidePicker:(IGAREffectNativeUIControlHandler *)arg1;
- (void)nativeUIControlServiceHandler:(IGAREffectNativeUIControlHandler *)arg1 shouldShowPickerWithValueChangedCallback:(void (^)(unsigned long long))arg2;
- (void)nativeUIControlServiceHandler:(IGAREffectNativeUIControlHandler *)arg1 shouldConfigurePickerWithConfiguration:(IGAREffectNativeUIPickerConfiguration *)arg2;
@end

