//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSArray, NSDictionary, NSString, NSURL;

@interface IGAREffectModel : NSObject <NSSecureCoding>
{
    _Bool _usesSegmentation;
    _Bool _usesWorldTracker;
    _Bool _usesTargetTracker;
    _Bool _usesTargetRecognition;
    _Bool _hasSound;
    NSString *_effectFileID;
    NSString *_effectPackageID;
    NSString *_effectID;
    NSString *_assetURL;
    NSString *_title;
    NSString *_thumbnailURL;
    NSString *_instructions_DEPRECATED;
    NSArray *_effectInstructions;
    NSDictionary *_mappedEffectInstructions;
    NSString *_sdkVersion;
    NSString *_effectNUX;
    NSString *_localizedEffectName;
    NSString *_attributionUserID;
    NSString *_attributionUsername;
    NSURL *_attributionProfileImageURL;
    NSArray *_moreInfoSheetItems;
    NSArray *_moreInfoSecondaryActionItems;
    long long _arEffectStatus;
    long long _arEffectSurface;
    long long _arEffectType;
    long long _disabledCaptureModes;
    long long _badgeState;
    NSArray *_arCapabilityMinVersionModels;
}

+ (_Bool)supportsSecureCoding;
+ (void)load;
@property(readonly, copy, nonatomic) NSArray *arCapabilityMinVersionModels; // @synthesize arCapabilityMinVersionModels=_arCapabilityMinVersionModels;
@property(readonly, nonatomic) long long badgeState; // @synthesize badgeState=_badgeState;
@property(readonly, nonatomic) long long disabledCaptureModes; // @synthesize disabledCaptureModes=_disabledCaptureModes;
@property(readonly, nonatomic) _Bool hasSound; // @synthesize hasSound=_hasSound;
@property(readonly, nonatomic) long long arEffectType; // @synthesize arEffectType=_arEffectType;
@property(readonly, nonatomic) long long arEffectSurface; // @synthesize arEffectSurface=_arEffectSurface;
@property(readonly, nonatomic) long long arEffectStatus; // @synthesize arEffectStatus=_arEffectStatus;
@property(readonly, copy, nonatomic) NSArray *moreInfoSecondaryActionItems; // @synthesize moreInfoSecondaryActionItems=_moreInfoSecondaryActionItems;
@property(readonly, copy, nonatomic) NSArray *moreInfoSheetItems; // @synthesize moreInfoSheetItems=_moreInfoSheetItems;
@property(readonly, copy, nonatomic) NSURL *attributionProfileImageURL; // @synthesize attributionProfileImageURL=_attributionProfileImageURL;
@property(readonly, copy, nonatomic) NSString *attributionUsername; // @synthesize attributionUsername=_attributionUsername;
@property(readonly, copy, nonatomic) NSString *attributionUserID; // @synthesize attributionUserID=_attributionUserID;
@property(readonly, copy, nonatomic) NSString *localizedEffectName; // @synthesize localizedEffectName=_localizedEffectName;
@property(readonly, copy, nonatomic) NSString *effectNUX; // @synthesize effectNUX=_effectNUX;
@property(readonly, copy, nonatomic) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(readonly, copy, nonatomic) NSDictionary *mappedEffectInstructions; // @synthesize mappedEffectInstructions=_mappedEffectInstructions;
@property(readonly, copy, nonatomic) NSArray *effectInstructions; // @synthesize effectInstructions=_effectInstructions;
@property(readonly, copy, nonatomic) NSString *instructions_DEPRECATED; // @synthesize instructions_DEPRECATED=_instructions_DEPRECATED;
@property(readonly, copy, nonatomic) NSString *thumbnailURL; // @synthesize thumbnailURL=_thumbnailURL;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, copy, nonatomic) NSString *assetURL; // @synthesize assetURL=_assetURL;
@property(readonly, copy, nonatomic) NSString *effectID; // @synthesize effectID=_effectID;
@property(readonly, copy, nonatomic) NSString *effectPackageID; // @synthesize effectPackageID=_effectPackageID;
@property(readonly, copy, nonatomic) NSString *effectFileID; // @synthesize effectFileID=_effectFileID;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly) _Bool isPartnerEffect;
- (_Bool)usesCapability:(unsigned long long)arg1;
- (id)initWithEffectFileID:(id)arg1 effectPackageID:(id)arg2 assetURL:(id)arg3 title:(id)arg4 thumbnailURL:(id)arg5 instructions_DEPRECATED:(id)arg6 effectInstructions:(id)arg7 sdkVersion:(id)arg8 effectID:(id)arg9 arEffectStatus:(long long)arg10 arEffectSurface:(long long)arg11 arEffectType:(long long)arg12 effectNUX:(id)arg13 localizedEffectName:(id)arg14 usesSegmentation:(_Bool)arg15 usesWorldTracker:(_Bool)arg16 usesTargetTracker:(_Bool)arg17 usesTargetRecognition:(_Bool)arg18 hasSound:(_Bool)arg19 disabledCaptureModes:(long long)arg20 badgeState:(long long)arg21 attributionUsername:(id)arg22 attributionUserID:(id)arg23 attributionProfileImageURL:(id)arg24 moreInfoSheetItems:(id)arg25 moreInfoSecondaryActionItems:(id)arg26 arCapabilityMinVersionModels:(id)arg27;

@end

