//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVPlayerItemOutputPullDelegate.h"

@class AVAsset, AVPlayer, AVPlayerItem, AVPlayerItemVideoOutput, AVVideoComposition, CADisplayLink, NSObject<OS_dispatch_queue>, NSString;

@interface IGAVVideoPlayer : NSObject <AVPlayerItemOutputPullDelegate>
{
    id _displayLinkTarget;
    AVPlayer *_player;
    AVPlayerItemVideoOutput *_videoOutput;
    AVPlayerItem *_playerItem;
    NSObject<OS_dispatch_queue> *_videoOutputQueue;
    _Bool _isLooping;
    _Bool _isDisplayLinkInRunLoop;
    _Bool _isSeeking;
    AVAsset *_asset;
    id <IGAVVideoPlayerDelegate> _delegate;
    CADisplayLink *_displayLink;
    CDStruct_1b6d18a9 _startTime;
    CDStruct_1b6d18a9 _seekTime;
    CDStruct_1b6d18a9 _audioVolumeRampDuration;
}

@property(readonly, nonatomic) CDStruct_1b6d18a9 audioVolumeRampDuration; // @synthesize audioVolumeRampDuration=_audioVolumeRampDuration;
@property(nonatomic) CDStruct_1b6d18a9 seekTime; // @synthesize seekTime=_seekTime;
@property(nonatomic) _Bool isSeeking; // @synthesize isSeeking=_isSeeking;
@property(nonatomic) _Bool isDisplayLinkInRunLoop; // @synthesize isDisplayLinkInRunLoop=_isDisplayLinkInRunLoop;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(retain, nonatomic) AVPlayerItemVideoOutput *videoOutput; // @synthesize videoOutput=_videoOutput;
@property(retain, nonatomic) AVPlayer *player; // @synthesize player=_player;
@property(nonatomic) __weak id <IGAVVideoPlayerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isLooping; // @synthesize isLooping=_isLooping;
@property(nonatomic) CDStruct_1b6d18a9 startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) AVAsset *asset; // @synthesize asset=_asset;
- (void).cxx_destruct;
- (void)outputSequenceWasFlushed:(id)arg1;
- (void)outputMediaDataWillChange:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_itemDidFinishPlaying;
- (void)_stopHelperAnimated:(_Bool)arg1;
- (void)_loadBufferAtItemTime:(CDStruct_1b6d18a9)arg1;
- (void)_displayLinkCallback:(id)arg1;
- (_Bool)_isReversed;
- (void)stopWithoutAnimation;
- (void)stop;
- (void)playInReverse;
- (void)play;
- (void)playFromTime:(CDStruct_1b6d18a9)arg1;
- (void)playFromStart;
@property(nonatomic) long long maximumFrameRate;
- (void)seekToTime:(CDStruct_1b6d18a9)arg1;
@property(retain, nonatomic) AVVideoComposition *videoComposition;
@property(readonly, nonatomic) double progress;
@property(readonly, nonatomic) CDStruct_1b6d18a9 duration;
@property(readonly, nonatomic) CDStruct_1b6d18a9 currentTime;
@property(nonatomic) CDStruct_1b6d18a9 endTime;
@property(nonatomic) _Bool isMuted;
- (void)_onAppDidBecomeActive;
- (void)_onAppBackground;
- (void)_addDisplayLinkToRunLoop;
- (id)initWithAsset:(id)arg1 audioVolumeRampDuration:(CDStruct_1b6d18a9)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

