//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGListSectionController.h"

#import "IGBakeoffStoryPairCellDelegate.h"
#import "IGGenericSurveyStoryViewerViewControllerDelegate.h"

@class IGUserSession, NSMutableArray, NSMutableSet, NSString;

@interface IGBakeoffStoryPairSectionController : IGListSectionController <IGBakeoffStoryPairCellDelegate, IGGenericSurveyStoryViewerViewControllerDelegate>
{
    IGUserSession *_userSession;
    NSMutableArray *_storyViewModelList;
    NSMutableArray *_previewViewModelList;
    NSMutableSet *_seenViewModelIndexes;
    NSString *_module;
    id <IGStoryViewerLandscapeAdLayoutListener> _bakeoffLogger;
    id <IGBakeoffStoryPairSectionControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <IGBakeoffStoryPairSectionControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)genericSurveyStoryViewerViewControllerDidMarkStoryAsSeenWithIndex:(long long)arg1;
- (void)bakeoffStoryPairCellDidTapPreviewViewWithIndex:(long long)arg1;
- (void)didUpdateToObject:(id)arg1;
- (id)cellForItemAtIndex:(long long)arg1;
- (struct CGSize)sizeForItemAtIndex:(long long)arg1;
- (id)initWithUserSession:(id)arg1 numberOfItems:(long long)arg2 module:(id)arg3 bakeoffLogger:(id)arg4;

@end

