//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGHashtagFollowStatusUpdateListener.h"

@class IGBloksContext, IGHashtagModel, IGUserSession, NSDictionary, NSObject<BKBloksModel>;

@interface IGBloksHashtagFollowButtonComponentController : NSObject <IGHashtagFollowStatusUpdateListener>
{
    IGUserSession *_session;
    NSObject<BKBloksModel> *_model;
    IGBloksContext *_context;
    NSDictionary *_hashtagModel;
    IGHashtagModel *_hashtag;
}

- (void).cxx_destruct;
- (void)_performLispyFunction:(id)arg1;
- (void)_updateModelWithIsFollowing:(_Bool)arg1;
- (void)_performFollow:(_Bool)arg1;
- (void)_showUnfollowConfirmation;
- (void)_tapped;
- (void)hashtagFollowStatusStoreDidUpdateFollowStatus:(long long)arg1 forHashtagWithName:(id)arg2;
- (void)addTapListenerToView:(id)arg1;
- (void)setComponentModel:(id)arg1 context:(id)arg2;

@end

