//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGGestureHandler.h"

@class IGBloksContext, IGUserSession, NSDictionary, NSString;

@interface IGBloksBottomSheetViewController : IGViewController <IGGestureHandler>
{
    IGUserSession *_session;
    NSDictionary *_content;
    NSDictionary *_bottomSheet;
    NSString *_analyticsModule;
    IGBloksContext *_context;
}

- (void).cxx_destruct;
- (_Bool)canRespondToGesture:(id)arg1;
- (id)analyticsModule;
- (void)loadView;
- (id)initWithSession:(id)arg1 context:(id)arg2 content:(id)arg3 analyticsModule:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

