//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGListDiffable.h"
#import "NSCopying.h"

@class NSArray, NSString;

@interface IGBusinessActionBarViewModel : NSObject <IGListDiffable, NSCopying>
{
    _Bool _showBottomSeparator;
    NSString *_ixButtonTitle;
    NSArray *_actions;
}

@property(retain, nonatomic) NSArray *actions; // @synthesize actions=_actions;
@property(readonly, nonatomic) _Bool showBottomSeparator; // @synthesize showBottomSeparator=_showBottomSeparator;
@property(readonly, copy, nonatomic) NSString *ixButtonTitle; // @synthesize ixButtonTitle=_ixButtonTitle;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
@property(readonly, copy, nonatomic) NSArray *availableActions;
- (id)initWithUser:(id)arg1 userSession:(id)arg2 showShareButton:(_Bool)arg3;

@end

