//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGGroupedTableViewController.h"

@class IGBusinessReportLocationLinkingDataSource;

@interface IGBusinessLocationLinkingReportViewController : IGGroupedTableViewController
{
    id <IGBusinessLocationLinkingReportViewControllerDelegate> _reportDelegate;
    IGBusinessReportLocationLinkingDataSource *_dataSource;
}

@property(readonly, copy, nonatomic) IGBusinessReportLocationLinkingDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <IGBusinessLocationLinkingReportViewControllerDelegate> reportDelegate; // @synthesize reportDelegate=_reportDelegate;
- (void).cxx_destruct;
- (id)analyticsModule;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)titleForHeaderInSection:(long long)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;
- (id)initWithDataSource:(id)arg1;

@end

