//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGBusinessConversionFacebookPageCategory, IGBusinessFBPageCreationConfigurationViewController, NSString;

@protocol IGBusinessFBPageCreationConfigurationViewControllerDelegate <NSObject>
- (_Bool)isSuperCategorySelected;
- (void)configurationViewControllerStartEditingSearchBox:(IGBusinessFBPageCreationConfigurationViewController *)arg1;
- (void)configurationViewControllerStartTyping:(IGBusinessFBPageCreationConfigurationViewController *)arg1 searchText:(NSString *)arg2;
- (void)configurationViewController:(IGBusinessFBPageCreationConfigurationViewController *)arg1 didSelectCategoryFromSearch:(IGBusinessConversionFacebookPageCategory *)arg2;
- (void)configurationViewControllerDidClickOutsideCategoryArea:(IGBusinessFBPageCreationConfigurationViewController *)arg1;
- (void)configurationViewControllerDidBeginEnteringCategoryName:(IGBusinessFBPageCreationConfigurationViewController *)arg1;
- (void)configurationViewControllerDidClickSuggestedCategoryCell:(IGBusinessFBPageCreationConfigurationViewController *)arg1 withCategory:(IGBusinessConversionFacebookPageCategory *)arg2;
- (void)configurationViewControllerDidClickSubCategoryCell:(IGBusinessFBPageCreationConfigurationViewController *)arg1;
- (void)configurationViewControllerDidClickSuperCategoryCell:(IGBusinessFBPageCreationConfigurationViewController *)arg1;
- (void)configurationViewControllerDidClickSuggestedPageNameCell:(IGBusinessFBPageCreationConfigurationViewController *)arg1;
- (void)configurationViewControllerDidClickOutsidePageTitleArea:(IGBusinessFBPageCreationConfigurationViewController *)arg1;
- (void)configurationViewControllerDidBeginEnteringPageName:(IGBusinessFBPageCreationConfigurationViewController *)arg1;
- (void)configurationViewControllerDidLoad:(IGBusinessFBPageCreationConfigurationViewController *)arg1;
- (void)configurationViewController:(IGBusinessFBPageCreationConfigurationViewController *)arg1 didFinishEnteringPageName:(NSString *)arg2;
@end

