//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGBusinessAttributeSyncInfo, IGBusinessAttributeSyncNetworker, NSDictionary, NSError;

@protocol IGBusinessAttributeSyncNetworkerDelegate <NSObject>
- (void)businessAttributeSyncNetworker:(IGBusinessAttributeSyncNetworker *)arg1 fetchFailedWithError:(NSError *)arg2 responseDict:(NSDictionary *)arg3;
- (void)businessAttributeSyncNetworker:(IGBusinessAttributeSyncNetworker *)arg1 didUpdateAttributeData:(IGBusinessAttributeSyncInfo *)arg2;
- (void)businessAttributeSyncNetworker:(IGBusinessAttributeSyncNetworker *)arg1 didFetchBusinessAttributeDataModel:(IGBusinessAttributeSyncInfo *)arg2;
@end

