//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGBusinessConversionEditableProfileCell.h"

@class NSString, UILabel, UIView;

@interface IGBusinessConversionEditableProfileInlineErrorCell : IGBusinessConversionEditableProfileCell
{
    UILabel *_errorLabel;
    UIView *_containerView;
    NSString *_errorMessage;
}

+ (id)_errorMessageFont;
+ (struct CGSize)_errorMessageSize:(id)arg1 withWidth:(double)arg2;
+ (double)cellHeightForErrorMessage:(id)arg1 withWidth:(double)arg2;
@property(copy, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UILabel *errorLabel; // @synthesize errorLabel=_errorLabel;
- (void).cxx_destruct;
- (void)prepareForReuse;
- (void)layoutSubviews;

@end

