//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGListDiffable.h"

@class IGCanvasButton, IGCanvasButtonViewModel, IGCanvasElementContext;

@interface IGCanvasFooterViewModel : NSObject <IGListDiffable>
{
    IGCanvasElementContext *_context;
    IGCanvasButton *_button;
    IGCanvasButtonViewModel *_buttonViewModel;
}

@property(readonly, nonatomic) IGCanvasButtonViewModel *buttonViewModel; // @synthesize buttonViewModel=_buttonViewModel;
@property(readonly, nonatomic) IGCanvasButton *button; // @synthesize button=_button;
@property(readonly, nonatomic) IGCanvasElementContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (id)initWithButtonViewModel:(id)arg1 context:(id)arg2 button:(id)arg3;

@end

