//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGCameraConfig : NSObject
{
    _Bool _removeInputsAndOutputsWhenStopped;
    _Bool _multiCaptureEnabled;
    _Bool _allowAudioSessionDeactivation;
    long long _cameraPosition;
    long long _captureManagerMode;
}

+ (id)shoppingCameraConfigWithCameraPosition:(long long)arg1;
+ (id)ARLinkScanCameraConfig;
+ (id)videoCallCameraConfig;
+ (id)walkieTalkieConfigWithCameraPosition:(long long)arg1;
+ (id)liveConfigWithCameraPosition:(long long)arg1;
+ (id)storyCameraConfigWithCameraPosition:(long long)arg1 removeInputsAndOutputsWhenStopped:(_Bool)arg2;
@property(readonly, nonatomic) _Bool allowAudioSessionDeactivation; // @synthesize allowAudioSessionDeactivation=_allowAudioSessionDeactivation;
@property(readonly, nonatomic) _Bool multiCaptureEnabled; // @synthesize multiCaptureEnabled=_multiCaptureEnabled;
@property(readonly, nonatomic) _Bool removeInputsAndOutputsWhenStopped; // @synthesize removeInputsAndOutputsWhenStopped=_removeInputsAndOutputsWhenStopped;
@property(readonly, nonatomic) long long captureManagerMode; // @synthesize captureManagerMode=_captureManagerMode;
@property(readonly, nonatomic) long long cameraPosition; // @synthesize cameraPosition=_cameraPosition;
- (id)initWithCameraPosition:(long long)arg1 removeInputsAndOutputsWhenStopped:(_Bool)arg2 allowAudioSessionDeactivation:(_Bool)arg3 multiCaptureEnabled:(_Bool)arg4 captureManagerMode:(long long)arg5;

@end

