//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGChainingContainerViewController;

@protocol IGChainingContainerDelegate <NSObject>
- (_Bool)hasShownPillInCurrentExploreSession:(IGChainingContainerViewController *)arg1;
- (void)chainingContainerDidShowPill:(IGChainingContainerViewController *)arg1;
@end

