//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGUserSessionEndingObject.h"

@class IGDiskCache, IGUserSession, NSArray, NSLock, NSMutableOrderedSet, NSObject<OS_dispatch_queue>, NSString;

@interface IGCLLocationCache : NSObject <IGUserSessionEndingObject>
{
    IGUserSession *_userSession;
    NSMutableOrderedSet *_locations;
    NSLock *_lock;
    IGDiskCache *_locationCache;
    NSString *_cacheKey;
    NSObject<OS_dispatch_queue> *_ioQueue;
}

- (void).cxx_destruct;
- (void)userSessionWillEndWithReason:(unsigned long long)arg1;
- (void)_io_queue_writeLocationsToDisk:(id)arg1;
- (id)_io_queue_objectForKey:(id)arg1;
- (void)_filterOutDatedLocations;
- (void)_shrinkToFit;
- (void)_sortLocations;
- (void)_clearMemoryCache;
@property(readonly, nonatomic) NSArray *locations;
- (void)clearCache;
- (void)loadCacheWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)removeLocations:(id)arg1;
- (void)addLocations:(id)arg1;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

