//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGCommentTextViewProtocol.h"

@class NSString, UILabel;

@interface IGCommentCommentingDisabledView : UIView <IGCommentTextViewProtocol>
{
    UILabel *_titleLabel;
    UIView *_separatorLineView;
}

- (void).cxx_destruct;
- (id)autocompleteTextInput;
- (void)clearText;
- (void)addSendButtonTappedTarget:(id)arg1 action:(SEL)arg2;
- (void)setButtonEnabled:(_Bool)arg1;
- (void)insertText:(id)arg1;
- (void)setText:(id)arg1;
- (void)setPlaceholderText:(id)arg1;
- (void)setTextViewDelegate:(id)arg1;
- (id)textView;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

