//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGUser, NSString;

@interface IGCountdownStickerConsumptionModelBuilder : NSObject
{
    NSString *_pk;
    NSString *_text;
    NSString *_textColor;
    NSString *_startBackgroundColor;
    NSString *_endBackgroundColor;
    NSString *_digitColor;
    NSString *_digitCardColor;
    double _endUnixTimestamp;
    _Bool _followingEnabled;
    IGUser *_attributionUser;
    _Bool _isViewerCountdownOwner;
    _Bool _isViewerFollowing;
}

+ (id)countdownStickerConsumptionModelFromExistingCountdownStickerConsumptionModel:(id)arg1;
+ (id)countdownStickerConsumptionModel;
- (void).cxx_destruct;
- (id)withIsViewerFollowing:(_Bool)arg1;
- (id)withIsViewerCountdownOwner:(_Bool)arg1;
- (id)withAttributionUser:(id)arg1;
- (id)withFollowingEnabled:(_Bool)arg1;
- (id)withEndUnixTimestamp:(double)arg1;
- (id)withDigitCardColor:(id)arg1;
- (id)withDigitColor:(id)arg1;
- (id)withEndBackgroundColor:(id)arg1;
- (id)withStartBackgroundColor:(id)arg1;
- (id)withTextColor:(id)arg1;
- (id)withText:(id)arg1;
- (id)withPk:(id)arg1;
- (id)build;

@end

