//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGGestureHandler.h"

@class IGUserSession, NSString;

@interface IGCoWatchContentPickerViewController : UIViewController <IGGestureHandler>
{
    IGUserSession *_userSession;
    id <IGCoWatchContentPickerViewControllerDelegate> _delegate;
    UIViewController *_savedViewController;
    IGCoWatchContentPickerViewController *globalSelf;
}

- (void).cxx_destruct;
- (_Bool)canRespondToGesture:(id)arg1;
- (void)savedMediaFeedViewController:(id)arg1 didSelectFeedItem:(id)arg2;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

