//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGDirectShareRecipientProvider.h"

@class IGCompositionConditionalExecutor, IGUser, IGUserBootstrapService, IGUserDefaults, NSArray;

@interface IGCrossReshareRecipientProvider : NSObject <IGDirectShareRecipientProvider>
{
    IGUser *_user;
    IGUserBootstrapService *_userBootstrapService;
    id <IGAPIClient> _networker;
    NSArray *_defaultUsers;
    NSArray *_topUsers;
    _Bool _isLoaded;
    IGCompositionConditionalExecutor *_conditionalExecutor;
    IGUserDefaults *_userDefaults;
}

- (void).cxx_destruct;
- (id)_defaultRecipientsFileURLWithUserPK:(id)arg1;
- (void)_persistDefaultRecipientsResponseDict:(id)arg1 userPK:(id)arg2;
- (void)_fetchDefaultRecipientsFromNetworkWithUserPK:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_fetchDefaultRecipientsFromDiskWithUserPK:(id)arg1 cacheMissBlock:(CDUnknownBlockType)arg2 cacheHitBlock:(CDUnknownBlockType)arg3;
- (void)_configureWithUser:(id)arg1 experimentSet:(id)arg2;
- (void)executeWhenReshareRecipientProviderIsReady:(CDUnknownBlockType)arg1;
- (id)topUsersForLimit:(long long)arg1;
- (id)defaultRecipients;
- (id)initWithUser:(id)arg1 experimentSet:(id)arg2;

@end

