//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGCustomSlider;

@protocol IGCustomSliderDelegate <NSObject>
- (void)sliderDidReceiveTapOnThumb:(IGCustomSlider *)arg1;
- (void)sliderDidEndSliding:(IGCustomSlider *)arg1;
- (void)sliderDidChangeValue:(IGCustomSlider *)arg1;
- (void)sliderDidBeginSliding:(IGCustomSlider *)arg1;
@end

