//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDeviceMotionManager;

@protocol IGDeviceMotionManagerDelegate <NSObject>
- (void)motionManagerDidDetectDeviceLowered:(IGDeviceMotionManager *)arg1;
- (void)motionManagerDidDetectDeviceRaised:(IGDeviceMotionManager *)arg1;
@end

