//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CMMotionManager, FBTimer;

@interface IGDeviceMotionManager : NSObject
{
    long long _state;
    CMMotionManager *_motionManager;
    FBTimer *_proximityTimer;
    id <IGDeviceMotionManagerDelegate> _delegate;
}

@property(nonatomic) __weak id <IGDeviceMotionManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_proximityTimerDidFire;
- (void)_stopProximityTimer;
- (void)_restartProximityTimer;
- (void)_didExitProximityState;
- (void)_didEnterProximityState;
- (void)_proximityStateDidChange;
- (void)_stopProximityMonitoring;
- (void)_startProximityMonitoring;
- (void)_handleMotionUpdate:(id)arg1;
- (void)_stopMotionUpdates;
- (void)_startMotionUpdates;
- (void)stopTracking;
- (void)startTracking;
- (void)_updateState:(long long)arg1;
- (void)_setup;
- (id)init;

@end

