//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGFeedItemLoggerCreator.h"

@class IGSessionTracker, IGUserSession;

@interface IGDefaultFeedItemLoggerCreator : NSObject <IGFeedItemLoggerCreator>
{
    IGSessionTracker *_sessionTracker;
    IGUserSession *_userSession;
    id <IGFeedItemConfigurationType> _feedItemConfiguration;
}

- (void).cxx_destruct;
- (id)createFeedItemLoggerWithListAdapter:(id)arg1;
- (id)initWithUserSession:(id)arg1 sessionTracker:(id)arg2 feedItemConfiguration:(id)arg3;

@end

