//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGListItemViewProvider.h"

@class IGDetailedDisclosureView, IGDetailedDisclosureViewModel, IGSettingsDescriptionBodyView, IGTableLayoutSpec;

@interface IGDetailedDisclosureViewProvider : NSObject <IGListItemViewProvider>
{
    IGTableLayoutSpec *_layoutSpec;
    IGSettingsDescriptionBodyView *_bodyView;
    IGDetailedDisclosureView *_disclosureView;
    _Bool selected;
    id <IGListItemViewProviderDelegate> providerDelegate;
    IGDetailedDisclosureViewModel *_viewModel;
    struct UIEdgeInsets _leadingViewInsets;
}

@property(retain, nonatomic) IGDetailedDisclosureViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak id <IGListItemViewProviderDelegate> providerDelegate; // @synthesize providerDelegate;
@property(nonatomic) _Bool selected; // @synthesize selected;
@property(readonly, nonatomic) struct UIEdgeInsets leadingViewInsets; // @synthesize leadingViewInsets=_leadingViewInsets;
@property(readonly, nonatomic) IGTableLayoutSpec *layoutSpec; // @synthesize layoutSpec=_layoutSpec;
- (void).cxx_destruct;
- (_Bool)trailingViewDeterminesOwnSize;
- (long long)trailingViewAlignment;
- (id)trailingContentView;
- (id)leadingContentView;
- (double)heightForBodyFittingSize:(struct CGSize)arg1;
- (id)bodyContentView;
- (id)initWithLayoutSpec:(id)arg1;

@end

