//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "IGListDiffable.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class NSString;

@interface IGDirectGroupNameViewModel : FBValueObject <IGListDiffable, NSCopying, NSCoding>
{
    NSString *_labelTitle;
    NSString *_placeholderText;
    NSString *_accessibilityLabel;
    NSString *_accessibilityIdentifier;
    NSString *_textFieldText;
    double _cellHeight;
}

@property(readonly, nonatomic) double cellHeight; // @synthesize cellHeight=_cellHeight;
@property(readonly, copy, nonatomic) NSString *textFieldText; // @synthesize textFieldText=_textFieldText;
@property(readonly, copy, nonatomic) NSString *accessibilityIdentifier; // @synthesize accessibilityIdentifier=_accessibilityIdentifier;
@property(readonly, copy, nonatomic) NSString *accessibilityLabel; // @synthesize accessibilityLabel=_accessibilityLabel;
@property(readonly, copy, nonatomic) NSString *placeholderText; // @synthesize placeholderText=_placeholderText;
@property(readonly, copy, nonatomic) NSString *labelTitle; // @synthesize labelTitle=_labelTitle;
- (void).cxx_destruct;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (id)initWithLabelTitle:(id)arg1 placeholderText:(id)arg2 accessibilityLabel:(id)arg3 accessibilityIdentifier:(id)arg4 textFieldText:(id)arg5 cellHeight:(double)arg6;

@end

