//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface IGDirectPivotSUDataModel : NSObject
{
    _Bool _showPill;
    NSArray *_suggestions;
}

@property(readonly, nonatomic) _Bool showPill; // @synthesize showPill=_showPill;
@property(readonly, nonatomic) NSArray *suggestions; // @synthesize suggestions=_suggestions;
- (void).cxx_destruct;
- (id)initWithSuggestions:(id)arg1 showPill:(_Bool)arg2;

@end

