//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGDirectMutationRequestProcessing.h"

@class IGDirectCache, IGDirectMessageVote, IGDirectMutationNetworker, NSString;

@interface IGDirectMessageOutgoingVoteUpdateMutationProcessor : NSObject <IGDirectMutationRequestProcessing>
{
    IGDirectMessageVote *_vote;
    IGDirectMutationNetworker *_networker;
    IGDirectCache *_directCache;
}

- (void).cxx_destruct;
- (void)_updateVisualMessageByApplyingVote:(_Bool)arg1;
- (void)_applyFailureState;
- (void)_applyInitialOptimisticState;
- (void)handleMutationStateChange:(id)arg1;
- (void)executeWithResultHandler:(id)arg1 accessoryPackage:(id)arg2;
- (id)initWithVote:(id)arg1 directCache:(id)arg2 networker:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

