//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGDirectBadgeCountTracking.h"
#import "IGDirectRealtimeIrisSubscriptionHandlerListener.h"

@class IGDirectBadgeCountEntry, IGDirectBadgeCountRequestNetworker, IGDirectBadgeCountTrackerListenerAnnouncer, IGDirectBadgingAppGroupFileManager, IGUserSession, NSObject<OS_dispatch_queue>, NSString;

@interface IGDirectCrossAppBasedBadgeCountTracker : NSObject <IGDirectRealtimeIrisSubscriptionHandlerListener, IGDirectBadgeCountTracking>
{
    IGUserSession *_userSession;
    IGDirectBadgeCountTrackerListenerAnnouncer *_announcer;
    IGDirectBadgingAppGroupFileManager *_badgingAppGroupFileManager;
    IGDirectBadgeCountRequestNetworker *_badgeCountRequestNetworker;
    NSObject<OS_dispatch_queue> *_queue;
    IGDirectBadgeCountEntry *_badgeCountEntry;
}

@property(copy) IGDirectBadgeCountEntry *badgeCountEntry; // @synthesize badgeCountEntry=_badgeCountEntry;
- (void).cxx_destruct;
- (void)_connectToIrisWithSequenceId:(id)arg1 badgeCountAtMs:(id)arg2;
- (void)_updateBadgeCountEntryIfNeeded:(id)arg1 isFromAppGroupFileManager:(_Bool)arg2;
- (void)_fetchBadgeCountEntryFromAppGroupFileManager;
- (void)_didFetchDirectBadgeFromServer:(id)arg1 badgeCountAtMs:(id)arg2;
- (void)_fetchDirectBadgeFromServer;
- (void)_appWillEnterForegroundNotification:(id)arg1;
- (void)irisSubscriptionHandlerRequiresResnapshot;
- (void)irisSubscriptionHandlerDidConnectAtSequenceId:(id)arg1 latestServerSequenceId:(id)arg2;
- (void)irisSubscriptionHandlerWillConnectAtSequenceId:(id)arg1;
- (void)updateWithBadgeCountEntry:(id)arg1;
- (unsigned long long)directBadgeCount;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (id)initWithUserSession:(id)arg1 badgingAppGroupFileManager:(id)arg2 irisSubscriptionHandler:(id)arg3 queue:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

