//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDirectMutationRequest, IGDirectSendError;

@protocol IGDirectMutationManagerListener <NSObject>
- (void)mutationRequestFailedAndIsIneligibleForAutoRetry:(IGDirectMutationRequest *)arg1 withError:(IGDirectSendError *)arg2;
- (void)mutationRequestDidSucceed:(IGDirectMutationRequest *)arg1;
- (void)mutationRequestWasAcknowledged:(IGDirectMutationRequest *)arg1;
@end

