//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGAnalyticsModule.h"
#import "IGDirectRecipientListViewControllerDelegate.h"
#import "IGDirectRecipientListViewControllerPresentationDelegate.h"
#import "IGDirectShareSheetControlling.h"
#import "IGKeyboardObserverFrameChangeDelegate.h"
#import "MFMessageComposeViewControllerDelegate.h"

@class IGDirectSharePrivacyBanner, IGFeedItem, IGKeyboardObserver, IGNavigationController, IGPassthroughView, IGPostItem, IGStoryViewerLoggingContext, IGStoryViewerViewModel, IGUserSession, IGViewController, IGViewController<IGDirectRecipientListViewControllerType>, NSOrderedSet, NSString, UIImpactFeedbackGenerator, UIView, UIViewController;

@interface IGDirectVerticalShareSheetController : NSObject <IGDirectRecipientListViewControllerDelegate, IGDirectRecipientListViewControllerPresentationDelegate, IGKeyboardObserverFrameChangeDelegate, MFMessageComposeViewControllerDelegate, IGAnalyticsModule, IGDirectShareSheetControlling>
{
    unsigned long long _state;
    IGNavigationController *_navController;
    IGPassthroughView *_shareSheetContainerView;
    UIView *_overlayView;
    IGDirectSharePrivacyBanner *_warningBanner;
    IGKeyboardObserver *_keyboardObserver;
    NSOrderedSet *_selectedRecipients;
    UIImpactFeedbackGenerator *_impactGenerator;
    id <IGDirectShareSheetControllerDelegate> _delegate;
    id <IGDirectVerticalShareSheetWarningMessageDataSource> _warningMessageDataSource;
    UIViewController *_hostingViewController;
    IGViewController *_sourceViewController;
    _Bool _keyboardIsVisible;
    struct CGRect _viewInitialRect;
    struct CGPoint _bannerInitialOrigin;
    IGPostItem *_selectedPost;
    id <IGStoryItemType> _currentStoryItem;
    IGStoryViewerLoggingContext *_storyViewerLoggingContext;
    IGStoryViewerViewModel *_storyViewerViewModel;
    id <IGFeedItemWithCarouselLoggingProviderDelegate><IGFeedItemDirectResponseLoggingProviderDelegate><IGFeedItemVideoLoggingProviderDelegate> _loggingProvider;
    IGFeedItem *_feedItem;
    IGUserSession *_userSession;
    IGViewController<IGDirectRecipientListViewControllerType> *_recipientListViewController;
}

@property(retain, nonatomic) IGViewController<IGDirectRecipientListViewControllerType> *recipientListViewController; // @synthesize recipientListViewController=_recipientListViewController;
@property(readonly, nonatomic) IGUserSession *userSession; // @synthesize userSession=_userSession;
@property(nonatomic) __weak id <IGDirectVerticalShareSheetWarningMessageDataSource> warningMessageDataSource; // @synthesize warningMessageDataSource=_warningMessageDataSource;
@property(nonatomic) __weak id <IGDirectShareSheetControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)analyticsModule;
- (void)messageComposeViewController:(id)arg1 didFinishWithResult:(long long)arg2;
- (_Bool)isFullscreen;
- (void)keyboardObserver:(id)arg1 keyboardFrameWillChangeWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(long long)arg5;
- (void)keyboardObserver:(id)arg1 keyboardFrameDidChangeWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(long long)arg5;
- (void)_popButton:(id)arg1;
- (struct UIEdgeInsets)_backgroundViewInsetsForState:(unsigned long long)arg1;
- (_Bool)_isCurrentlyFullscreen;
- (void)selectRecipientViewController:(id)arg1 wantsToToggleFullScreen:(_Bool)arg2;
- (void)selectRecipientViewController:(id)arg1 didTapRecipient:(id)arg2 selected:(_Bool)arg3;
- (void)selectRecipientViewController:(id)arg1 didUpdateSelectedRecipients:(id)arg2;
- (void)_presentReplyToAuthorViewControllerForFeedItem:(id)arg1;
- (void)selectRecipientViewController:(id)arg1 didTapWhatsappShareWithFeedItem:(id)arg2;
- (void)selectRecipientViewController:(id)arg1 didTapSMSShareWithFeedItem:(id)arg2;
- (void)selectRecipientViewController:(id)arg1 didTapGeneralShareWithFeedItem:(id)arg2;
- (void)selectRecipientViewController:(id)arg1 didTapCopyLinkWithFeedItem:(id)arg2;
- (void)selectRecipientViewController:(id)arg1 didTapDirectReplyToAuthorWithFeedItem:(id)arg2;
- (void)selectRecipientViewControllerDidPresentFullscreen:(id)arg1;
- (void)selectRecipientViewController:(id)arg1 didSwipeOnHeaderWithDirection:(unsigned long long)arg2;
- (void)selectRecipientViewControllerDidTapBackButton:(id)arg1;
- (void)selectRecipientViewControllerDidDismissRecipientList:(id)arg1 selectedStorySendTarget:(long long)arg2 selectedExternalServices:(id)arg3 selectedDirectRecipients:(id)arg4 recipientsFromSearch:(id)arg5 bumpedRecipients:(id)arg6 oneTapStateTracker:(id)arg7 fromOneTap:(_Bool)arg8;
- (void)selectRecipientViewControllerDidTapFinishButton:(id)arg1 storySendTarget:(long long)arg2 sender:(id)arg3 directRecipients:(id)arg4 externalServices:(id)arg5 text:(id)arg6 fromOneTap:(_Bool)arg7 storyViewerViewModel:(id)arg8 storyViewerLoggingContext:(id)arg9 currentStoryItem:(id)arg10 loggingProvider:(id)arg11 feedItem:(id)arg12;
- (id)selectedRecipientsSoFarFromOneTapping:(id)arg1;
- (void)selectRecipientViewController:(id)arg1 didOneTapSendToSharedStories:(id)arg2;
- (void)selectRecipientViewControllerDidTapAddToHighlight:(id)arg1;
- (void)selectRecipientViewController:(id)arg1 didOneTapSendToBlastList:(id)arg2;
- (void)selectRecipientViewController:(id)arg1 didOneTapSendToDirectRecipient:(id)arg2 messageText:(id)arg3;
- (void)selectRecipientViewController:(id)arg1 didOneTapSendToExternalService:(long long)arg2;
- (void)selectRecipientViewController:(id)arg1 didOneTapSendToStoryTarget:(long long)arg2;
- (void)_onTapOverlayView;
- (void)_dismissShareSheetAnimated:(_Bool)arg1 logCancellation:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (CDUnknownBlockType)_fullscreenStateChangesWithViewHeight:(double)arg1;
- (void)_updateState:(unsigned long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)dismissShareSheetAnimated:(_Bool)arg1 logCancellation:(_Bool)arg2;
- (_Bool)isDirectShareSheetOnScreen;
- (void)presentShareSheetWithOverlayView:(_Bool)arg1 directRecipientConfiguration:(id)arg2 feedItem:(id)arg3 selectedPost:(id)arg4 productItem:(id)arg5 storyViewModel:(id)arg6 storyViewerLoggingContext:(id)arg7 currentStoryItem:(id)arg8 commentModel:(id)arg9 hostingViewController:(id)arg10 loggingProvider:(id)arg11;
- (void)dealloc;
- (id)initWithUserSession:(id)arg1 sourceViewController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

