//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDirectMediaViewerViewController;

@protocol IGDirectMediaViewerDismissDelegate <NSObject>
- (void)didEndDraggingMediaViewer:(IGDirectMediaViewerViewController *)arg1 mediaCenter:(struct CGPoint)arg2;
- (void)mediaViewerDidDismiss:(IGDirectMediaViewerViewController *)arg1;
- (void)mediaViewerWillDismiss:(IGDirectMediaViewerViewController *)arg1;
@end

