//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDirectMessageMetadata, NSString;

@interface IGDirectLiveVideoDiffIdentifier : NSObject
{
    NSString *_broadcastId;
    IGDirectMessageMetadata *_metadata;
}

@property(readonly, nonatomic) IGDirectMessageMetadata *metadata; // @synthesize metadata=_metadata;
@property(readonly, copy, nonatomic) NSString *broadcastId; // @synthesize broadcastId=_broadcastId;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithBroacastId:(id)arg1 metadata:(id)arg2;

@end

