//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "IGDiscoveryGridItem.h"
#import "IGListDiffable.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class IGDiscoveryTopicModel, IGGridLayoutSpec, NSArray, NSString;

@interface IGDiscoveryShoppingViewModel : FBValueObject <IGDiscoveryGridItem, IGListDiffable, NSCopying, NSCoding>
{
    NSString *_identifier;
    IGDiscoveryTopicModel *_topicModel;
    NSArray *_coverPhotos;
    IGGridLayoutSpec *_gridLayoutSpec;
}

@property(readonly, copy, nonatomic) IGGridLayoutSpec *gridLayoutSpec; // @synthesize gridLayoutSpec=_gridLayoutSpec;
@property(readonly, copy, nonatomic) NSArray *coverPhotos; // @synthesize coverPhotos=_coverPhotos;
@property(readonly, copy, nonatomic) IGDiscoveryTopicModel *topicModel; // @synthesize topicModel=_topicModel;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (id)initWithIdentifier:(id)arg1 topicModel:(id)arg2 coverPhotos:(id)arg3 gridLayoutSpec:(id)arg4;

@end

