//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class IGDirectOutgoingMessageContent, NSDate, NSString;

@interface IGDirectOutgoingMessage : FBValueObject <NSCopying, NSCoding>
{
    NSString *_clientContext;
    NSString *_threadId;
    IGDirectOutgoingMessageContent *_content;
    NSDate *_latestPublishedMessageSentDate;
    NSDate *_userSendDate;
}

@property(readonly, copy, nonatomic) NSDate *userSendDate; // @synthesize userSendDate=_userSendDate;
@property(readonly, copy, nonatomic) NSDate *latestPublishedMessageSentDate; // @synthesize latestPublishedMessageSentDate=_latestPublishedMessageSentDate;
@property(readonly, copy, nonatomic) IGDirectOutgoingMessageContent *content; // @synthesize content=_content;
@property(readonly, copy, nonatomic) NSString *threadId; // @synthesize threadId=_threadId;
@property(readonly, copy, nonatomic) NSString *clientContext; // @synthesize clientContext=_clientContext;
- (void).cxx_destruct;
- (id)initWithClientContext:(id)arg1 threadId:(id)arg2 content:(id)arg3 latestPublishedMessageSentDate:(id)arg4 userSendDate:(id)arg5;

@end

