//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSDate, NSString;

@interface IGDirectInboxCursor : FBValueObject <NSCopying, NSCoding>
{
    NSString *_threadIdV2;
    NSDate *_lastActivityServerDate;
}

@property(readonly, copy, nonatomic) NSDate *lastActivityServerDate; // @synthesize lastActivityServerDate=_lastActivityServerDate;
@property(readonly, copy, nonatomic) NSString *threadIdV2; // @synthesize threadIdV2=_threadIdV2;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithThreadIdV2:(id)arg1 lastActivityServerDate:(id)arg2;
- (id)initWithCoder:(id)arg1;

@end

