//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class IGDirectMutationRequestStatus, NSArray, NSString;

@interface IGDirectMutationOptimisticUpdateInfo : FBValueObject <NSCopying, NSCoding>
{
    NSString *_mutationId;
    NSString *_threadId;
    NSArray *_updates;
    IGDirectMutationRequestStatus *_status;
}

@property(readonly, copy, nonatomic) IGDirectMutationRequestStatus *status; // @synthesize status=_status;
@property(readonly, copy, nonatomic) NSArray *updates; // @synthesize updates=_updates;
@property(readonly, copy, nonatomic) NSString *threadId; // @synthesize threadId=_threadId;
@property(readonly, copy, nonatomic) NSString *mutationId; // @synthesize mutationId=_mutationId;
- (void).cxx_destruct;
- (id)initWithMutationId:(id)arg1 threadId:(id)arg2 updates:(id)arg3 status:(id)arg4;

@end

