//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDirectComposerMode, NSString;

@protocol IGDirectComposerTextListener <NSObject>
- (void)composerDidEndEditing:(id <IGDirectComposerProtocol>)arg1;
- (void)composerDidBeginEditing:(id <IGDirectComposerProtocol>)arg1;
- (void)composerDidTapOnTextArea:(id <IGDirectComposerProtocol>)arg1;
- (void)composerDidReachMaxTextLength:(id <IGDirectComposerProtocol>)arg1;
- (void)composer:(id <IGDirectComposerProtocol>)arg1 didChangeToText:(NSString *)arg2 mode:(IGDirectComposerMode *)arg3;
@end

