//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "IGDirectMessageViewModelProtocol.h"
#import "IGListDiffable.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class IGDirectMessageCellViewModel, IGDirectMessageMetadata, IGStyledString, NSString, NSURL;

@interface IGDirectCTALinkMessageViewModel : FBValueObject <IGDirectMessageViewModelProtocol, IGListDiffable, NSCopying, NSCoding>
{
    unsigned long long _type;
    NSURL *_url;
    IGStyledString *_styledMessageString;
    IGStyledString *_styledCTAString;
    IGDirectMessageMetadata *_messageMetadata;
    IGDirectMessageCellViewModel *_messageCellViewModel;
    NSString *_contentType;
}

+ (id)_titleTextForSenderUserName:(id)arg1 threadName:(id)arg2 isGroupThread:(_Bool)arg3 isSentByCurrentUser:(_Bool)arg4;
+ (id)viewModelWithMessage:(id)arg1 senderUsername:(id)arg2 cellViewModel:(id)arg3 threadName:(id)arg4;
@property(readonly, copy, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(readonly, copy, nonatomic) IGDirectMessageCellViewModel *messageCellViewModel; // @synthesize messageCellViewModel=_messageCellViewModel;
@property(readonly, copy, nonatomic) IGDirectMessageMetadata *messageMetadata; // @synthesize messageMetadata=_messageMetadata;
@property(readonly, copy, nonatomic) IGStyledString *styledCTAString; // @synthesize styledCTAString=_styledCTAString;
@property(readonly, copy, nonatomic) IGStyledString *styledMessageString; // @synthesize styledMessageString=_styledMessageString;
@property(readonly, copy, nonatomic) NSURL *url; // @synthesize url=_url;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (id)initWithType:(unsigned long long)arg1 url:(id)arg2 styledMessageString:(id)arg3 styledCTAString:(id)arg4 messageMetadata:(id)arg5 messageCellViewModel:(id)arg6 contentType:(id)arg7;
- (_Bool)_shouldShowCTAButton;
- (double)contentHeight;
- (struct CGSize)_iconSize;
- (double)width;
- (struct UIEdgeInsets)ctaInsets;
- (struct CGRect)ctaFrame;
- (struct CGRect)separatorFrame;
- (struct UIEdgeInsets)messageInsets;
- (struct CGRect)bannerFrame;
- (struct CGRect)iconFrame;
- (struct CGRect)messageFrame;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

