//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSFastEnumeration.h"

@class NSArray, NSDictionary, NSOrderedSet;

@interface IGDirectPublishedMessageSet : NSObject <NSFastEnumeration, NSCopying>
{
    NSArray *_sortedMessages;
    NSOrderedSet *_sortedLegacyMessages;
    NSDictionary *_messagesByServerId;
    NSDictionary *_messagesByClientContext;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (id)legacyMessagesOrderedSet;
- (id)reverseEnumerator;
- (unsigned long long)count;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (id)messageWithClientContext:(id)arg1;
- (id)messageWithServerId:(id)arg1;
- (id)oldestMessage;
- (id)newestMessage;
- (id)initWithSortedMessages:(id)arg1 sortedLegacyMessages:(id)arg2 messagesByServerId:(id)arg3 messagesByClientContext:(id)arg4;

@end

