//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDirectAnimatedMediaViewModel;

@protocol IGDirectAnimatedMediaSectionControllerDelegate <NSObject>
- (void)animatedMediaSectionController:(id <IGDirectAnimatedMediaSectionControllerProtocol>)arg1 didSelectAnimatedMedia:(IGDirectAnimatedMediaViewModel *)arg2;
@end

