//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@interface IGDirectRecipientListActionBarConfiguration : FBValueObject <NSCopying, NSCoding>
{
    _Bool _showAddToStory;
    _Bool _showReply;
    _Bool _showCopyLink;
    _Bool _showSystemShare;
    _Bool _showShareViaWhatsapp;
    _Bool _showShareViaLine;
    _Bool _showShareViaVK;
    _Bool _showShareViaiMessage;
    _Bool _showShareViaMessenger;
    _Bool _showShareViaSMS;
    _Bool _showShareViaEmail;
    _Bool _showShareViaTelegram;
}

+ (id)hashtagConfiguration;
+ (id)adsConfiguration;
+ (id)feedConfiguration;
@property(readonly, nonatomic) _Bool showShareViaTelegram; // @synthesize showShareViaTelegram=_showShareViaTelegram;
@property(readonly, nonatomic) _Bool showShareViaEmail; // @synthesize showShareViaEmail=_showShareViaEmail;
@property(readonly, nonatomic) _Bool showShareViaSMS; // @synthesize showShareViaSMS=_showShareViaSMS;
@property(readonly, nonatomic) _Bool showShareViaMessenger; // @synthesize showShareViaMessenger=_showShareViaMessenger;
@property(readonly, nonatomic) _Bool showShareViaiMessage; // @synthesize showShareViaiMessage=_showShareViaiMessage;
@property(readonly, nonatomic) _Bool showShareViaVK; // @synthesize showShareViaVK=_showShareViaVK;
@property(readonly, nonatomic) _Bool showShareViaLine; // @synthesize showShareViaLine=_showShareViaLine;
@property(readonly, nonatomic) _Bool showShareViaWhatsapp; // @synthesize showShareViaWhatsapp=_showShareViaWhatsapp;
@property(readonly, nonatomic) _Bool showSystemShare; // @synthesize showSystemShare=_showSystemShare;
@property(readonly, nonatomic) _Bool showCopyLink; // @synthesize showCopyLink=_showCopyLink;
@property(readonly, nonatomic) _Bool showReply; // @synthesize showReply=_showReply;
@property(readonly, nonatomic) _Bool showAddToStory; // @synthesize showAddToStory=_showAddToStory;
- (id)initWithShowAddToStory:(_Bool)arg1 showReply:(_Bool)arg2 showCopyLink:(_Bool)arg3 showSystemShare:(_Bool)arg4 showShareViaWhatsapp:(_Bool)arg5 showShareViaLine:(_Bool)arg6 showShareViaVK:(_Bool)arg7 showShareViaiMessage:(_Bool)arg8 showShareViaMessenger:(_Bool)arg9 showShareViaSMS:(_Bool)arg10 showShareViaEmail:(_Bool)arg11 showShareViaTelegram:(_Bool)arg12;

@end

