//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGWarmStartListener.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class IGDirectMainInboxAnalyticsLogger, NSArray, NSIndexPath, NSString, UITableView, UIView;

@interface IGDirectInboxFiltersViewController : UIViewController <IGWarmStartListener, UITableViewDataSource, UITableViewDelegate>
{
    id <IGDirectThreadsFilterControllerDelegate> _delegate;
    IGDirectMainInboxAnalyticsLogger *_analyticsLogger;
    UITableView *_tableView;
    UIView *_dimmedView;
    UIView *_searchBarSnapshotView;
    NSArray *_threadsFilters;
    long long _selectedThreadsFilter;
    NSIndexPath *_selectedIndexPath;
    NSString *_module;
    _Bool _isDisplayingSwitchFiltersTableView;
    _Bool _isAnimating;
}

- (void).cxx_destruct;
- (void)_dismiss;
- (void)_animationCompleteWithVisible:(_Bool)arg1;
- (struct CGRect)_switchFiltersTableFrameFromHeight:(double)arg1 visible:(_Bool)arg2;
- (void)_threadsFilterControllerSwitchToThreadsFilter:(long long)arg1;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)_filtersViewHeight;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)_filterCellForTableView:(id)arg1 threadsFilter:(id)arg2;
- (void)applicationWillEnterForegroundWithTimeIntervalSinceBackground:(double)arg1 warmStartInitializedFromNotification:(_Bool)arg2;
- (void)updateSelectedThreadsFilter:(long long)arg1 updateScreenContentOnCompletion:(_Bool)arg2;
- (long long)selectedThreadsFilter;
- (void)displaySwitchFiltersTableView:(_Bool)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)isPresented;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)_setupSearchBarSnapshotView;
- (void)_setupDimmedView;
- (void)_setupTableView;
- (id)initWithDelegate:(id)arg1 analyticsLogger:(id)arg2 selectedThreadsFilter:(long long)arg3 searchBarSnapshotView:(id)arg4 module:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

