//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGListSectionController.h"

#import "IGDiscoverPeopleCellDelegate.h"

@class IGFeaturedUserInfo, IGTableLayoutSpec, IGUserSession, NSString;

@interface IGDiscoverPeopleSectionController : IGListSectionController <IGDiscoverPeopleCellDelegate>
{
    NSString *_module;
    long long _firstCellStartPosition;
    IGFeaturedUserInfo *_featuredUserInfo;
    id <IGFollowPeopleLoggerProtocol> _logger;
    _Bool _showHideButton;
    IGUserSession *_userSession;
    _Bool _isOnActivityFeed;
    IGTableLayoutSpec *_tableInterface;
    _Bool _hasSocialContext;
    id <IGDiscoverPeopleSectionControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <IGDiscoverPeopleSectionControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_clickPointForModule:(id)arg1;
- (void)_friendStatusChanged:(id)arg1;
- (void)_performChangeFriendshipStatus:(id)arg1;
- (void)_showAlertForUnfollow:(id)arg1;
- (void)discoverPeopleCellDidTapProfileRing:(id)arg1;
- (void)discoverPeopleCellDidTapDismiss:(id)arg1;
- (void)discoverPeopleCellDidTapFollowing:(id)arg1;
- (void)discoverPeopleCellDidTapFollow:(id)arg1;
- (void)didSelectItemAtIndex:(long long)arg1;
- (void)didUpdateToObject:(id)arg1;
- (id)cellForItemAtIndex:(long long)arg1;
- (struct CGSize)sizeForItemAtIndex:(long long)arg1;
- (long long)numberOfItems;
- (void)setFirstCellStartPosition:(long long)arg1;
- (id)initWithHasSocialContext:(_Bool)arg1 userSession:(id)arg2 isOnActivityFeed:(_Bool)arg3 module:(id)arg4 tableInterface:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

