//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class IGDirectShareSheetOneTapButtonLayoutSpec, IGDirectShareSheetOneTapButtonState, IGDirectShareSheetOneTapButtonTextGrouping;

@interface IGDirectShareSheetOneTapButtonViewModel : FBValueObject <NSCopying, NSCoding>
{
    IGDirectShareSheetOneTapButtonTextGrouping *_texts;
    IGDirectShareSheetOneTapButtonTextGrouping *_accessibilityTexts;
    IGDirectShareSheetOneTapButtonLayoutSpec *_layoutSpec;
    IGDirectShareSheetOneTapButtonState *_state;
    double _width;
}

+ (id)newCustomButtonViewModelWithSendState:(id)arg1 titleTexts:(id)arg2 accessibilityTexts:(id)arg3 accessibilityTarget:(id)arg4 additionalWordsToAccommodate:(id)arg5;
+ (id)newCreateButtonViewModel;
+ (id)newInviteButtonViewModelWithSendState:(id)arg1 accessibilityTarget:(id)arg2 additionalWordsToAccommodate:(id)arg3;
+ (id)newSendButtonViewModelWithSendState:(id)arg1 accessibilityTarget:(id)arg2 additionalWordsToAccommodate:(id)arg3 recipientCount:(long long)arg4;
+ (id)newBorderlessSendButtonViewModelWithSendState:(id)arg1 accessibilityTarget:(id)arg2 additionalWordsToAccommodate:(id)arg3;
+ (id)newSendButtonViewModelWithSendState:(id)arg1 accessibilityTarget:(id)arg2 additionalWordsToAccommodate:(id)arg3;
+ (id)newShareButtonViewModelWithSendState:(id)arg1 accessibilityTarget:(id)arg2 additionalWordsToAccommodate:(id)arg3;
@property(readonly, nonatomic) double width; // @synthesize width=_width;
@property(readonly, copy, nonatomic) IGDirectShareSheetOneTapButtonState *state; // @synthesize state=_state;
@property(readonly, copy, nonatomic) IGDirectShareSheetOneTapButtonLayoutSpec *layoutSpec; // @synthesize layoutSpec=_layoutSpec;
@property(readonly, copy, nonatomic) IGDirectShareSheetOneTapButtonTextGrouping *accessibilityTexts; // @synthesize accessibilityTexts=_accessibilityTexts;
@property(readonly, copy, nonatomic) IGDirectShareSheetOneTapButtonTextGrouping *texts; // @synthesize texts=_texts;
- (void).cxx_destruct;
- (id)initWithTexts:(id)arg1 accessibilityTexts:(id)arg2 layoutSpec:(id)arg3 state:(id)arg4 width:(double)arg5;
- (id)_initWithTexts:(id)arg1 accessibilityTexts:(id)arg2 additionalWordsToAccommodate:(id)arg3 state:(id)arg4 borderless:(_Bool)arg5;

@end

