//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGDiscoveryNavigationTrayItem.h"
#import "IGListDiffable.h"
#import "NSCopying.h"

@class IGDiscoveryTopicMuteStatus, IGFeedItem, NSString;

@interface IGDiscoveryTopicModel : NSObject <IGDiscoveryNavigationTrayItem, IGListDiffable, NSCopying>
{
    NSString *_topicId;
    long long _type;
    NSString *_title;
    NSString *_displayTitle;
    IGFeedItem *_coverFeedItem;
    long long _rankedPosition;
    IGDiscoveryTopicMuteStatus *_muteStatus;
    NSString *_debugInfo;
}

@property(readonly, copy, nonatomic) NSString *debugInfo; // @synthesize debugInfo=_debugInfo;
@property(readonly, nonatomic) IGDiscoveryTopicMuteStatus *muteStatus; // @synthesize muteStatus=_muteStatus;
@property(readonly, nonatomic) long long rankedPosition; // @synthesize rankedPosition=_rankedPosition;
@property(readonly, nonatomic) IGFeedItem *coverFeedItem; // @synthesize coverFeedItem=_coverFeedItem;
@property(readonly, copy, nonatomic) NSString *displayTitle; // @synthesize displayTitle=_displayTitle;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;
@property(readonly, copy, nonatomic) NSString *topicId; // @synthesize topicId=_topicId;
- (void).cxx_destruct;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)initWithTopicId:(id)arg1 type:(long long)arg2 title:(id)arg3 displayTitle:(id)arg4 coverFeedItem:(id)arg5 rankedPosition:(long long)arg6 muteStatus:(id)arg7 debugInfo:(id)arg8;
- (_Bool)showsDropdownIndicator;
- (id)navigationTrayIcon;
- (id)navigationTrayTitle;

@end

