//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGDirectMessageModalSubtitleViewModel, IGSliderStickerAverageVoteView, UILabel;

@interface IGDirectMessageModalSubtitleView : UIView
{
    UILabel *_subtitleLabel;
    IGSliderStickerAverageVoteView *_sliderView;
    IGDirectMessageModalSubtitleViewModel *_subtitleViewModel;
}

@property(copy, nonatomic) IGDirectMessageModalSubtitleViewModel *subtitleViewModel; // @synthesize subtitleViewModel=_subtitleViewModel;
- (void).cxx_destruct;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

