//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIView<IGStoryViewerEntryView>, UIViewController;

@protocol IGDirectAvatarSelectionDelegate <NSObject>
- (void)didSelectAvatarForThreadId:(NSString *)arg1 viewController:(UIViewController *)arg2 sourceView:(UIView<IGStoryViewerEntryView> *)arg3;
@end

