//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGDiscoveryDestinationOverlayView.h"

@class IGDiscoveryVideoCellTitleView, IGGradientView, IGVideoGlyphView, NSString, UIImageView;

@interface IGDiscoveryVideoCellOverlayView : UIView <IGDiscoveryDestinationOverlayView>
{
    UIImageView *_backgroundView;
    IGDiscoveryVideoCellTitleView *_titleView;
    IGGradientView *_gradientView;
    long long _accessoryType;
    UIImageView *_igtvIconImageView;
    _Bool _shouldShowTitle;
    IGVideoGlyphView *_playIcon;
    long long _alignmentStyle;
}

@property(nonatomic) long long alignmentStyle; // @synthesize alignmentStyle=_alignmentStyle;
- (void).cxx_destruct;
- (void)handleDidPause;
- (void)handleDidBeginPlaying;
- (_Bool)isIGTVAccessoryType:(long long)arg1;
- (id)_activeAccessoryView;
- (void)layoutSubviews;
- (void)configureWithHeader:(id)arg1 title:(id)arg2 subtitle:(id)arg3 accessoryType:(long long)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

