//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDirectThreadViewTimestampAnimator, NSIndexPath, UICollectionViewCell;

@protocol IGDirectThreadViewTimestampAnimatorDelegate <NSObject>
- (void)timestampAnimatorDidBeginSliding:(IGDirectThreadViewTimestampAnimator *)arg1;
- (_Bool)timestampAnimator:(IGDirectThreadViewTimestampAnimator *)arg1 shouldSlideCell:(UICollectionViewCell *)arg2 atIndexPath:(NSIndexPath *)arg3;
@end

