//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGDiscoverySpotlightModel, IGDiscoverySpotlightSectionController;

@protocol IGDiscoverySpotlightSectionControllerDelegate <NSObject>
- (void)spotlightSectionController:(IGDiscoverySpotlightSectionController *)arg1 didTapSpotlight:(IGDiscoverySpotlightModel *)arg2;
@end

