//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGDrawBrushGLAbstract.h"

@class NSArray;

@interface IGDrawCompoundBrush : IGDrawBrushGLAbstract
{
    NSArray *_brushes;
}

@property(readonly, nonatomic) NSArray *brushes; // @synthesize brushes=_brushes;
- (void).cxx_destruct;
- (id)createMark;
- (void)prepareToDraw;
- (void)setBackingSize:(struct CGSize)arg1;
- (id)context;
- (id)initWithBrushes:(id)arg1;

@end

