//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGFeedScrollViewAnnouncer, UIScrollView;

@protocol IGDynamicPageChildViewControllerType <NSObject>
- (_Bool)canDynamicPageBeDismissedVertically;
- (void)prepareForReuse;
- (IGFeedScrollViewAnnouncer *)scrollViewAnnouncer;
- (UIScrollView *)scrollView;
- (void)willResignSelectedPageInDynamicPageViewController;
- (void)didBecomeSelectedPageInDynamicPageViewController;
@end

