//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGEasyReportingHelper : NSObject
{
    id _entityToReport;
    long long _type;
    id <IGEasyReportDelegate> _delegate;
}

+ (void)sponsoredStoryActionSheetDismissedWithButtonTitled:(id)arg1 hideCallback:(CDUnknownBlockType)arg2 inappropriateCallback:(CDUnknownBlockType)arg3;
+ (void)prepareSponsoredStoryReportingActionSheetWithOptions:(id)arg1;
+ (void)commentActionSheetDismissedWithButtonTitled:(id)arg1 spamCallback:(CDUnknownBlockType)arg2 abuseCallback:(CDUnknownBlockType)arg3 cancelCallback:(CDUnknownBlockType)arg4;
+ (void)prepareCommentEasyReportingActionSheet;
+ (void)defaultActionSheetDismissedWithButtonTitled:(id)arg1 spamCallback:(CDUnknownBlockType)arg2 inappropriateCallback:(CDUnknownBlockType)arg3 cancelCallback:(CDUnknownBlockType)arg4 fraudCallback:(CDUnknownBlockType)arg5;
+ (void)defaultActionSheetDismissedWithButtonTitled:(id)arg1 spamCallback:(CDUnknownBlockType)arg2 inappropriateCallback:(CDUnknownBlockType)arg3 cancelCallback:(CDUnknownBlockType)arg4;
+ (void)prepareEasyReportingActionSheetForFeedItem:(id)arg1;
+ (void)prepareEasyReportingActionSheetForUser:(id)arg1;
+ (void)prepareEasyReportingActionSheet;
- (void).cxx_destruct;
- (void)didDismissWithButtonTitle:(id)arg1;
- (id)initWithEntityToReport:(id)arg1 type:(long long)arg2 delegate:(id)arg3 isHackedAccountEnabled:(_Bool)arg4;

@end

