//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGLoadMoreResponseType.h"

@class IGEIAdsDataModel, IGEIPrimaryCountry, NSNumber, NSString;

@interface IGEIUserDetailsResponse : NSObject <IGLoadMoreResponseType>
{
    _Bool _hasFormerUsernames;
    _Bool _hasSharedFollowerAccounts;
    IGEIPrimaryCountry *_primaryCountry;
    NSNumber *_dateJoinedTimestamp;
    IGEIAdsDataModel *_adsData;
    NSString *_releaseDateString;
}

@property(readonly, copy, nonatomic) NSString *releaseDateString; // @synthesize releaseDateString=_releaseDateString;
@property(readonly, nonatomic) _Bool hasSharedFollowerAccounts; // @synthesize hasSharedFollowerAccounts=_hasSharedFollowerAccounts;
@property(readonly, nonatomic) _Bool hasFormerUsernames; // @synthesize hasFormerUsernames=_hasFormerUsernames;
@property(readonly, nonatomic) IGEIAdsDataModel *adsData; // @synthesize adsData=_adsData;
@property(readonly, nonatomic) NSNumber *dateJoinedTimestamp; // @synthesize dateJoinedTimestamp=_dateJoinedTimestamp;
@property(readonly, nonatomic) IGEIPrimaryCountry *primaryCountry; // @synthesize primaryCountry=_primaryCountry;
- (void).cxx_destruct;
- (id)maxId;
- (id)initWithPrimaryCountry:(id)arg1 dateJoinedTimestamp:(id)arg2 adsData:(id)arg3 hasFormerUsernames:(_Bool)arg4 hasSharedFollowerAccounts:(_Bool)arg5 releaseDateString:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

