//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class IGTextButton, UIImageView, UILabel;

@interface IGEIVisualHeaderTableViewCell : UITableViewCell
{
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    IGTextButton *_learnMoreButton;
    id <IGEIVisualHeaderTableViewCellDelegate> _delegate;
}

@property(nonatomic) __weak id <IGEIVisualHeaderTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_onLearnMoreButtonTapped:(id)arg1;
- (void)configureWithTitleText:(id)arg1 messageText:(id)arg2;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

