//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGExploreSeeLessTrackingManager : NSObject
{
}

+ (void)_reportUserDismissItem:(id)arg1 withEventType:(long long)arg2 networker:(id)arg3;
+ (void)_logHidingForItem:(id)arg1 withEventType:(long long)arg2 withSourceModule:(id)arg3 fromSource:(long long)arg4 extraInfo:(id)arg5 userSession:(id)arg6;
+ (void)trackHidingForItem:(id)arg1 withEventType:(long long)arg2 withSourceModule:(id)arg3 fromSource:(long long)arg4 extraInfo:(id)arg5 userSession:(id)arg6;

@end

