//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGTabPageViewController.h"

#import "IGKeyboardObserverShowDelegate.h"
#import "IGSearchChildViewControllerTypeDelegate.h"
#import "IGTabPageViewControllerDelegate.h"

@class IGExploreAutocompleteSearchHelper, IGKeyboardObserver, IGSearchAnalyticsLogger, IGSearchNavigationPerfComponents, IGSearchSession, IGUserSession, IGViewController<IGSearchChildViewControllerType>, NSDate, NSString, UIColor;

@interface IGExploreModernSearchViewController : IGTabPageViewController <IGSearchChildViewControllerTypeDelegate, IGTabPageViewControllerDelegate, IGKeyboardObserverShowDelegate>
{
    IGUserSession *_userSession;
    IGExploreAutocompleteSearchHelper *_searchHelper;
    IGViewController<IGSearchChildViewControllerType> *_topSearchViewController;
    IGViewController<IGSearchChildViewControllerType> *_userSearchViewController;
    IGViewController<IGSearchChildViewControllerType> *_hashtagSearchViewController;
    IGViewController<IGSearchChildViewControllerType> *_placesSearchViewController;
    NSString *_searchText;
    UIColor *_tabBackgroundColor;
    NSDate *_viewControllerPushedTime;
    _Bool _willMoveToParentVC;
    _Bool _viewHasAppeared;
    IGSearchNavigationPerfComponents *_navPerfComponents;
    IGKeyboardObserver *_keyboardObserver;
    id <IGSearchViewControllerTypeDelegate> _searchDelegate;
    NSString *_querySessionId;
    IGSearchAnalyticsLogger *_searchAnalyticsLogger;
    IGSearchSession *_searchSession;
}

+ (void)prefetchSuggestedResultsIfNeeded:(id)arg1;
@property(readonly, nonatomic) IGSearchSession *searchSession; // @synthesize searchSession=_searchSession;
@property(readonly, nonatomic) IGSearchAnalyticsLogger *searchAnalyticsLogger; // @synthesize searchAnalyticsLogger=_searchAnalyticsLogger;
@property(readonly, copy, nonatomic) NSString *querySessionId; // @synthesize querySessionId=_querySessionId;
@property(nonatomic) __weak id <IGSearchViewControllerTypeDelegate> searchDelegate; // @synthesize searchDelegate=_searchDelegate;
- (void).cxx_destruct;
- (void)keyboardObserverKeyboardDidShow:(id)arg1;
- (void)keyboardObserver:(id)arg1 keyboardWillShowWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(long long)arg5;
- (id)analyticsExtras;
- (id)analyticsModule;
- (id)_viewControllerForTabState:(long long)arg1;
- (void)_updateRecentHideItems;
- (void)pageViewController:(id)arg1 didPageToViewController:(id)arg2;
- (void)pageViewController:(id)arg1 willShowViewController:(id)arg2;
- (void)_searchDidEnd;
- (void)_searchDidStart;
- (void)updateActiveSearchText:(id)arg1;
- (void)searchChildViewControllerDidFailToLoadNullStateResults:(id)arg1 error:(id)arg2;
- (void)searchChildViewControllerDidLoadNullStateResults:(id)arg1;
- (void)searchChildViewControllerWillLoadNullStateResults:(id)arg1;
- (_Bool)isReadyForImpressionLogging;
- (void)searchChildViewControllerDidTapOnSearchResult:(id)arg1;
- (id)currentSearchText;
- (void)childViewControllerWillPushView:(id)arg1;
- (void)childViewController:(id)arg1 pushedTimeDidChange:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
@property(readonly, nonatomic) long long currentTabState;
- (struct UIEdgeInsets)preferredContentInsets;
- (_Bool)allowsNavigationGestureForGestureOrigin:(struct CGPoint)arg1;
- (_Bool)prefersNavigationBarHidden;
- (void)_renewSessionIfNeeded;
- (void)_onApplicationWillResignActiveNotification:(id)arg1;
- (void)_onApplicationWillEnterForegroundNotification:(id)arg1;
- (void)didMoveToParentViewController:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)_setCurrentTabState:(long long)arg1;
- (void)_initializeChildViewControllers;
- (id)initWithUserSession:(id)arg1 tabState:(long long)arg2 tabBackgroundColor:(id)arg3;

// Remaining properties
@property(retain, nonatomic) IGViewController<IGSearchChildViewControllerType> *currentViewController; // @dynamic currentViewController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

