//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGTabPageViewController.h"

#import "IGKeyboardObserverFrameChangeDelegate.h"
#import "IGKeyboardObserverShowDelegate.h"
#import "IGNavSearchBarDelegate.h"
#import "IGSearchChildViewControllerTypeDelegate.h"
#import "IGTabPageViewControllerDelegate.h"

@class IGExploreAutocompleteSearchHelper, IGKeyboardObserver, IGNavSearchBar, IGSearchAnalyticsLogger, IGSearchNavigationPerfComponents, IGSearchSession, IGUserSession, IGViewController<IGSearchChildViewControllerType>, NSDate, NSString, UIColor, UINavigationBar, UIView;

@interface IGExploreLegacySearchViewController : IGTabPageViewController <IGNavSearchBarDelegate, IGSearchChildViewControllerTypeDelegate, IGTabPageViewControllerDelegate, IGKeyboardObserverFrameChangeDelegate, IGKeyboardObserverShowDelegate>
{
    IGUserSession *_userSession;
    IGExploreAutocompleteSearchHelper *_searchHelper;
    IGKeyboardObserver *_keyboardObserver;
    IGViewController<IGSearchChildViewControllerType> *_topSearchViewController;
    IGViewController<IGSearchChildViewControllerType> *_userSearchViewController;
    IGViewController<IGSearchChildViewControllerType> *_hashtagSearchViewController;
    IGViewController<IGSearchChildViewControllerType> *_placesSearchViewController;
    UIView *_navigationContainerView;
    UIView *_navigationLineView;
    UINavigationBar *_navigationBar;
    NSDate *_viewControllerPushedTime;
    _Bool _willMoveToParentVC;
    _Bool _keyboardShownAtLeastOnce;
    IGSearchNavigationPerfComponents *_navPerfComponents;
    UIColor *_navigationBackgroundColor;
    _Bool _isActive;
    id <IGSearchViewControllerTypeDelegate> _searchDelegate;
    NSDate *_lastSearch;
    IGNavSearchBar *_searchBar;
    NSString *_querySessionId;
    IGSearchAnalyticsLogger *_searchAnalyticsLogger;
    IGSearchSession *_searchSession;
}

+ (void)prefetchSuggestedResultsIfNeeded:(id)arg1;
@property(readonly, nonatomic) IGSearchSession *searchSession; // @synthesize searchSession=_searchSession;
@property(readonly, nonatomic) IGSearchAnalyticsLogger *searchAnalyticsLogger; // @synthesize searchAnalyticsLogger=_searchAnalyticsLogger;
@property(readonly, copy, nonatomic) NSString *querySessionId; // @synthesize querySessionId=_querySessionId;
@property(readonly, nonatomic) IGNavSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(readonly, nonatomic) NSDate *lastSearch; // @synthesize lastSearch=_lastSearch;
@property(readonly, nonatomic) _Bool isActive; // @synthesize isActive=_isActive;
@property(nonatomic) __weak id <IGSearchViewControllerTypeDelegate> searchDelegate; // @synthesize searchDelegate=_searchDelegate;
- (void).cxx_destruct;
- (id)analyticsExtras;
- (id)analyticsModule;
- (void)keyboardObserverKeyboardDidShow:(id)arg1;
- (void)keyboardObserver:(id)arg1 keyboardWillShowWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(long long)arg5;
- (void)keyboardObserver:(id)arg1 keyboardFrameDidChangeWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(long long)arg5;
- (void)keyboardObserver:(id)arg1 keyboardFrameWillChangeWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(long long)arg5;
- (void)_resetNavElementStyleDefaults;
- (void)_updateSearchbarPlaceholderForController:(id)arg1;
@property(readonly, copy, nonatomic) NSString *searchText;
- (void)_updateRecentHideItems;
- (id)navigationBottomLineView;
- (id)navigationView;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarReturnKeyTapped:(id)arg1;
- (void)searchBarWillEndEditing:(id)arg1;
- (void)searchBarWillBeginEditing:(id)arg1;
- (void)searchBarCancelButtonTapped:(id)arg1;
- (void)pageViewController:(id)arg1 didPageToViewController:(id)arg2;
- (void)pageViewController:(id)arg1 willShowViewController:(id)arg2;
- (void)_searchDidEnd;
- (void)_searchDidStart;
- (void)willPresentSearchViewController;
- (void)_onSearchWillBecomeInactive;
- (void)_onSearchWillBecomeActive;
- (void)searchChildViewControllerDidFailToLoadNullStateResults:(id)arg1 error:(id)arg2;
- (void)searchChildViewControllerDidLoadNullStateResults:(id)arg1;
- (void)searchChildViewControllerWillLoadNullStateResults:(id)arg1;
- (_Bool)isReadyForImpressionLogging;
- (void)searchChildViewControllerDidTapOnSearchResult:(id)arg1;
- (id)currentSearchText;
- (void)childViewControllerWillPushView:(id)arg1;
- (void)childViewController:(id)arg1 pushedTimeDidChange:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)allowsNavigationGestureForGestureOrigin:(struct CGPoint)arg1;
- (struct UIEdgeInsets)preferredContentInsets;
- (_Bool)prefersNavigationBarHidden;
- (long long)preferredStatusBarStyle;
- (void)_renewSessionIfNeeded;
- (void)_onApplicationWillResignActiveNotification:(id)arg1;
- (void)_onApplicationWillEnterForegroundNotification:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)didMoveToParentViewController:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)_initializeChildViewControllers;
- (void)dealloc;
- (id)initWithUserSession:(id)arg1 showDiscoverButtonBeforeAnimation:(_Bool)arg2 showScanButtonBeforeAnimation:(_Bool)arg3 navigationBackgroundColor:(id)arg4;

// Remaining properties
@property(retain, nonatomic) IGViewController<IGSearchChildViewControllerType> *currentViewController; // @dynamic currentViewController;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

