//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGExponentMovingAverageCalculator : NSObject
{
    struct vector<double, std::__1::allocator<double>> _values;
    double _exponentDegree;
    unsigned long long _nextIndex;
    unsigned long long _capacity;
    unsigned long long _countOfValuesAdded;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (double)currentAverage;
- (void)addNewPoint:(double)arg1;
- (id)initWithCapacity:(unsigned long long)arg1 movingAverageDegree:(double)arg2;

@end

