//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol IGFeedSidecarIndicatorViewProtocol <NSObject>
- (void)cleanUpAnimationTimer;
- (void)animateShowAndHideForSwipeCompletion:(void (^)(void))arg1;
- (void)animateShowAndHideCompletion:(void (^)(void))arg1;
- (void)setCurrentItem:(long long)arg1;
- (void)setItemCount:(long long)arg1;
@end

