//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGFeedItemRealtimeSubscriptionService;

@protocol IGFeedItemRealTimeUpdateListener
- (void)feedItemRealTimeServiceDidUpdateVideoViewCount:(IGFeedItemRealtimeSubscriptionService *)arg1;
- (void)feedItemRealTimeServiceDidUpdateComment:(IGFeedItemRealtimeSubscriptionService *)arg1;
- (void)feedItemRealTimeServiceDidUpdateLike:(IGFeedItemRealtimeSubscriptionService *)arg1;
@end

