//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "IGActivationChainingControlDisplayable.h"
#import "IGFeedItemMediaDiscoverableCell.h"
#import "IGFeedVideoCell.h"
#import "IGHeartAnimatable.h"
#import "IGPageCellIndicatorControllerDelegate.h"
#import "IGPageMediaViewDelegate.h"
#import "IGSaveToCollectionsUpsellable.h"
#import "IGVideoPlaybackCellWithDelayedAudioLabel.h"
#import "IGZoomControllerZoomingDelegate.h"

@class IGActivationChainingControl, IGFeedItem, IGFeedItemPageCellState, IGFeedItemPageRedesignIndicator, IGFeedSidecarIndicatorView, IGMediaOverlayIndicator, IGObjectRecyclingPotentialLogger, IGPageCellIndicatorController, IGPageMediaTracker, IGPageMediaView, IGUserDefaults, NSString, UITapGestureRecognizer, UIView<IGFeedSidecarIndicatorViewProtocol>;

@interface IGFeedItemPageCell : UICollectionViewCell <IGPageMediaViewDelegate, IGPageCellIndicatorControllerDelegate, IGHeartAnimatable, IGFeedVideoCell, IGZoomControllerZoomingDelegate, IGSaveToCollectionsUpsellable, IGFeedItemMediaDiscoverableCell, IGVideoPlaybackCellWithDelayedAudioLabel, IGActivationChainingControlDisplayable>
{
    IGFeedSidecarIndicatorView *_legacySidecarIndicatorView;
    UITapGestureRecognizer *_sidecarIndicatorViewTapGestureRecognizer;
    _Bool _useRedesignPageControl;
    IGFeedItemPageRedesignIndicator *_redesignPageControl;
    IGUserDefaults *_sessionUserDefaults;
    id <IGFeedItemWithCarouselLoggingProviderDelegate> _loggingDelegate;
    _Bool _optimizationEnabled;
    IGObjectRecyclingPotentialLogger *_recycleLogger;
    _Bool _supportVideoStitching;
    _Bool _hasShownSaveToCollectionUpsell;
    _Bool _persistentOverlayIndicators;
    _Bool _showedSidecarIcon;
    IGActivationChainingControl *_chainingControl;
    IGFeedItem *_feedItem;
    IGFeedItemPageCellState *_pageCellState;
    double _percentVisible;
    id <IGFeedItemPageCellDelegate> _delegate;
    id <IGFeedVideoCellInteractionDelegate> _interactionDelegate;
    id <IGZoomControllerZoomingDelegate> _zoomingDelegate;
    id <IGFeedVideoCellPlayerDelegate> _playerDelegate;
    id <IGObjectInTagDisplayDelegate> _tagViewDelegate;
    long long _indicatorAnimationStyle;
    IGMediaOverlayIndicator *_indicatorView;
    IGPageMediaView *_pageMediaView;
    IGPageCellIndicatorController *_indicatorController;
    UIView<IGFeedSidecarIndicatorViewProtocol> *_sidecarIndicatorView;
    IGPageMediaTracker *_pageMediaTracker;
}

@property(retain, nonatomic) IGPageMediaTracker *pageMediaTracker; // @synthesize pageMediaTracker=_pageMediaTracker;
@property(nonatomic) _Bool showedSidecarIcon; // @synthesize showedSidecarIcon=_showedSidecarIcon;
@property(retain, nonatomic) UIView<IGFeedSidecarIndicatorViewProtocol> *sidecarIndicatorView; // @synthesize sidecarIndicatorView=_sidecarIndicatorView;
@property(readonly, nonatomic) IGPageCellIndicatorController *indicatorController; // @synthesize indicatorController=_indicatorController;
@property(retain, nonatomic) IGPageMediaView *pageMediaView; // @synthesize pageMediaView=_pageMediaView;
@property(retain, nonatomic) IGMediaOverlayIndicator *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(nonatomic) _Bool persistentOverlayIndicators; // @synthesize persistentOverlayIndicators=_persistentOverlayIndicators;
@property(nonatomic) long long indicatorAnimationStyle; // @synthesize indicatorAnimationStyle=_indicatorAnimationStyle;
@property(nonatomic) __weak id <IGObjectInTagDisplayDelegate> tagViewDelegate; // @synthesize tagViewDelegate=_tagViewDelegate;
@property(nonatomic) __weak id <IGFeedVideoCellPlayerDelegate> playerDelegate; // @synthesize playerDelegate=_playerDelegate;
@property(nonatomic) __weak id <IGZoomControllerZoomingDelegate> zoomingDelegate; // @synthesize zoomingDelegate=_zoomingDelegate;
@property(nonatomic) __weak id <IGFeedVideoCellInteractionDelegate> interactionDelegate; // @synthesize interactionDelegate=_interactionDelegate;
@property(nonatomic) __weak id <IGFeedItemPageCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double percentVisible; // @synthesize percentVisible=_percentVisible;
@property(retain, nonatomic) IGFeedItemPageCellState *pageCellState; // @synthesize pageCellState=_pageCellState;
@property(readonly, nonatomic) IGFeedItem *feedItem; // @synthesize feedItem=_feedItem;
@property(retain, nonatomic) IGActivationChainingControl *chainingControl; // @synthesize chainingControl=_chainingControl;
@property(nonatomic) _Bool hasShownSaveToCollectionUpsell; // @synthesize hasShownSaveToCollectionUpsell=_hasShownSaveToCollectionUpsell;
- (void).cxx_destruct;
- (_Bool)_isRedesignPageControlVisible;
- (void)_hideVideoIndicatorsForCurrentVideoView:(_Bool)arg1;
- (void)_requestVideoPlayback;
- (void)_scrollToNextPageWithAnimation;
- (void)_didTapIndicatorView:(id)arg1;
- (_Bool)isShowingSwipeNUX;
- (void)zoomControllerDetectedZoom:(id)arg1 withGestureRecognizer:(id)arg2;
- (void)pageMediaViewDidTapOverlayIndicator:(id)arg1;
- (void)pageMediaViewVideoIGTVKeepWatchingTapped:(id)arg1;
- (void)pageMediaViewVideoIGTVIndicatorTapped:(id)arg1;
- (void)pageMediaViewVideoTagsTapped:(id)arg1;
- (void)pageMediaView:(id)arg1 didShowPhotoTagsWithReason:(unsigned long long)arg2;
- (void)pageMediaView:(id)arg1 didTapWatchAndMoreButtonWithType:(unsigned long long)arg2;
- (void)pageMediaView:(id)arg1 didToggleVideoAudio:(_Bool)arg2;
- (void)pageMediaView:(id)arg1 itemDidEndViewing:(id)arg2;
- (void)pageMediaView:(id)arg1 itemDidStartViewing:(id)arg2;
- (void)pageMediaView:(id)arg1 itemDidDisappear:(id)arg2;
- (void)pageMediaView:(id)arg1 itemDidAppear:(id)arg2;
- (void)pageMediaView:(id)arg1 scrollingToPageIndex:(long long)arg2 fromIndex:(long long)arg3 percentageComplete:(double)arg4;
- (void)pageMediaViewDidScroll:(id)arg1;
- (void)pageMediaViewDidBeginTouch:(id)arg1;
- (void)pageMediaViewDidTapSaveToCollection:(id)arg1;
- (void)pageMediaViewDidSingleTap:(id)arg1;
- (void)pageMediaViewDidDoubleTap:(id)arg1;
- (void)pageMediaViewCurrentPhotoCellDidLoadImage:(id)arg1;
- (void)pageMediaViewCurrentVideoCellDidLoadImage:(id)arg1;
- (void)pageMediaViewDidInitialSingleTap:(id)arg1;
- (void)pageMediaViewWillDisplayOverlay:(id)arg1;
- (void)pageMediaView:(id)arg1 didScrollToPageIndex:(long long)arg2 fromIndex:(long long)arg3;
- (void)pageMediaView:(id)arg1 willScrollToPageIndex:(long long)arg2 fromIndex:(long long)arg3;
- (void)pageCellIndicatorControllerDidShowNUX:(id)arg1;
- (id)mediaCellFeedItem;
- (id)contentViewForHeartAnimation;
- (void)bounceNextPage;
- (void)peekCarouselIndicator;
- (void)handleDidRequestPlayback;
- (void)handleDidEndPlaying;
- (void)handleDidPause;
- (void)handleDidBeginPlaying;
- (id)videoView;
- (_Bool)supportsMediaCollections;
- (_Bool)supportsVideoStitching;
- (_Bool)supportsWatchAndMore;
- (_Bool)isSponsored;
- (unsigned long long)updatePercentVisible:(double)arg1;
- (void)configureCellWithFeedItem:(id)arg1 userSession:(id)arg2 module:(id)arg3 indicatorAnimationStyle:(long long)arg4 useRedesignPageControl:(_Bool)arg5 loggingDelegate:(id)arg6 interactionOptions:(CDStruct_8ab98ee7)arg7 videoOptions:(CDStruct_7071a04e)arg8 surfaceSupportCarouselViewInfo:(_Bool)arg9 supportSponsoredTracking:(_Bool)arg10 supportVideoStitching:(_Bool)arg11;
- (void)prepareForReuse;
- (id)thumbnailImage;
- (id)photoViewAtIndex:(long long)arg1;
- (id)currentPhotoView;
- (long long)getCurrentPage;
- (void)layoutSubviews;
- (void)toggleWatchAndMoreButtonWithType:(unsigned long long)arg1;
- (void)showSaveToCollectionUpsell;
- (void)showSwipeCarouselNUXIfNecessary;
- (void)peekTagsIndicator;
- (void)_showRedesignPageControlNUXIfNeeded;
- (void)_showIndicatorTooltipViewIfNeeded;
- (void)showAndHideSidecarIndicatorViewAfterCarouselBumping;
- (void)updatePageMediaViewItemsWithUserSession:(id)arg1;
- (void)scrollToPage:(long long)arg1 animated:(_Bool)arg2;
- (void)showNUXIfNeededWithPercentVisible:(double)arg1;
- (void)_showRedesignPageControl:(_Bool)arg1;
- (void)_showPersistentIndicatorView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

