//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGFeedItemPhotoCell.h"

@class UIButton, UILabel, UIView;

@interface IGFeedItemAd4AdCell : IGFeedItemPhotoCell
{
    UIView *_transparentOverlayView;
    UIView *_textContainerView;
    UILabel *_titleLabel;
    UILabel *_footerLabel;
    UIButton *_promoteButton;
    UIButton *_hideButton;
    id <IGFeedItemAd4AdCellDelegate> _delegate;
}

@property(nonatomic) __weak id <IGFeedItemAd4AdCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_promoteButtonClick:(id)arg1;
- (void)_onMoreButtonTapped:(id)arg1;
- (void)setAlphaWithOverlayProgress:(double)arg1 contentProgress:(double)arg2;
- (void)configureCellWithTitleText:(id)arg1 footerText:(id)arg2 promoteButtonText:(id)arg3;
- (void)_configurePromoteButtonWithTitle:(id)arg1;
- (void)_setTextWithLabel:(id)arg1 text:(id)arg2 lineHeight:(float)arg3;
- (void)layoutSubviews;
- (void)_setupLayout;
- (id)_initializePromoteButton;
- (id)_initializeLabel;
- (id)initWithFrame:(struct CGRect)arg1;

@end

