//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGFeedItem, IGPhoto, IGPhotoTagIndicatorConfiguration, IGUser, NSString, UIImage;

@interface IGFeedItemPhotoCellConfiguration : NSObject
{
    _Bool _isForMLEXPreview;
    IGPhoto *_photo;
    IGFeedItem *_feedItem;
    UIImage *_localImage;
    IGPhotoTagIndicatorConfiguration *_indicatorConfiguration;
    IGUser *_user;
    NSString *_analyticsModule;
}

@property(readonly, copy, nonatomic) NSString *analyticsModule; // @synthesize analyticsModule=_analyticsModule;
@property(readonly, nonatomic) IGUser *user; // @synthesize user=_user;
@property(readonly, nonatomic) IGPhotoTagIndicatorConfiguration *indicatorConfiguration; // @synthesize indicatorConfiguration=_indicatorConfiguration;
@property(readonly, nonatomic) _Bool isForMLEXPreview; // @synthesize isForMLEXPreview=_isForMLEXPreview;
@property(readonly, nonatomic) UIImage *localImage; // @synthesize localImage=_localImage;
@property(readonly, nonatomic) IGFeedItem *feedItem; // @synthesize feedItem=_feedItem;
@property(readonly, nonatomic) IGPhoto *photo; // @synthesize photo=_photo;
- (void).cxx_destruct;
- (id)initWithPhoto:(id)arg1 feedItem:(id)arg2 localImage:(id)arg3 indicatorConfiguration:(id)arg4 isForMLEXPreview:(_Bool)arg5 user:(id)arg6 analyticsModule:(id)arg7;

@end

