//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGFeedMediaView.h"

#import "IGImageProgressViewDelegate.h"
#import "IGMediaOverlayDelegate.h"
#import "IGTagHintDisplayViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class IGDebuggingMediaLinesView, IGImageProgressView, IGMediaOverlayIndicator, IGObjectInTagDisplayView, IGPhotoTagIndicatorConfiguration, IGShoppingConsumptionFeedItemLogger, IGShoppingShelfDotDisplayView, IGTagHintDisplayView, IGUser, NSArray, NSString, NSURL, UIImage, UIImageView, UITapGestureRecognizer;

@interface IGFeedPhotoView : IGFeedMediaView <IGImageProgressViewDelegate, UIGestureRecognizerDelegate, IGMediaOverlayDelegate, IGTagHintDisplayViewDelegate>
{
    IGDebuggingMediaLinesView *_debuggingMediaLinesView;
    NSString *_module;
    id <IGFeedTagsProvider> _tagsProvider;
    IGPhotoTagIndicatorConfiguration *_indicatorConfiguration;
    IGShoppingConsumptionFeedItemLogger *_impressionLogger;
    _Bool _wereTagsShown;
    _Bool _isShowingTags;
    _Bool _showsTagsOnTap;
    _Bool _persistentOverlayIndicator;
    _Bool _interactiveTagHints;
    _Bool _isPeekingTagDots;
    _Bool _isImageAccessibilityElement;
    _Bool _showUnifiedTagIndicator;
    _Bool _isTestClass;
    IGImageProgressView *_photoImageView;
    NSArray *_tagGroups;
    IGUser *_currentUser;
    NSURL *_imageURL;
    UIImage *_preloadedImage;
    IGMediaOverlayIndicator *_indicator;
    IGObjectInTagDisplayView *_inTagView;
    IGShoppingShelfDotDisplayView *_shoppingShelfDotDisplayView;
    id <IGFeedPhotoViewDelegate> _delegate;
    UITapGestureRecognizer *_doubleTapRecognizer;
    UITapGestureRecognizer *_singleTapRecognizer;
    UIImageView *_hiddenIcon;
    IGTagHintDisplayView *_tagHintDisplayView;
}

@property(readonly, nonatomic) IGTagHintDisplayView *tagHintDisplayView; // @synthesize tagHintDisplayView=_tagHintDisplayView;
@property(readonly, nonatomic) UIImageView *hiddenIcon; // @synthesize hiddenIcon=_hiddenIcon;
@property(readonly, nonatomic) UITapGestureRecognizer *singleTapRecognizer; // @synthesize singleTapRecognizer=_singleTapRecognizer;
@property(readonly, nonatomic) UITapGestureRecognizer *doubleTapRecognizer; // @synthesize doubleTapRecognizer=_doubleTapRecognizer;
@property(nonatomic) __weak id <IGFeedPhotoViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) IGShoppingShelfDotDisplayView *shoppingShelfDotDisplayView; // @synthesize shoppingShelfDotDisplayView=_shoppingShelfDotDisplayView;
@property(readonly, nonatomic) IGObjectInTagDisplayView *inTagView; // @synthesize inTagView=_inTagView;
@property(nonatomic) _Bool isTestClass; // @synthesize isTestClass=_isTestClass;
@property(nonatomic) _Bool showUnifiedTagIndicator; // @synthesize showUnifiedTagIndicator=_showUnifiedTagIndicator;
@property(nonatomic) _Bool isImageAccessibilityElement; // @synthesize isImageAccessibilityElement=_isImageAccessibilityElement;
@property(readonly, nonatomic) _Bool isPeekingTagDots; // @synthesize isPeekingTagDots=_isPeekingTagDots;
@property(nonatomic) _Bool interactiveTagHints; // @synthesize interactiveTagHints=_interactiveTagHints;
@property(nonatomic) _Bool persistentOverlayIndicator; // @synthesize persistentOverlayIndicator=_persistentOverlayIndicator;
@property(nonatomic) _Bool showsTagsOnTap; // @synthesize showsTagsOnTap=_showsTagsOnTap;
@property(readonly, nonatomic) _Bool isShowingTags; // @synthesize isShowingTags=_isShowingTags;
@property(readonly, nonatomic) IGMediaOverlayIndicator *indicator; // @synthesize indicator=_indicator;
@property(retain, nonatomic) UIImage *preloadedImage; // @synthesize preloadedImage=_preloadedImage;
@property(readonly, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(retain, nonatomic) IGUser *currentUser; // @synthesize currentUser=_currentUser;
- (id)photoImageView;
- (void).cxx_destruct;
- (void)_shouldTrackImpressionsForOverlayIndicator:(_Bool)arg1;
- (void)tagHintDisplayViewTagTapped:(id)arg1;
- (void)mediaOverlayIndicator:(id)arg1 didChangeToState:(unsigned long long)arg2;
- (void)mediaOverlayTapped:(id)arg1;
- (void)cleanUpShoppingShelfDotDisplayView;
- (void)showShoppingShelfDot:(_Bool)arg1;
- (void)_onTagGroupWasEdited:(id)arg1;
- (void)progressImageView:(id)arg1 didFailLoadWithError:(id)arg2 networkRequestSummary:(id)arg3;
- (void)progressImageView:(id)arg1 didLoadImage:(id)arg2 loadSource:(id)arg3 networkRequestSummary:(id)arg4;
- (void)progressImageView:(id)arg1 didLoadPreviewImage:(id)arg2 progressiveJPEGScanNumber:(id)arg3;
- (void)_debuggingLinesDisplay;
- (void)_hideTagHintDotsAnimated:(_Bool)arg1 style:(long long)arg2;
- (void)_fadeTagHintDotsWithStyleNumber:(id)arg1;
- (void)clearTagHintDots;
- (void)peekTagHintDotsWithStyle:(long long)arg1 delayInSeconds:(double)arg2;
@property(readonly, nonatomic) _Bool imageViewIsFinishedLoading;
- (void)showTags:(_Bool)arg1 animated:(_Bool)arg2 tagShowReason:(unsigned long long)arg3;
- (_Bool)_shouldShowTagsIndicatorFromShowingTags:(_Bool)arg1;
- (void)showTagsIndicator:(_Bool)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) NSArray *tagGroups; // @synthesize tagGroups=_tagGroups;
- (id)productTags;
- (_Bool)hasUserTags;
- (_Bool)hasHashtagTags;
- (_Bool)hasProductTags;
- (_Bool)hasTags;
- (void)_updateSingleTapRecognizer;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)_onDoubleTap:(id)arg1;
- (void)_onTap:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)setTagViewDelegate:(id)arg1;
- (void)setImageURL:(id)arg1 module:(id)arg2;
- (void)setModule:(id)arg1;
- (void)_configureTagIndicator;
- (void)configureOverlayAndIndicatorWithTagGroups:(id)arg1 tagsProvider:(id)arg2 indicatorConfiguration:(id)arg3;
- (void)_showTagView:(_Bool)arg1 animated:(_Bool)arg2 tagShowReason:(unsigned long long)arg3;
- (void)_hideAllOverlaysAnimated:(_Bool)arg1;
@property(readonly, copy) NSString *description;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

