//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIImageView;

@interface IGGalleryStickerCell : UICollectionViewCell
{
    UIImageView *_dynamicGalleryIconImageView;
    UIImageView *_smallGalleryIconImageView;
    struct CGSize _dynamicIconSize;
}

- (void).cxx_destruct;
- (id)accessibilityLabel;
- (void)configureWithModel:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

