//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGGDPRConsentContext, IGGDPRConsentDataSource, IGUserSession;

@interface IGGDPRConsentNavigationPresenter : NSObject
{
    IGUserSession *_userSession;
    IGGDPRConsentContext *_consentContext;
    id <IGAPIClient> _networker;
    _Bool _isPresentedParentalConsent;
    IGGDPRConsentDataSource *_consentDataSource;
    id <IGGDPRConsentNavigationPresenterDelegate> _delegate;
}

+ (void)showBlockingViewWithUserSession:(id)arg1 dataDict:(id)arg2 hostViewController:(id)arg3;
+ (id)entryPointFromParams:(id)arg1;
@property(nonatomic) __weak id <IGGDPRConsentNavigationPresenterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_showActivityIndicatorInViewController:(id)arg1;
- (void)presentLeaveConfirmationDialogWithHostViewController:(id)arg1 keepReviewBlock:(CDUnknownBlockType)arg2 leaveReviewBlock:(CDUnknownBlockType)arg3;
- (void)updateUserSession:(id)arg1;
- (void)presentParentalConsentViewWithHostViewController:(id)arg1 animated:(_Bool)arg2;
- (void)presentConsentViewWithData:(id)arg1 withHostViewController:(id)arg2 animated:(_Bool)arg3;
- (void)initConsentViewWithHostViewController:(id)arg1;
- (id)initWithUserSession:(id)arg1 consentContext:(id)arg2 networker:(id)arg3;

@end

