//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGGLKShader, NSMutableDictionary, NSObject<OS_dispatch_semaphore>;

@interface IGGLKProgram : NSObject
{
    unsigned int _handle;
    IGGLKShader *_vertexShader;
    IGGLKShader *_fragmentShader;
    NSMutableDictionary *_attributeToLocationDict;
    NSMutableDictionary *_uniformToLocationDict;
    NSObject<OS_dispatch_semaphore> *_compileSemaphore;
}

- (void).cxx_destruct;
- (void)_compile;
- (_Bool)_isValid;
- (_Bool)use;
- (int)locationForUniform:(id)arg1;
- (int)locationForAttribute:(id)arg1;
- (_Bool)validate;
- (void)dealloc;
- (id)initWithVertexShader:(id)arg1 fragmentShader:(id)arg2;

@end

