//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGGLKNode.h"

@class IGGLKTextureRenderer, UIImage;

@interface IGGLKImageNode : IGGLKNode
{
    IGGLKTextureRenderer *_textureRenderer;
    UIImage *_image;
    long long _contentMode;
}

@property(nonatomic) long long contentMode; // @synthesize contentMode=_contentMode;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (void)_updateTextureBounds;
- (void)draw;
- (void)modelViewProjectionMatrixDidUpdate;
- (void)layoutChildren;
- (id)initWithFrame:(struct CGRect)arg1;

@end

