//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGFeedScrollViewListener.h"
#import "IGFollowListSectionControllerLoggingDelegate.h"
#import "IGListAdapterDataSource.h"
#import "IGListAdapterDelegate.h"
#import "IGNavSearchBarDelegate.h"
#import "IGNetworkSourceDelegate.h"
#import "IGUserActionsListener.h"
#import "UICollectionViewDelegate.h"

@class IGFeedScrollViewAnnouncer, IGHashtagFollowListLogger, IGListAdapter, IGNavSearchBar, IGNavSearchBarItemConfiguration, IGNetworkSource, IGRefreshControl, IGUserSession, NSArray, NSString, UICollectionView;

@interface IGHashtagFollowListViewController : IGViewController <IGFeedScrollViewListener, IGFollowListSectionControllerLoggingDelegate, IGListAdapterDataSource, IGListAdapterDelegate, IGNavSearchBarDelegate, IGNetworkSourceDelegate, IGUserActionsListener, UICollectionViewDelegate>
{
    NSString *_contextPK;
    NSString *_contextUsername;
    NSString *_sourceAnalyticsModule;
    IGUserSession *_userSession;
    double _headerHeight;
    _Bool _isCurrentUser;
    _Bool _isLoading;
    UICollectionView *_collectionView;
    IGListAdapter *_listAdapter;
    IGFeedScrollViewAnnouncer *_scrollViewAnnouncer;
    IGRefreshControl *_refreshControl;
    IGNetworkSource *_hashtagsDataSource;
    IGNetworkSource *_hashtagSuggestionDataSource;
    NSArray *_hashtags;
    NSArray *_suggestedHashtags;
    NSString *_searchString;
    NSArray *_filteredHashtags;
    NSArray *_filteredSuggestedHashtags;
    IGNavSearchBarItemConfiguration *_searchBarItemConfig;
    IGNavSearchBar *_searchBar;
    IGHashtagFollowListLogger *_hashtagLogger;
}

- (void).cxx_destruct;
- (struct UIEdgeInsets)preferredContentInsets;
- (id)analyticsModule;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewWillScrollNearTop:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndScrolling:(id)arg1;
- (void)scrollViewWillScrollNearBottom:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (id)_loggingExtrasForViewModel:(id)arg1;
- (void)logFollowListSectionController:(id)arg1 follow:(_Bool)arg2 followListItemViewModel:(id)arg3;
- (void)logFollowListSectionController:(id)arg1 didTapFollowListItemViewModel:(id)arg2;
- (void)didChangePrivacyFollowingAcceptRateLimit;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarWillBeginEditing:(id)arg1;
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)_fetchData;
- (void)_handleHashtagResponseFollowStatus:(id)arg1;
- (void)_reloadData;
- (void)networkSource:(id)arg1 didFailWithError:(id)arg2;
- (void)networkSource:(id)arg1 didFetchMoreWithObject:(id)arg2;
- (void)networkSource:(id)arg1 didFetchObject:(id)arg2;
- (id)networkSource:(id)arg1 requestWithMaxID:(id)arg2;
- (void)listAdapter:(id)arg1 didEndDisplayingObject:(id)arg2 atIndex:(long long)arg3;
- (void)listAdapter:(id)arg1 willDisplayObject:(id)arg2 atIndex:(long long)arg3;
- (id)emptyViewForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)objectsForListAdapter:(id)arg1;
- (void)viewDidLoad;
- (id)initWithContextPK:(id)arg1 contextUsername:(id)arg2 sourceAnalyticsModule:(id)arg3 userSession:(id)arg4 headerHeight:(double)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

