//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBGeneratedIntentTarget.h"

@class IGFollowAttributionModel, IGHashtagModel, IGUserSession;

@interface IGHashtagFeedIntentTarget : FBGeneratedIntentTarget
{
    IGHashtagModel *_hashtag;
    IGUserSession *_session;
    IGFollowAttributionModel *_followAttributionModel;
}

@property(readonly, nonatomic) IGFollowAttributionModel *followAttributionModel; // @synthesize followAttributionModel=_followAttributionModel;
@property(readonly, nonatomic) IGUserSession *session; // @synthesize session=_session;
@property(readonly, nonatomic) IGHashtagModel *hashtag; // @synthesize hashtag=_hashtag;
- (void).cxx_destruct;
- (id)initWithHashtag:(id)arg1 session:(id)arg2 followAttributionModel:(id)arg3;

@end

