//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGFeedItem, UIViewController<IGHighlightsMultiSelectController>;

@protocol IGHighlightsMultiSelectControllerDelegate
- (void)highlightsMultiSelectVC:(UIViewController<IGHighlightsMultiSelectController> *)arg1 didDeselectFeedItem:(IGFeedItem *)arg2;
- (void)highlightsMultiSelectVC:(UIViewController<IGHighlightsMultiSelectController> *)arg1 didSelectFeedItem:(IGFeedItem *)arg2;
@end

