//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class IGHScrollCollectionViewLayout, UICollectionView;

@interface IGHScrollBusinessConversionNetegoCell : UICollectionViewCell
{
    UICollectionView *_collectionView;
    IGHScrollCollectionViewLayout *_layout;
}

@property(retain, nonatomic) IGHScrollCollectionViewLayout *layout; // @synthesize layout=_layout;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (double)currentContentOffset;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

