//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UITabBar;

@interface IGImageWithTextTabBarFooter : UIButton
{
    UITabBar *_backdropTabBar;
}

@property(retain, nonatomic) UITabBar *backdropTabBar; // @synthesize backdropTabBar=_backdropTabBar;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithNormalImage:(id)arg1 highlightedImage:(id)arg2 buttonTitle:(id)arg3 buttonTitleColor:(id)arg4 highlightedTitleColor:(id)arg5 textFontSize:(double)arg6;

@end

