//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FBMediaUploadListener.h"

@class IGFBMediaUploadListenerWrapper, IGImageUploadLogger, NSObject<OS_dispatch_queue>, NSString;

@interface IGImageUploader : NSObject <FBMediaUploadListener>
{
    id <IGNetworking> _networker;
    IGImageUploadLogger *_logger;
    _Bool _cancelled;
    NSObject<OS_dispatch_queue> *_callBackQueue;
    CDUnknownBlockType _completionBlock;
    CDUnknownBlockType _progressBlock;
    id <FBMediaUploadJob> _uploadJob;
    IGFBMediaUploadListenerWrapper *_uploadJobListener;
}

- (void).cxx_destruct;
- (void)uploadWasCancelled:(id)arg1 metrics:(id)arg2;
- (void)uploadHasProgressed:(id)arg1 withProgressInformation:(id)arg2;
- (void)uploadDidFail:(id)arg1 withFailureReason:(unsigned long long)arg2 isResumable:(_Bool)arg3 metrics:(id)arg4;
- (void)uploadDidSucceed:(id)arg1 withResponse:(id)arg2 metrics:(id)arg3;
- (void)_cleanup;
- (id)_optionalConfig;
- (id)_fbMediaUploadConfigWithFbUploadJobId:(id)arg1 uploadParams:(id)arg2 imageUploadConfig:(id)arg3 imageSize:(struct CGSize)arg4 imageMimeType:(id)arg5;
- (void)cancel;
- (void)uploadWithImageUploadSource:(id)arg1 imageSize:(struct CGSize)arg2 imageMimeType:(id)arg3 imageUploadConfig:(id)arg4 fbUploadJobId:(id)arg5 uploadParams:(id)arg6 completionBlock:(CDUnknownBlockType)arg7 progressBlock:(CDUnknownBlockType)arg8 callBackQueue:(id)arg9;
- (id)initWithNetworker:(id)arg1 logger:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

