//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGGridViewCell, NSIndexPath, NSString;

@protocol IGInlineGalleryDataSource
@property(copy, nonatomic) NSString *selectedAssetIdentifier;
@property(nonatomic) __weak id <IGInlineGalleryDataSourceDelegate> delegate;
- (void)decorateGridCell:(IGGridViewCell *)arg1 forAssetAtIndexPath:(NSIndexPath *)arg2;
- (long long)numberOfItems;
- (long long)numMediaSince:(double)arg1;
- (void)setThumbnailSize:(struct CGSize)arg1;
- (_Bool)hasCameraRollAccess;
- (void)pauseDataFetch;
- (void)startDataFetchWithCompletion:(void (^)(void))arg1;
@end

