//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGListDiffable.h"

@class NSArray, NSString;

@interface IGInfoDetailHoursViewModel : NSObject <IGListDiffable>
{
    NSString *_status;
    NSArray *_hours;
}

@property(readonly, copy, nonatomic) NSArray *hours; // @synthesize hours=_hours;
@property(readonly, copy, nonatomic) NSString *status; // @synthesize status=_status;
- (void).cxx_destruct;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (_Bool)isEqual:(id)arg1;
- (id)initWithStatus:(id)arg1 hours:(id)arg2;

@end

