//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class IGKeywordSearchEntity, NSArray, NSString;

@interface IGKeywordSearchResultItemModel : FBValueObject <NSCopying, NSCoding>
{
    IGKeywordSearchEntity *_entity;
    long long _followButtonStyle;
    NSArray *_mediaBundle;
    NSString *_subtitle;
    NSString *_sectionName;
    NSString *_snippet;
}

@property(readonly, copy, nonatomic) NSString *snippet; // @synthesize snippet=_snippet;
@property(readonly, copy, nonatomic) NSString *sectionName; // @synthesize sectionName=_sectionName;
@property(readonly, copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, copy, nonatomic) NSArray *mediaBundle; // @synthesize mediaBundle=_mediaBundle;
@property(readonly, nonatomic) long long followButtonStyle; // @synthesize followButtonStyle=_followButtonStyle;
@property(readonly, copy, nonatomic) IGKeywordSearchEntity *entity; // @synthesize entity=_entity;
- (void).cxx_destruct;
- (id)initWithEntity:(id)arg1 followButtonStyle:(long long)arg2 mediaBundle:(id)arg3 subtitle:(id)arg4 sectionName:(id)arg5 snippet:(id)arg6;

@end

