//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "IGLeadGenCollectionViewDynamicSizingCell.h"

@class NSString, UILabel, UIView;

@interface IGLeadGenFormInfoCell : UICollectionViewCell <IGLeadGenCollectionViewDynamicSizingCell>
{
    UIView *_heroMediaView;
    UIView *_profileImage;
    UILabel *_pageNameView;
    UILabel *_titleView;
    UIView *_pageInfoView;
}

- (void).cxx_destruct;
- (struct CGSize)_titleViewSizeWithConstrainingSize:(struct CGSize)arg1;
- (struct CGSize)_pageNameViewSizeWithConstrainingSize:(struct CGSize)arg1;
- (struct CGSize)dynamicSizeWithConstrainingSize:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)configureWithModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

