//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGLeadGenViewControllerInitializer : NSObject
{
}

+ (id)reactNativeViewControllerForFeedItem:(id)arg1 feedItemTracker:(id)arg2 viewWidth:(double)arg3 directResponseInfo:(id)arg4 pageCellState:(id)arg5 mediaPosition:(long long)arg6 userSession:(id)arg7 loggingDelegate:(id)arg8 hideHeaderImageView:(_Bool)arg9 hideFixedHeaderView:(_Bool)arg10 hideStatusBar:(_Bool)arg11 hideNavigationBar:(_Bool)arg12;
+ (id)viewControllerForFeedItem:(id)arg1 feedItemTracker:(id)arg2 viewWidth:(double)arg3 directResponseInfo:(id)arg4 pageCellState:(id)arg5 mediaPosition:(long long)arg6 userSession:(id)arg7 loggingDelegate:(id)arg8 hideHeaderImageView:(_Bool)arg9 hideFixedHeaderView:(_Bool)arg10 hideStatusBar:(_Bool)arg11 hideNavigationBar:(_Bool)arg12 module:(id)arg13 context:(unsigned long long)arg14 isForStoryAds:(_Bool)arg15;

@end

