//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGAnalyticsNavigationState, IGListCellController, IGUserSession, NSString, UICollectionViewCell, UIViewController;

@protocol IGListSectionContext <NSObject>
- (NSString *)analyticsModule;
- (IGAnalyticsNavigationState *)navState;
- (IGUserSession *)userSession;
- (UICollectionViewCell *)cellForCellController:(IGListCellController *)arg1;
- (void)reloadSectionAnimated:(_Bool)arg1;
- (void)invalidateLayout;
- (long long)section;
- (id <IGListCollectionContext>)collectionContext;
- (UIViewController *)viewController;
@end

