//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGLiveBroadcasterProfileView, IGLiveIndicatorView, IGLiveViewerCountView, IGLiveWithProfileView, IGStoryFullscreenProgressView, IGTapButton, UILabel;

@interface IGLiveViewerHeaderView : UIView
{
    UIView *_followView;
    _Bool _showViewerCount;
    id <IGLiveViewerHeaderViewDelegate> _delegate;
    IGTapButton *_closeButton;
    IGTapButton *_storiesBrowsingButton;
    IGLiveIndicatorView *_liveIndicatorView;
    IGLiveViewerCountView *_viewerCountView;
    IGLiveBroadcasterProfileView *_broadcasterProfileView;
    IGStoryFullscreenProgressView *_progressView;
    IGLiveWithProfileView *_liveWithProfileView;
    UILabel *_playbackTimeLabel;
}

@property(nonatomic) _Bool showViewerCount; // @synthesize showViewerCount=_showViewerCount;
@property(readonly, nonatomic) UILabel *playbackTimeLabel; // @synthesize playbackTimeLabel=_playbackTimeLabel;
@property(readonly, nonatomic) IGLiveWithProfileView *liveWithProfileView; // @synthesize liveWithProfileView=_liveWithProfileView;
@property(readonly, nonatomic) IGStoryFullscreenProgressView *progressView; // @synthesize progressView=_progressView;
@property(readonly, nonatomic) IGLiveBroadcasterProfileView *broadcasterProfileView; // @synthesize broadcasterProfileView=_broadcasterProfileView;
@property(readonly, nonatomic) IGLiveViewerCountView *viewerCountView; // @synthesize viewerCountView=_viewerCountView;
@property(readonly, nonatomic) IGLiveIndicatorView *liveIndicatorView; // @synthesize liveIndicatorView=_liveIndicatorView;
@property(readonly, nonatomic) IGTapButton *storiesBrowsingButton; // @synthesize storiesBrowsingButton=_storiesBrowsingButton;
@property(readonly, nonatomic) IGTapButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) __weak id <IGLiveViewerHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_viewerCountButtonTapped;
- (void)_liveWithProfileTapped;
- (void)_broadcasterProfileTapped;
- (void)_storiesBrowsingTapped;
- (void)_closeButtonTapped;
- (void)configureQuestionsMode:(_Bool)arg1;
- (double)getProgressForSegmentAtIndex:(long long)arg1;
- (void)setProgress:(double)arg1 forSegmentAtIndex:(long long)arg2;
- (void)setViewerCount:(long long)arg1;
- (id)profileImageView;
- (void)_animateView:(id)arg1 show:(_Bool)arg2;
- (void)hidePlaybackTimestamp;
- (void)showPlaybackTimestamp:(long long)arg1;
- (void)configureWithMode:(long long)arg1 broadcaster:(id)arg2 guest:(id)arg3 supportsVerifiedBadge:(_Bool)arg4 profileTitle:(id)arg5 profileSubtitle:(id)arg6 profileSecondarySubtitle:(id)arg7 showEmptyStoryBadge:(_Bool)arg8 showViewerCount:(_Bool)arg9 showProgressBar:(_Bool)arg10 showStoriesBrowsingButton:(_Bool)arg11 showFollowButton:(_Bool)arg12 showInternalOnly:(_Bool)arg13 currentBroadcastIndex:(long long)arg14 totalBroadcastsCount:(long long)arg15 supportsStoryCreationFromHeader:(_Bool)arg16 followView:(id)arg17 module:(id)arg18;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

