//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "IGStoryContentView.h"
#import "IGStoryDimmableView.h"
#import "IGStoryProfileImageContaining.h"

@class IGLiveViewerView, IGStoryVideoView, IGStoryViewerTransitionOverlay, NSString, UIView;

@interface IGLiveFullscreenCell : UICollectionViewCell <IGStoryProfileImageContaining, IGStoryDimmableView, IGStoryContentView>
{
    _Bool _showLandscapeView;
    IGStoryViewerTransitionOverlay *_dimmableView;
    IGLiveViewerView *_viewerOverlayView;
    UIView *_liveWithView;
    IGStoryVideoView *_mediaView;
}

@property(nonatomic) _Bool showLandscapeView; // @synthesize showLandscapeView=_showLandscapeView;
@property(retain, nonatomic) IGStoryVideoView *mediaView; // @synthesize mediaView=_mediaView;
@property(retain, nonatomic) UIView *liveWithView; // @synthesize liveWithView=_liveWithView;
@property(readonly, nonatomic) IGLiveViewerView *viewerOverlayView; // @synthesize viewerOverlayView=_viewerOverlayView;
@property(readonly, nonatomic) IGStoryViewerTransitionOverlay *dimmableView; // @synthesize dimmableView=_dimmableView;
- (void).cxx_destruct;
- (id)contentViewForSnapshot;
- (void)setDimmingPercent:(double)arg1;
- (id)profileImageView;
- (struct CGRect)_mediaViewFrame;
- (struct CGRect)_overlayViewFrame;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

