//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGLocalBusinessStoryTrayDataSource, IGReel, IGUserSession, NSArray, NSNumber, NSString;

@interface IGLocalBusinessDataStore : NSObject
{
    IGUserSession *_userSession;
    long long _dateType;
    NSNumber *_maxPageNumber;
    NSArray *_allMediaModels;
    IGLocalBusinessStoryTrayDataSource *_storyTrayDataSource;
    NSArray *_nearbyBusinessCardModels;
    NSArray *_farBusinessCardModels;
    IGReel *_topLocationReel;
    NSString *_profileChainingTitle;
    NSString *_profileChainingSubitle;
}

- (void).cxx_destruct;
- (_Bool)_isValidForDataType:(long long)arg1 isFirstLoad:(_Bool)arg2 withNewPageNumber:(long long)arg3;
- (void)updateWithTopLocationReel:(id)arg1;
- (id)maxPageNumber;
- (void)updateWithBusinessCardResponse:(id)arg1 isFirstLoad:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)updateWithGridMediaResponse:(id)arg1 isFirstLoad:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)topLocationReel;
- (id)titlesForProfileChainingNavigationBar;
- (id)allBusinessCardViewModels;
- (id)farBusinessCardViewModels;
- (id)nearbyBusinessCardViewModels;
- (id)allMediaModels;
- (id)initWithUserSession:(id)arg1 dataType:(long long)arg2;

@end

