//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGLocalBusinessBusinessCardViewModel, IGLocalBusinessCardViewSectionController, NSString;

@protocol IGLocalBusinessCardViewSectionControllerDelegate <NSObject>
- (void)localBusinessCardViewSectionController:(IGLocalBusinessCardViewSectionController *)arg1 didSelectBusinessCardReelWithModel:(IGLocalBusinessBusinessCardViewModel *)arg2;
- (void)localBusinessCardViewSectionController:(IGLocalBusinessCardViewSectionController *)arg1 didSelectBusinessCardWithModel:(IGLocalBusinessBusinessCardViewModel *)arg2;
- (void)localBusinessCardViewSectionController:(IGLocalBusinessCardViewSectionController *)arg1 didSelectBusinessCardWithModel:(IGLocalBusinessBusinessCardViewModel *)arg2 withFeedItemWithMediaID:(NSString *)arg3;
@end

