//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGLoginManaging.h"

@class IGAccountSwitcher, IGAuthUserParser, IGCurrentUserManager, IGPersistentCookieStore, IGUserCookieStorage, NSString;

@interface IGLoginManager : NSObject <IGLoginManaging>
{
    IGCurrentUserManager *_currentUserManager;
    IGAccountSwitcher *_accountSwitcher;
    IGPersistentCookieStore *_persistentCookieStore;
    IGUserCookieStorage *_userCookieStore;
    IGAuthUserParser *_authUserParser;
    id <IGLoginManagerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_saveCookiesForInternalUsers;
- (void)_handleLoginError;
- (id)_switchAccountsByLoggingInWithUser:(id)arg1 cookies:(id)arg2 facebookAccessToken:(id)arg3 authLogInType:(long long)arg4 notification:(id)arg5;
- (id)_logInWithUser:(id)arg1 cookies:(id)arg2 facebookAccessToken:(id)arg3 authLogInType:(long long)arg4 notification:(id)arg5 destinationURL:(id)arg6;
- (id)beginSessionWithUserDictionary:(id)arg1 cookies:(id)arg2 facebookAccessToken:(id)arg3 authLogInType:(long long)arg4 notification:(id)arg5 destinationURL:(id)arg6;
- (void)postDidEndLoggedOutSessionNotification;
- (id)initWithCurrentUserManager:(id)arg1 accountSwitcher:(id)arg2 persistentCookieStore:(id)arg3 userCookieStore:(id)arg4 authUserParser:(id)arg5 delegate:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

