//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGListSectionController.h"

#import "IGLocalBusinessChangeLocationViewControllerDelegate.h"
#import "IGLocalBusinessLocationEditCellDelegate.h"
#import "IGLocalBusinessSearchLocationViewControllerDelegate.h"

@class CLLocation, IGLocalBusinessLocationCellViewModel, IGUserSession, NSString;

@interface IGLocalBusinessCardPlaceSearchSectionController : IGListSectionController <IGLocalBusinessChangeLocationViewControllerDelegate, IGLocalBusinessLocationEditCellDelegate, IGLocalBusinessSearchLocationViewControllerDelegate>
{
    CLLocation *_location;
    IGUserSession *_userSession;
    IGLocalBusinessLocationCellViewModel *_locationModel;
    id <IGLocalBusinessCardPlaceSearchSectionControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <IGLocalBusinessCardPlaceSearchSectionControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)localBusinessSearchLocationViewControllerDidSelectMap:(id)arg1;
- (void)localBusinessSearchLocationViewController:(id)arg1 didSelectCurrentLocation:(CDStruct_b7cb895d)arg2;
- (void)localBusinessSearchLocationViewController:(id)arg1 didSelectResultForRegion:(CDStruct_b7cb895d)arg2;
- (void)localBusinessSearchLocationViewControllerDidTapCancel:(id)arg1;
- (void)localBusinessChangeLocationViewController:(id)arg1 didTapSearchAreaForRegion:(CDStruct_b7cb895d)arg2;
- (void)localBusinessChangeLocationViewControllerDidTapCancel:(id)arg1;
- (void)didTapChangeLocationButton:(id)arg1;
- (void)didUpdateToObject:(id)arg1;
- (struct CGSize)sizeForItemAtIndex:(long long)arg1;
- (id)cellForItemAtIndex:(long long)arg1;
- (id)initWithUserSession:(id)arg1 location:(id)arg2 locationModel:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

