//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGMainFeedWarmStartUnseenContentHelper : NSObject
{
}

+ (void)logUnseenItems:(id)arg1 bumpedItems:(id)arg2 module:(id)arg3 timeSinceBackground:(double)arg4;
+ (id)tryToBumpUnseenItemsWithNetworkSource:(id)arg1 userSession:(id)arg2 module:(id)arg3 timeSinceBackground:(double)arg4 lastFetchTime:(double)arg5;

@end

