//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGUserDefaults, IGUserSession;

@interface IGMainFeedSlideshowToggle : NSObject
{
    IGUserSession *_userSession;
    IGUserDefaults *_userDefaults;
    _Bool _isTogglePersisted;
    _Bool _defaultToggleValue;
    _Bool _toggleValue;
    _Bool _isEligibleForSlideshow;
    _Bool _isToggleAllowed;
    _Bool _isSlideshowEnabled;
}

@property(readonly, nonatomic) _Bool isSlideshowEnabled; // @synthesize isSlideshowEnabled=_isSlideshowEnabled;
@property(readonly, nonatomic) _Bool isToggleAllowed; // @synthesize isToggleAllowed=_isToggleAllowed;
@property(readonly, nonatomic) _Bool isEligibleForSlideshow; // @synthesize isEligibleForSlideshow=_isEligibleForSlideshow;
- (void).cxx_destruct;
- (void)_showStatusToast;
- (void)_saveOverrideValueOrClearIfDefault;
- (_Bool)_haveSavedToggleOverride;
- (void)_updateEnabledState;
- (void)toggleSlideshowEnabled;
- (id)initWithUserSession:(id)arg1;

@end

