//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGMentionStickerCreationViewController, IGMentionStickerView;

@protocol IGMentionStickerCreationViewControllerDelegate <NSObject>
- (void)mentionStickerViewController:(IGMentionStickerCreationViewController *)arg1 didFinishEditingMentionStickerView:(IGMentionStickerView *)arg2;
- (void)mentionStickerViewController:(IGMentionStickerCreationViewController *)arg1 willFinishEditingMentionStickerView:(IGMentionStickerView *)arg2;
@end

