//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGListSectionController.h"

#import "IGFeedPreviewableSectionController.h"
#import "IGListDisplayDelegate.h"
#import "IGListWorkingRangeDelegate.h"
#import "IGMediaThumbnailCellDelegate.h"
#import "IGMediaThumbnailSectionControllerSelectionDelegate.h"

@class IGCTAPresenterContext, IGFeedItem, IGUserSession, NSDate, NSString, UIColor, UIImageView;

@interface IGMediaThumbnailSectionController : IGListSectionController <IGListDisplayDelegate, IGListWorkingRangeDelegate, IGMediaThumbnailCellDelegate, IGMediaThumbnailSectionControllerSelectionDelegate, IGFeedPreviewableSectionController>
{
    IGUserSession *_userSession;
    NSString *_analyticsModule;
    struct IGGridLayoutConfiguration _layoutConfig;
    id <IGMediaThumbnailConfigurationType> _thumbnailConfig;
    _Bool _isThumbnailLoadedOnce;
    IGCTAPresenterContext *_ctaPresenterContext;
    UIImageView *_heartImageView;
    _Bool _supportDoubleTap;
    _Bool _forceServerBestFit;
    _Bool _selected;
    id <IGMediaThumbnailSectionControllerDelegate> _delegate;
    id <IGMediaThumbnailSectionControllerSelectionDelegate> _selectionDelegate;
    IGFeedItem *_feedItem;
    UIColor *_predominantMediaColor;
    long long _singleFeedEntryPoint;
    NSDate *_visibleDate;
}

@property(retain, nonatomic) NSDate *visibleDate; // @synthesize visibleDate=_visibleDate;
@property(nonatomic, getter=isSelected) _Bool selected; // @synthesize selected=_selected;
@property(nonatomic) long long singleFeedEntryPoint; // @synthesize singleFeedEntryPoint=_singleFeedEntryPoint;
@property(retain, nonatomic) UIColor *predominantMediaColor; // @synthesize predominantMediaColor=_predominantMediaColor;
@property(nonatomic) _Bool forceServerBestFit; // @synthesize forceServerBestFit=_forceServerBestFit;
@property(readonly, nonatomic) IGFeedItem *feedItem; // @synthesize feedItem=_feedItem;
@property(nonatomic) __weak id <IGMediaThumbnailSectionControllerSelectionDelegate> selectionDelegate; // @synthesize selectionDelegate=_selectionDelegate;
@property(readonly, nonatomic) __weak id <IGMediaThumbnailSectionControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_handleThumbnailCellDidEndLoading:(id)arg1 isSuccess:(_Bool)arg2;
- (void)_handleThumbnailCellDidStartLoading:(id)arg1;
- (void)_handleSingleTapAtIndex:(long long)arg1;
- (void)_configureCell:(id)arg1 atIndex:(long long)arg2;
- (void)presentFeedPreviewableItem;
- (void)didSelectFeedItem:(id)arg1;
- (void)mediaThumbnailCellDidDoubleTap:(id)arg1;
- (void)mediaThumbnailCellDidSingleTap:(id)arg1;
- (void)mediaThumbnailCell:(id)arg1 didFailLoadWithError:(id)arg2 networkRequestSummary:(id)arg3;
- (void)mediaThumbnailCell:(id)arg1 didLoadImage:(id)arg2 source:(id)arg3 networkRequestSummary:(id)arg4;
- (void)_reloadSection;
- (void)_onFeedItemUpdated:(id)arg1;
- (void)_onFeedItemRevealed:(id)arg1;
- (void)_onFeedItemHidden:(id)arg1;
- (void)listAdapter:(id)arg1 didEndDisplayingSectionController:(id)arg2 cell:(id)arg3 atIndex:(long long)arg4;
- (void)listAdapter:(id)arg1 willDisplaySectionController:(id)arg2 cell:(id)arg3 atIndex:(long long)arg4;
- (void)listAdapter:(id)arg1 didEndDisplayingSectionController:(id)arg2;
- (void)listAdapter:(id)arg1 willDisplaySectionController:(id)arg2;
- (void)listAdapter:(id)arg1 sectionControllerDidExitWorkingRange:(id)arg2;
- (void)listAdapter:(id)arg1 sectionControllerWillEnterWorkingRange:(id)arg2;
- (void)didSelectItemAtIndex:(long long)arg1;
- (void)didUpdateToObject:(id)arg1;
- (struct CGSize)sizeForItemAtIndex:(long long)arg1;
- (id)cellForItemAtIndex:(long long)arg1;
- (long long)numberOfItems;
- (id)initWithUserSession:(id)arg1 layoutConfig:(struct IGGridLayoutConfiguration)arg2 thumbnailConfig:(id)arg3 analyticsModule:(id)arg4 delegate:(id)arg5 ctaPresenterContext:(id)arg6 supportDoubleTap:(_Bool)arg7;
- (id)initWithUserSession:(id)arg1 layoutConfig:(struct IGGridLayoutConfiguration)arg2 thumbnailConfig:(id)arg3 analyticsModule:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

