//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface IGMediaUploadHandler : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    id <IGMediaUploadJobFactory> _uploadJobFactory;
    id <IGNetworking> _networkDispatcher;
}

@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (void)cancelUploadJob:(id)arg1;
- (id)startUploadJobWithContentSource:(id)arg1 config:(id)arg2 token:(id)arg3 listener:(id)arg4;
- (id)initWithNetworkDispatcher:(id)arg1 uploadJobFactory:(id)arg2 queue:(id)arg3;

@end

