//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOrderedSet;

@interface IGModuleState : NSObject
{
    struct unique_ptr<const std::__1::unordered_map<unsigned long, IGActiveModuleItem *, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, IGActiveModuleItem *>>>, std::__1::default_delete<const std::__1::unordered_map<unsigned long, IGActiveModuleItem *, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, IGActiveModuleItem *>>>>> _itemKeyMap;
    NSOrderedSet *_itemsInOrder;
    long long _scrollDirection;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (long long)scrollDirection;
- (id)allActiveItems;
- (_Bool)isItemActive:(id)arg1;
- (id)mostRecentlyActiveItem;
- (id)initWithItems:(id)arg1 map:(unordered_map_a764cb8e *)arg2 scrollDirection:(long long)arg3;
- (id)init;

@end

