//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGMutedListNetworkDataSource;

@protocol IGMutedListNetworkDataSourceDelegate
- (void)dataSourceDidFailLoad:(IGMutedListNetworkDataSource *)arg1;
- (void)dataSourceDidFinishLoading:(IGMutedListNetworkDataSource *)arg1;
- (void)dataSourceDidStartLoading:(IGMutedListNetworkDataSource *)arg1;
@end

