//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGUserSession, NSMutableArray, NSString;

@interface IGMutedListNetworkDataSource : NSObject
{
    NSMutableArray *_mutedUsers;
    IGUserSession *_userSession;
    NSString *_maxID;
    _Bool _isLoading;
    _Bool _areMoreUsersAvailable;
    id <IGMutedListNetworkDataSourceDelegate> _delegate;
    NSString *_errorMessage;
}

@property(readonly, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(readonly, nonatomic) _Bool areMoreUsersAvailable; // @synthesize areMoreUsersAvailable=_areMoreUsersAvailable;
@property(readonly, nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) __weak id <IGMutedListNetworkDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_onUserFetchFailed:(id)arg1 fromRequest:(id)arg2;
- (void)_onUsersReceived:(id)arg1 fromRequest:(id)arg2;
- (void)_fetchDataWithRefresh:(_Bool)arg1;
- (void)removeUnmutedUsers;
- (long long)numberOfResults;
- (id)resultForRow:(long long)arg1;
- (void)fetchMoreData;
- (void)refreshData;
- (id)initWithUserSession:(id)arg1;

@end

