//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGEmojiModel, IGNametagStickerTrayViewController, IGStoryStickerTrayStateModel;

@protocol IGNametagStickerTrayViewControllerDelegate <NSObject>
- (void)cardStickerTrayViewController:(IGNametagStickerTrayViewController *)arg1 didSelectEmoji:(IGEmojiModel *)arg2;
- (void)cardStickerTrayViewController:(IGNametagStickerTrayViewController *)arg1 didDismissWithFinalTrayStateModel:(IGStoryStickerTrayStateModel *)arg2;
@end

