//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIImageView, UILabel;

@interface IGNearbyBannerCollectionViewCell : UICollectionViewCell
{
    UILabel *_titleLabel;
    UIImageView *_iconImageView;
}

- (void).cxx_destruct;
- (void)changeTitle:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

