//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGNetegoSurveyItem, IGUserSession;

@interface IGNetegoSurveyLogger : NSObject
{
    IGNetegoSurveyItem *_surveyItem;
    IGUserSession *_userSession;
}

- (void).cxx_destruct;
- (void)_logtWithEventSuffix:(id)arg1 extraDict:(id)arg2;
- (void)logHideResponseWithReason:(id)arg1;
- (void)logHideAllPollsButtonOnSelect;
- (void)logHideThisButtonOnSelect;
- (void)logSurveyResponseWithQuestionId:(id)arg1 answers:(id)arg2;
- (void)logImpressionForNetegoSurveyItem;
- (id)initWithUserSession:(id)arg1 netegoSurveyItem:(id)arg2;

@end

