//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGNetworkerOperationsListener.h"

@class IGNetworker, NSString;

@interface IGNetworkActivityIndicatorManager : NSObject <IGNetworkerOperationsListener>
{
    IGNetworker *_networker;
    _Bool _isNetworkActivityIndicatorVisible;
    CDUnknownBlockType _deferredUpdateBlock;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)networkOperationsDidChange;
- (void)_updateNetworkActivityIndicatorVisibility;
- (void)_scheduleUpdateForNetworkActivityIndicator;
- (void)_setNetworker:(id)arg1;
- (void)enableActivityIndicatorByObservingNetworker:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

