//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSData, NSDate;

@protocol IGNetworkCachedData
@property(readonly, nonatomic) NSDate *dateInvalid;
@property(readonly, nonatomic) NSDate *fetched;
@property(readonly, nonatomic) NSDate *lastAccessed;
@property(readonly, nonatomic) NSData *cachedData;
- (void)invalidate;
@end

