//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGHTTPResponse, IGNetworkingRequest, IGRequestPolicy;

@protocol IGNetworkDispatcherPerformanceLogging <NSObject>
- (void)markRequestDidCancel:(IGNetworkingRequest *)arg1;
- (void)markRequestDidFail:(IGNetworkingRequest *)arg1;
- (void)markRequestDidSucceed:(IGNetworkingRequest *)arg1;
- (void)markRequest:(IGNetworkingRequest *)arg1 withResponseSize:(unsigned long long)arg2;
- (void)markRequest:(IGNetworkingRequest *)arg1 didReceiveResponse:(IGHTTPResponse *)arg2;
- (void)markRequestDidStart:(IGNetworkingRequest *)arg1;
- (void)markPositionInQueue:(unsigned long long)arg1 forRequest:(IGNetworkingRequest *)arg2;
- (void)startMarkerForRequest:(IGNetworkingRequest *)arg1 policy:(IGRequestPolicy *)arg2;
@end

