//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGNetegoSurveyHeader;

@protocol IGNetegoSurveyHeaderDelegate <NSObject>
- (void)netegoSurveyHeaderDidTapOnMoreButton:(IGNetegoSurveyHeader *)arg1;
- (void)netegoSurveyHeaderDidTapOnAvatar:(IGNetegoSurveyHeader *)arg1;
- (void)netegoSurveyHeaderDidTapUser:(IGNetegoSurveyHeader *)arg1;
@end

