//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIPanGestureRecognizer;

@interface IGPanAnimationView : UIView
{
    _Bool _isAnimating;
    id <IGPanAnimationViewDelegate> _delegate;
    UIPanGestureRecognizer *_pan;
    struct CGRect _viewBound;
}

@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(nonatomic) struct CGRect viewBound; // @synthesize viewBound=_viewBound;
@property(readonly, nonatomic) UIPanGestureRecognizer *pan; // @synthesize pan=_pan;
@property(nonatomic) __weak id <IGPanAnimationViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_cancelLeftPanAnimation:(CDUnknownBlockType *)arg1 completion:(CDUnknownBlockType *)arg2 duration:(double)arg3;
- (void)_cancelRightPanAnimation:(CDUnknownBlockType *)arg1 completion:(CDUnknownBlockType *)arg2 duration:(double)arg3;
- (void)_finishLeftPanAnimation:(CDUnknownBlockType *)arg1 completion:(CDUnknownBlockType *)arg2 duration:(double)arg3;
- (void)_finishRightPanAnimation:(CDUnknownBlockType *)arg1 completion:(CDUnknownBlockType *)arg2 duration:(double)arg3;
- (_Bool)_shouldFinishPanAnimation:(id)arg1;
- (_Bool)_panGestureMovingRight:(double)arg1;
- (double)_computeAnimationTime:(double)arg1;
- (void)_finishTranslationAnimation:(id)arg1;
- (void)_handlePan:(id)arg1;
- (void)layoutSubviews;
- (id)init;

@end

