//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface IGPhotoTaggingView : UIView
{
    id <IGTaggingViewConfiguration> _taggingViewConfig;
    _Bool _hasMultipleAssets;
    _Bool _hasAddedTags;
    _Bool _allowTagging;
    UILabel *_guidanceLabel;
}

- (void).cxx_destruct;
- (id)_attributedStringWithHasAddedTags:(_Bool)arg1 taggingLimitReached:(_Bool)arg2 hasMultipleAssets:(_Bool)arg3;
- (void)_updateLabels;
- (void)configureWithHasAddedTags:(_Bool)arg1 allowTagging:(_Bool)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 taggingViewConfig:(id)arg2 hasMultipleAssets:(_Bool)arg3;

@end

