//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGPostSession, IGPostSessionContext, NSData, NSString, NSURL;

@protocol IGPostSessionDelegate <NSObject>
- (void)postSession:(IGPostSession *)arg1 didRenderVideoUrl:(NSURL *)arg2 mediaId:(NSString *)arg3;
- (void)postSession:(IGPostSession *)arg1 didRenderImageData:(NSData *)arg2 mediaId:(NSString *)arg3;
- (void)postSessionDidSucceedUpload:(IGPostSession *)arg1;
- (void)postSession:(IGPostSession *)arg1 didAddShare:(NSString *)arg2;
- (void)postSession:(IGPostSession *)arg1 didUpdateWithContext:(IGPostSessionContext *)arg2;
@end

