//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGPostLoggingContext, IGPostShareSessionContext, IGUserSession, NSDictionary, NSMutableArray, NSMutableDictionary, NSMutableOrderedSet;

@interface IGPostShareSession : NSObject
{
    id <IGAPIClient> _networker;
    IGPostLoggingContext *_loggingContext;
    IGUserSession *_userSession;
    NSMutableDictionary *_shareIdToStatus;
    NSMutableDictionary *_shareIdToConfig;
    NSMutableDictionary *_shareIdToActiveShareService;
    NSMutableOrderedSet *_shareIdSortedByShareTime;
    NSDictionary *_crossAccountSharingNonces;
    _Bool _sequentialShare;
    NSMutableArray *_queuedShareIds;
    _Bool _processingQueuedShare;
    long long _retryCount;
    id <IGPostShareSessionDelegate> _delegate;
}

@property(nonatomic) __weak id <IGPostShareSessionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)debugDescription;
- (void)_handleShareCompletionWithShareId:(id)arg1 queueProcessing:(_Bool)arg2 error:(id)arg3 serverResponse:(id)arg4;
- (id)_createContext;
- (void)_startShareId:(id)arg1 crossAccountSharingNonces:(id)arg2 queueProcessing:(_Bool)arg3;
- (void)_processQueue;
- (id)configForShareId:(id)arg1;
- (long long)statusForShareId:(id)arg1;
- (id)allShareIds;
- (void)retryShareId:(id)arg1 crossAccountSharingNonces:(id)arg2;
- (void)cancelShareId:(id)arg1 resumable:(_Bool)arg2;
- (void)startSharingWithCrossAccountSharingNonces:(id)arg1;
@property(readonly, nonatomic) _Bool isPermanentlyFailed;
@property(readonly, copy, nonatomic) IGPostShareSessionContext *context;
- (id)addShareWithConfig:(id)arg1;
- (id)initWithNetworker:(id)arg1 userSession:(id)arg2 context:(id)arg3 sequentialShare:(_Bool)arg4 loggingContext:(id)arg5;

@end

