//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGLiveInteractivityHelperDelegate.h"

@class IGLiveInteractivityService, IGLiveInteractivityTimestampHelper, NSString;

@interface IGPostLiveInteractivityController : NSObject <IGLiveInteractivityHelperDelegate>
{
    IGLiveInteractivityService *_interactivityService;
    IGLiveInteractivityTimestampHelper *_timestampHelper;
    long long _refetchIntervalCounter;
    id <IGPostLiveInteractivityControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <IGPostLiveInteractivityControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)timestampHelper:(id)arg1 didReceiveHistoricalEvent:(id)arg2 atApproximateTimestamp:(double)arg3;
- (void)timestampHelper:(id)arg1 removeCurrentEventAtTimestamp:(double)arg2;
- (void)timestampHelper:(id)arg1 didReceiveEvent:(id)arg2 atTimestamp:(double)arg3;
- (void)_updateToEvent:(id)arg1 atTimestamp:(double)arg2;
- (void)_fetchAllQuestionEvents;
- (void)updateToOffset:(double)arg1;
- (id)initWithBroadcastId:(id)arg1 userSession:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

