//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGPopoverStyle : NSObject
{
    double _minimumMargin;
    double _maximumWidth;
    double _cornerRadius;
}

+ (id)betaChannelPopoverStyle;
+ (id)alertsPopoverStyle;
+ (id)favoritesPopoverStyle;
+ (id)defaultPopoverStyle;
@property(readonly, nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(readonly, nonatomic) double maximumWidth; // @synthesize maximumWidth=_maximumWidth;
@property(readonly, nonatomic) double minimumMargin; // @synthesize minimumMargin=_minimumMargin;
- (id)initWithMinimumMargin:(double)arg1 maximumWidth:(double)arg2 cornerRadius:(double)arg3;

@end

