//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSString, UIImage;

@interface IGPostShareModel : FBValueObject <NSCopying, NSCoding>
{
    NSString *_postId;
    NSString *_shareId;
    long long _postDataType;
    long long _shareType;
    long long _status;
    UIImage *_previewImage;
}

@property(readonly, copy, nonatomic) UIImage *previewImage; // @synthesize previewImage=_previewImage;
@property(readonly, nonatomic) long long status; // @synthesize status=_status;
@property(readonly, nonatomic) long long shareType; // @synthesize shareType=_shareType;
@property(readonly, nonatomic) long long postDataType; // @synthesize postDataType=_postDataType;
@property(readonly, copy, nonatomic) NSString *shareId; // @synthesize shareId=_shareId;
@property(readonly, copy, nonatomic) NSString *postId; // @synthesize postId=_postId;
- (void).cxx_destruct;
- (id)initWithPostId:(id)arg1 shareId:(id)arg2 postDataType:(long long)arg3 shareType:(long long)arg4 status:(long long)arg5 previewImage:(id)arg6;

@end

