//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NativeIGPostInsightsReactModuleSpec.h"
#import "RCTBridgeModule.h"
#import "RCTIGUserSessionModule.h"

@class IGUserSession, NSObject<OS_dispatch_queue>, NSString, RCTBridge;

@interface IGPostInsightsReactModule : NSObject <NativeIGPostInsightsReactModuleSpec, RCTIGUserSessionModule, RCTBridgeModule>
{
    IGUserSession *_userSession;
}

+ (const struct RCTMethodInfo *)__rct_export__661;
+ (const struct RCTMethodInfo *)__rct_export__540;
+ (void)load;
+ (id)moduleName;
@property(nonatomic) __weak IGUserSession *userSession; // @synthesize userSession=_userSession;
- (void).cxx_destruct;
- (void)toggleNavigationBar:(double)arg1 hideActionBar:(_Bool)arg2;
- (void)didFinishLoading:(double)arg1;

// Remaining properties
@property(readonly, nonatomic) __weak RCTBridge *bridge;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;
@property(readonly) Class superclass;

@end

