//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGSideTrayLoggingController.h"
#import "IGSideTrayNavigationHandler.h"

@class IGUserSession, NSString;

@interface IGProfileSideTrayController : NSObject <IGSideTrayLoggingController, IGSideTrayNavigationHandler>
{
    IGUserSession *_userSession;
    id <IGSideTrayNavigationControllerProvider> _navigationProvider;
    NSString *_analyticsModule;
}

- (void).cxx_destruct;
- (void)handleNavigationWithBlock:(CDUnknownBlockType)arg1 dismissSideTray:(_Bool)arg2;
- (void)logTapAction:(id)arg1;
- (id)initWithAnalyticsModule:(id)arg1 userSession:(id)arg2 navigationProvider:(id)arg3;

@end

