//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGStyledString, NSNumber;

@interface IGProfileHeaderBioSectionModel : NSObject
{
    NSNumber *_profileBioFieldValue;
    double _topPadding;
    IGStyledString *_styledString;
}

@property(readonly, nonatomic) IGStyledString *styledString; // @synthesize styledString=_styledString;
@property(readonly, nonatomic) double topPadding; // @synthesize topPadding=_topPadding;
@property(readonly, nonatomic) NSNumber *profileBioFieldValue; // @synthesize profileBioFieldValue=_profileBioFieldValue;
- (void).cxx_destruct;
- (id)initWithProfileBioFieldValue:(id)arg1 topPadding:(double)arg2 styledString:(id)arg3;

@end

