//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "IGListDiffable.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class IGStyledString, IGUser, NSString;

@interface IGProfileBioModel : FBValueObject <IGListDiffable, NSCopying, NSCoding>
{
    IGUser *_user;
    id <IGAPIClient> _networker;
    NSString *_analyticsModule;
    IGStyledString *_overrideBioString;
}

@property(readonly, copy, nonatomic) IGStyledString *overrideBioString; // @synthesize overrideBioString=_overrideBioString;
@property(readonly, copy, nonatomic) NSString *analyticsModule; // @synthesize analyticsModule=_analyticsModule;
@property(readonly, nonatomic) id <IGAPIClient> networker; // @synthesize networker=_networker;
@property(readonly, copy, nonatomic) IGUser *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (id)initWithUser:(id)arg1 networker:(id)arg2 analyticsModule:(id)arg3 overrideBioString:(id)arg4;

@end

