//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGStartupPrefetchJobProducer.h"
#import "IGStartupPrefetchManagerListener.h"

@class IGUserSession, NSOperationQueue, NSString;

@interface IGPresenceBackgroundFetchDataProvider : NSObject <IGStartupPrefetchManagerListener, IGStartupPrefetchJobProducer>
{
    IGUserSession *_userSession;
    NSOperationQueue *_presenceFetchQueue;
    id <IGPresenceBackgroundFetchStateChangeDelegate> _delegate;
}

+ (id)_presenceMappingDictFromResponseDict:(id)arg1;
+ (id)_newGetPresenceRequest;
@property(nonatomic) __weak id <IGPresenceBackgroundFetchStateChangeDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)finishedFetchingPrefetchWithIdentifier:(id)arg1;
- (id)prefetchJob;
- (void)_applicationWillEnterForeground:(id)arg1;
- (void)_applicationDidEnterBackground:(id)arg1;
- (void)_startListeningToAppStateChanges;
- (void)_enqueuePresenceFetchOperation;
- (void)triggerPresenceRefresh;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

