//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGUser, IGUserSession, NSString, UINavigationController;

@interface IGProfileBioLinkNavigationHandler : NSObject
{
    IGUserSession *_userSession;
    IGUser *_user;
    UINavigationController *_navigationController;
    NSString *_analyticsModule;
}

- (void).cxx_destruct;
- (void)_untagSelfNetworkRequest;
- (id)_hashtagLinkForText:(id)arg1;
- (id)_userLinkForText:(id)arg1;
- (void)_showAlertForUntaggingSelf;
- (void)_showActionSheetForTappingOnOwnTagWithLink:(id)arg1;
- (void)_navigateToUserWithLink:(id)arg1;
- (void)navigateToUserForLinkText:(id)arg1;
- (void)navigateToHashtagForLinkText:(id)arg1;
- (id)initWithUserSession:(id)arg1 navigationController:(id)arg2 user:(id)arg3 analyticsModule:(id)arg4;

@end

