//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSString;

@interface IGQPTooltipAnchorID : FBValueObject <NSCopying, NSCoding>
{
    NSString *_anchorID;
}

@property(readonly, copy, nonatomic) NSString *anchorID; // @synthesize anchorID=_anchorID;
- (void).cxx_destruct;
- (id)initWithAnchorID:(id)arg1;

@end

