//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IGPhoneNumberTextFieldDelegate.h"
#import "IGQPMegaphoneViewProtocol.h"
#import "IGRemoteImageViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class IGFacepileComponentView, IGPhoneNumberTextField, IGQPMegaphone, IGRemoteImageView, IGTextButton, NSString, UIActivityIndicatorView, UIButton, UILabel;

@interface IGQPMegaphoneView : UIView <IGRemoteImageViewDelegate, IGPhoneNumberTextFieldDelegate, UIGestureRecognizerDelegate, IGQPMegaphoneViewProtocol>
{
    IGQPMegaphone *_megaphone;
    IGFacepileComponentView *_facepileView;
    UILabel *_titleLabelView;
    UILabel *_messageLabelView;
    UILabel *_socialContextLabelView;
    IGPhoneNumberTextField *_inlineTextField;
    IGRemoteImageView *_imageView;
    UIButton *_dismissButton;
    UIView *_lineView;
    IGTextButton *_primaryButton;
    IGTextButton *_secondaryButton;
    UIView *_buttonsView;
    UIActivityIndicatorView *_spinnerView;
    id <IGQPMegaphoneViewDelegate> _delegate;
}

@property(nonatomic) __weak id <IGQPMegaphoneViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_didTriggerTapGesture;
- (void)_prefillInlineTextField:(id)arg1;
- (void)_setButtonsEnabled:(_Bool)arg1;
- (void)_hideSpinnerForButton:(id)arg1;
- (void)_showSpinnerForButton:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)textFieldDidTapCountryButton:(id)arg1;
- (void)remoteImageView:(id)arg1 didUpdateDownloadProgress:(double)arg2;
- (void)remoteImageView:(id)arg1 didFailToLoadImageWithError:(id)arg2 networkRequestSummary:(id)arg3;
- (void)remoteImageView:(id)arg1 didLoadPreviewWithProgressiveJPEGScanNumber:(id)arg2;
- (void)remoteImageView:(id)arg1 didLoadImageFromSource:(unsigned long long)arg2 networkRequestSummary:(id)arg3;
- (void)_didTapButton:(id)arg1 buttonView:(id)arg2;
- (void)_didTapButtonTwo;
- (void)_didTapButtonOne;
- (void)_didTapDismissButton;
- (id)_createSpinnerView;
- (id)_createFacepileView;
- (id)_createMegaphoneImageView;
- (id)_createInlineTextField;
- (id)_createSocialContextLabelView;
- (id)_createMessageLabelView;
- (id)_createTitleLabelView;
- (id)_createDismissButton;
- (id)_createButtonsView;
- (struct CGSize)_imageSize;
- (struct CGSize)_imageViewSize;
- (struct CGRect)_secondaryButtonRectForViewWidth:(double)arg1;
- (void)_layoutInlineField;
- (void)_layoutTextView;
- (void)_layoutButtons;
- (void)_layoutDismissButton;
- (void)_layoutImageView;
- (void)_layoutFacepileView;
- (_Bool)_hasInlineEditingTextField;
- (_Bool)_hasSocialContextText;
- (_Bool)_hasSocialContextFacepile;
- (_Bool)_megaphoneHasImage;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)setInlineTextFieldWithCountryCode:(id)arg1 countryNumber:(id)arg2;
- (id)initWithMegaphone:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

