//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGQuizStickerConsumptionViewController, IGQuizStickerView, NSNumber;

@protocol IGQuizStickerConsumptionViewControllerDelegate <NSObject>
- (void)quizStickerConsumptionViewController:(IGQuizStickerConsumptionViewController *)arg1 didDismissSticker:(IGQuizStickerView *)arg2 withVote:(NSNumber *)arg3;
@end

