//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGQuizStickerCreationViewController, IGQuizStickerView;

@protocol IGQuizStickerCreationViewControllerDelegate <NSObject>
- (void)quizStickerCreationViewController:(IGQuizStickerCreationViewController *)arg1 didFinishEditingQuizStickerView:(IGQuizStickerView *)arg2;
@end

