//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGRageShakeReport, NSNumber, NSString;

@protocol IGRageShakeViewControllerUploader
- (void)uploadRageShakeReport:(IGRageShakeReport *)arg1 withType:(long long)arg2 description:(NSString *)arg3 lastViewControllerName:(NSString *)arg4 categoryIdOverride:(NSNumber *)arg5;
@end

