//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBSDKAccessToken, IGAuthenticator, IGContactPointPrefillDataFetcher, IGFacebookAuthHelper, IGFacebookInfoFetcher, IGRegistrationFlowConfiguration, IGRegistrationLogger, NSArray, NSDictionary, NSString;

@interface IGRegistrationFlowContext : NSObject
{
    _Bool _isSMSConsent;
    _Bool _isGDPRRequired;
    _Bool _isPhoneNumberTaken;
    IGRegistrationFlowConfiguration *_configuration;
    id <IGAPIClient> _loggedOutNetworker;
    IGAuthenticator *_authenticator;
    IGFacebookAuthHelper *_fbAuthHelper;
    IGContactPointPrefillDataFetcher *_contactPointPrefillDataFetcher;
    IGFacebookInfoFetcher *_fbInfoFetcher;
    IGRegistrationLogger *_logger;
    long long _flowType;
    NSDictionary *_facebookMeInfo;
    NSArray *_suggestedUsernames;
    FBSDKAccessToken *_facebookAccessToken;
    NSString *_phoneNumber;
    NSString *_email;
    NSString *_username;
    NSString *_fullName;
    NSString *_password;
    NSString *_tosVersion;
    NSString *_smsVerificationCode;
    NSString *_forceSignUpCode;
}

@property(readonly, copy, nonatomic) NSString *forceSignUpCode; // @synthesize forceSignUpCode=_forceSignUpCode;
@property(readonly, copy, nonatomic) NSString *smsVerificationCode; // @synthesize smsVerificationCode=_smsVerificationCode;
@property(readonly, copy, nonatomic) NSString *tosVersion; // @synthesize tosVersion=_tosVersion;
@property(readonly, copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(readonly, copy, nonatomic) NSString *fullName; // @synthesize fullName=_fullName;
@property(readonly, copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(readonly, copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(readonly, copy, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(readonly, nonatomic) FBSDKAccessToken *facebookAccessToken; // @synthesize facebookAccessToken=_facebookAccessToken;
@property(readonly, nonatomic) _Bool isPhoneNumberTaken; // @synthesize isPhoneNumberTaken=_isPhoneNumberTaken;
@property(readonly, nonatomic) _Bool isGDPRRequired; // @synthesize isGDPRRequired=_isGDPRRequired;
@property(readonly, nonatomic) _Bool isSMSConsent; // @synthesize isSMSConsent=_isSMSConsent;
@property(readonly, nonatomic) NSArray *suggestedUsernames; // @synthesize suggestedUsernames=_suggestedUsernames;
@property(readonly, nonatomic) NSDictionary *facebookMeInfo; // @synthesize facebookMeInfo=_facebookMeInfo;
@property(readonly, nonatomic) long long flowType; // @synthesize flowType=_flowType;
@property(readonly, nonatomic) IGRegistrationLogger *logger; // @synthesize logger=_logger;
@property(readonly, nonatomic) IGFacebookInfoFetcher *fbInfoFetcher; // @synthesize fbInfoFetcher=_fbInfoFetcher;
@property(readonly, nonatomic) IGContactPointPrefillDataFetcher *contactPointPrefillDataFetcher; // @synthesize contactPointPrefillDataFetcher=_contactPointPrefillDataFetcher;
@property(readonly, nonatomic) IGFacebookAuthHelper *fbAuthHelper; // @synthesize fbAuthHelper=_fbAuthHelper;
@property(readonly, nonatomic) IGAuthenticator *authenticator; // @synthesize authenticator=_authenticator;
@property(readonly, nonatomic) id <IGAPIClient> loggedOutNetworker; // @synthesize loggedOutNetworker=_loggedOutNetworker;
@property(readonly, nonatomic) IGRegistrationFlowConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (void)updateWithForceSignUpCode:(id)arg1;
- (void)updateWithSmsVerificationCode:(id)arg1;
- (void)updateWithTosVersion:(id)arg1;
- (void)updateWithPassword:(id)arg1;
- (void)updateWithFullName:(id)arg1;
- (void)updateWithUsername:(id)arg1;
- (void)updateWithEmail:(id)arg1;
- (void)updateWithPhoneNumber:(id)arg1;
- (void)updateWithFacebookAccessToken:(id)arg1;
- (void)updateWithIsPhoneNumberTaken:(_Bool)arg1;
- (void)updateWithIsGDPRRequired:(_Bool)arg1;
- (void)updateWithIsSMSConsent:(_Bool)arg1;
- (void)ingestSuggestedUsernames:(id)arg1;
- (void)updateWithFlowType:(long long)arg1;
@property(readonly, copy, nonatomic) NSString *flowTypeString;
- (id)initWithConfiguration:(id)arg1 facebookMeInfo:(id)arg2 loggedOutNetworker:(id)arg3 authenticator:(id)arg4 fbAuthHelper:(id)arg5 contactPointPrefillDataFetcher:(id)arg6 fbInfoFetcher:(id)arg7 logger:(id)arg8;

@end

