//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGListSectionController.h"

#import "IGRecommenderProfileCellDelegate.h"

@class IGRecommenderProfileConfiguration, IGUserSession, NSString;

@interface IGRecommendAccountsSectionController : IGListSectionController <IGRecommenderProfileCellDelegate>
{
    NSString *_module;
    IGUserSession *_userSession;
    IGRecommenderProfileConfiguration *_configuration;
}

- (void).cxx_destruct;
- (void)_openRecommenderProfile;
- (void)recommenderProfileCellViewRecommenderNameTapped:(id)arg1;
- (void)recommenderProfileCellViewProfilePictureTapped:(id)arg1;
- (void)didUpdateToObject:(id)arg1;
- (id)cellForItemAtIndex:(long long)arg1;
- (struct CGSize)sizeForItemAtIndex:(long long)arg1;
- (long long)numberOfItems;
- (id)initWithUserSession:(id)arg1 module:(id)arg2;

@end

