//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGKeyboardObserverFrameChangeDelegate.h"
#import "IGReportPopoverViewDelegate.h"

@class IGBugReportUploader, IGCrashTaskDetailsModel, IGKeyboardObserver, IGRageShakeReport, IGReportPopoverView, IGUserSession, NSMutableArray, NSString;

@interface IGReportPopoverViewController : IGViewController <IGReportPopoverViewDelegate, IGKeyboardObserverFrameChangeDelegate>
{
    IGUserSession *_userSession;
    IGCrashTaskDetailsModel *_crashTaskModel;
    IGReportPopoverView *_popoverView;
    id <IGReportPopoverCaptureProtocol> _captureDelegate;
    IGBugReportUploader *_uploader;
    IGRageShakeReport *_report;
    long long _bugReportType;
    NSMutableArray *_scaledImageAttachments;
    NSMutableArray *_orderedAttachments;
    long long _currentEditIndex;
    IGKeyboardObserver *_keyboardObserver;
    _Bool _photoLibraryEnabled;
}

@property(nonatomic) _Bool photoLibraryEnabled; // @synthesize photoLibraryEnabled=_photoLibraryEnabled;
- (void).cxx_destruct;
- (void)updateAttachmentWithUIImage:(id)arg1;
- (_Bool)isAttachmentVideoAtIndex:(long long)arg1;
- (void)reportPopoverViewReportDescriptionChange:(id)arg1;
- (void)reportAppUpdatePopoverView:(id)arg1;
- (void)reportPopoverView:(id)arg1 didDeleteImageAtIndex:(long long)arg2;
- (void)reportPopoverView:(id)arg1 didSelectImageAtIndex:(long long)arg2;
- (void)reportPopoverView:(id)arg1 didSelectVideoRecordButton:(id)arg2;
- (void)reportPopoverView:(id)arg1 didSelectPhotoLibraryButton:(id)arg2;
- (void)reportPopoverView:(id)arg1 didSelectCaptureButton:(id)arg2;
- (void)reportPopoverView:(id)arg1 didSelectTaskLabel:(id)arg2;
- (void)keyboardObserver:(id)arg1 keyboardFrameDidChangeWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(long long)arg5;
- (void)keyboardObserver:(id)arg1 keyboardFrameWillChangeWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(long long)arg5;
- (void)_updateEnableSendButton;
- (void)_editReportAttachmentImage:(id)arg1;
- (void)editReportAttachment:(id)arg1;
- (void)_onCloseButton;
- (id)_videoQualityCategoryID;
- (id)_categoryIdOverride;
- (void)_onSendButton;
- (id)analyticsModule;
- (void)_insertReport:(id)arg1 thumbnail:(id)arg2;
- (id)addAttachmentWithVideoURL:(id)arg1;
- (id)addAttachmentWithUIImage:(id)arg1 windowDescriptionData:(id)arg2;
- (void)addAdHocAttachmentsWithThermalStateMonitor:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (_Bool)prefersNavigationBarHidden;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 reportUploader:(id)arg2 bugReportType:(long long)arg3 crashTaskModel:(id)arg4 captureDelegate:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

