//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBIvarBasedEqualityObject.h"

@class IGRageShakeScreenshotAttachment, NSURL;

@interface IGReportAttachmentType : FBIvarBasedEqualityObject
{
    unsigned long long _subtype;
    NSURL *_videoURLAttachment;
    IGRageShakeScreenshotAttachment *_screenshotAttachment;
}

+ (id)videoURLAttachment:(id)arg1;
+ (id)screenshotAttachment:(id)arg1;
- (void).cxx_destruct;
- (void)matchVideoURLAttachment:(CDUnknownBlockType)arg1 screenshotAttachment:(CDUnknownBlockType)arg2;

@end

