//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGReportPopoverView, UIButton, UILabel;

@protocol IGReportPopoverViewDelegate <NSObject>
- (_Bool)isAttachmentVideoAtIndex:(long long)arg1;
- (void)reportPopoverViewReportDescriptionChange:(IGReportPopoverView *)arg1;
- (void)reportAppUpdatePopoverView:(IGReportPopoverView *)arg1;
- (void)reportPopoverView:(IGReportPopoverView *)arg1 didDeleteImageAtIndex:(long long)arg2;
- (void)reportPopoverView:(IGReportPopoverView *)arg1 didSelectImageAtIndex:(long long)arg2;
- (void)reportPopoverView:(IGReportPopoverView *)arg1 didSelectVideoRecordButton:(UIButton *)arg2;
- (void)reportPopoverView:(IGReportPopoverView *)arg1 didSelectPhotoLibraryButton:(UIButton *)arg2;
- (void)reportPopoverView:(IGReportPopoverView *)arg1 didSelectCaptureButton:(UIButton *)arg2;
- (void)reportPopoverView:(IGReportPopoverView *)arg1 didSelectTaskLabel:(UILabel *)arg2;
@end

