//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "IGCoreTextLinkHandler.h"
#import "IGProfilePictureImageViewDelegate.h"

@class IGCoreTextView, IGFeaturedUserInfo, IGProfilePictureImageView, IGStyledString, NSString;

@interface IGRecommenderProfileCell : UICollectionViewCell <IGCoreTextLinkHandler, IGProfilePictureImageViewDelegate>
{
    IGFeaturedUserInfo *_userInfo;
    NSString *_module;
    IGProfilePictureImageView *_profilePicView;
    IGCoreTextView *_infoLabelView;
    IGStyledString *_lableString;
    id <IGRecommenderProfileCellDelegate> _delegate;
}

+ (id)_infoLabelStringForUsername:(id)arg1;
+ (double)cellHeightForUsername:(id)arg1;
@property(nonatomic) __weak id <IGRecommenderProfileCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)coreTextView:(id)arg1 didLongTapOnString:(id)arg2 URL:(id)arg3;
- (void)coreTextView:(id)arg1 didTapOnString:(id)arg2 URL:(id)arg3;
- (void)profilePictureImageViewImageFailedToLoad:(id)arg1 withURL:(id)arg2;
- (void)profilePictureImageViewImageDidLoad:(id)arg1 profileImage:(id)arg2;
- (void)profilePictureTapped:(id)arg1;
- (void)layoutSubviews;
- (void)configWithFeaturedUserInfo:(id)arg1 userSession:(id)arg2 module:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

