//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGRichTextEmphasis, NSArray, NSShadow, UIColor;

@interface IGRichTextDisplayConfiguration : NSObject
{
    NSArray *_backgroundGradientColors;
    UIColor *_textColor;
    IGRichTextEmphasis *_textEmphasis;
    NSShadow *_customTextShadow;
    long long _gradientDirection;
}

@property(nonatomic) long long gradientDirection; // @synthesize gradientDirection=_gradientDirection;
@property(readonly, nonatomic) NSShadow *customTextShadow; // @synthesize customTextShadow=_customTextShadow;
@property(readonly, nonatomic) IGRichTextEmphasis *textEmphasis; // @synthesize textEmphasis=_textEmphasis;
@property(readonly, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(readonly, copy, nonatomic) NSArray *backgroundGradientColors; // @synthesize backgroundGradientColors=_backgroundGradientColors;
- (void).cxx_destruct;
- (id)initWithBackgroundGradientColors:(id)arg1 textColor:(id)arg2 textEmphasis:(id)arg3 customTextShadow:(id)arg4;
- (id)initWithBackgroundGradientColors:(id)arg1 textColor:(id)arg2 textEmphasis:(id)arg3;

@end

