//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGUserSession, NSDictionary, NSMutableArray, NSString;

@interface IGSaveHomeLogger : NSObject
{
    NSString *_module;
    NSString *_priorModule;
    NSMutableArray *_loggedProductCardImpressions;
    NSDictionary *_defaultCollectionExtras;
    IGUserSession *_userSession;
}

- (void).cxx_destruct;
- (id)_positionForIndex:(long long)arg1 numberOfItemPerRow:(unsigned long long)arg2;
- (void)logProductCardImpressionInShoppingCollectionWithProductItemId:(id)arg1 index:(unsigned long long)arg2 isProductAvailable:(_Bool)arg3 userId:(id)arg4;
- (void)logProductCardClickInShoppingCollectionProductItem:(id)arg1 isProductAvailable:(_Bool)arg2;
- (void)logIndividualCollectionLoadSuccess;
- (void)logCollectionsHomeLoadSuccess;
- (id)initWithModule:(id)arg1 priorModule:(id)arg2 collectionId:(id)arg3 collectionTitle:(id)arg4 userSession:(id)arg5;

@end

