//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGListSectionController.h"

#import "IGListAdapterDataSource.h"
#import "IGMainFeedStoryTrayLoggingContextProvider.h"
#import "IGStoryTraySectionControllerActionDelegate.h"
#import "IGStoryTraySectionControllerViewerDelegate.h"

@class IGAnalyticsNavigationState, IGListAdapter, IGSettingsAdActivityStoryTrayDataSource, IGSettingsAdActivityStoryTrayModel, IGSpinnerLabelViewModel, IGStoryTraySectionController, IGUserSession, NSString, UICollectionView;

@interface IGSettingsAdActivityStoryTraySectionController : IGListSectionController <IGMainFeedStoryTrayLoggingContextProvider, IGStoryTraySectionControllerViewerDelegate, IGStoryTraySectionControllerActionDelegate, IGListAdapterDataSource>
{
    IGUserSession *_userSession;
    IGAnalyticsNavigationState *_navState;
    NSString *_analyticsModule;
    IGSpinnerLabelViewModel *_spinner;
    IGSettingsAdActivityStoryTrayDataSource *_storyTrayDataSource;
    IGSettingsAdActivityStoryTrayModel *_model;
    IGListAdapter *_listAdapter;
    UICollectionView *_collectionView;
    IGStoryTraySectionController *_storyTraySectionController;
    _Bool _hasQueuedUpdate;
    id <IGSettingsAdActivityStoryTraySectionControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <IGSettingsAdActivityStoryTraySectionControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)loggingExtras;
- (id)loggingContext;
- (void)storyTraySectionController:(id)arg1 changedMuteStatusForUser:(id)arg2 changedPostsMuteStatus:(_Bool)arg3 changedStoryMuteStatus:(_Bool)arg4;
- (void)storyTraySectionControllerScrollViewWillScrollNearRight:(id)arg1;
- (void)storyTraySectionControllerViewerDidPublishHighlight:(id)arg1;
- (void)storyTraySectionController:(id)arg1 didDismissViewerWithUnseenItems:(_Bool)arg2 shouldRemainVisible:(_Bool)arg3 addToStoryNUXModel:(id)arg4;
- (void)_setupSpinner;
- (void)_setupCollectionViewAndAdapter;
- (void)didSelectItemAtIndex:(long long)arg1;
- (id)cellForItemAtIndex:(long long)arg1;
- (struct CGSize)sizeForItemAtIndex:(long long)arg1;
- (void)didUpdateToObject:(id)arg1;
- (id)objectsForListAdapter:(id)arg1;
- (id)listAdapter:(id)arg1 sectionControllerForObject:(id)arg2;
- (id)emptyViewForListAdapter:(id)arg1;
- (void)updateWithReels:(id)arg1;
- (id)initWithUserSession:(id)arg1 delegate:(id)arg2 navState:(id)arg3 analyticsModule:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

