//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet;

@interface IGSeenStateObject : NSObject
{
    NSMutableSet *_seenIDs;
    NSMutableDictionary *_viewInfoKeyToViewInfos;
}

@property(readonly, nonatomic) NSMutableDictionary *viewInfoKeyToViewInfos; // @synthesize viewInfoKeyToViewInfos=_viewInfoKeyToViewInfos;
@property(readonly, nonatomic) NSMutableSet *seenIDs; // @synthesize seenIDs=_seenIDs;
- (void).cxx_destruct;
- (id)seenStateObjectData;
- (id)_initWithSeenIDs:(id)arg1 seenStateViewInfos:(id)arg2;
- (id)initWithSeenStateObjectData:(id)arg1;
- (id)init;

@end

