//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IGSearchResultDataModel : NSObject
{
    id _backingModel;
    NSString *_sectionType;
    NSString *_subtitle;
}

+ (id)searchResultDataModelsForSearchObjects:(id)arg1;
@property(readonly, copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, copy, nonatomic) NSString *sectionType; // @synthesize sectionType=_sectionType;
@property(readonly, nonatomic) id backingModel; // @synthesize backingModel=_backingModel;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithBackingModel:(id)arg1 sectionType:(id)arg2 subtitle:(id)arg3;

@end

