//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "IGListDiffable.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class NSString, UIColor;

@interface IGSearchBarConfig : FBValueObject <IGListDiffable, NSCopying, NSCoding>
{
    double _fontSize;
    double _cornerRadius;
    double _barHeight;
    NSString *_placeholder;
    UIColor *_placeholderColor;
    UIColor *_backgroundColor;
    UIColor *_contentViewBackgroundColor;
    UIColor *_textFieldTextColor;
    UIColor *_textFieldTintColor;
    UIColor *_searchIconColor;
    UIColor *_clearIconColor;
    UIColor *_cancelButtonTextColor;
    double _cancelButtonLeftInset;
    double _cancelButtonRightInset;
    long long _rightButtonStyle;
    long long _keyboardAppearance;
    long long _returnKeyType;
    long long _autocorrectionType;
    long long _autocapitalizationType;
    struct UIEdgeInsets _insets;
}

+ (id)searchBarConfigWithStyle:(unsigned long long)arg1;
@property(readonly, nonatomic) long long autocapitalizationType; // @synthesize autocapitalizationType=_autocapitalizationType;
@property(readonly, nonatomic) long long autocorrectionType; // @synthesize autocorrectionType=_autocorrectionType;
@property(readonly, nonatomic) long long returnKeyType; // @synthesize returnKeyType=_returnKeyType;
@property(readonly, nonatomic) long long keyboardAppearance; // @synthesize keyboardAppearance=_keyboardAppearance;
@property(readonly, nonatomic) long long rightButtonStyle; // @synthesize rightButtonStyle=_rightButtonStyle;
@property(readonly, nonatomic) double cancelButtonRightInset; // @synthesize cancelButtonRightInset=_cancelButtonRightInset;
@property(readonly, nonatomic) double cancelButtonLeftInset; // @synthesize cancelButtonLeftInset=_cancelButtonLeftInset;
@property(readonly, copy, nonatomic) UIColor *cancelButtonTextColor; // @synthesize cancelButtonTextColor=_cancelButtonTextColor;
@property(readonly, copy, nonatomic) UIColor *clearIconColor; // @synthesize clearIconColor=_clearIconColor;
@property(readonly, copy, nonatomic) UIColor *searchIconColor; // @synthesize searchIconColor=_searchIconColor;
@property(readonly, copy, nonatomic) UIColor *textFieldTintColor; // @synthesize textFieldTintColor=_textFieldTintColor;
@property(readonly, copy, nonatomic) UIColor *textFieldTextColor; // @synthesize textFieldTextColor=_textFieldTextColor;
@property(readonly, copy, nonatomic) UIColor *contentViewBackgroundColor; // @synthesize contentViewBackgroundColor=_contentViewBackgroundColor;
@property(readonly, copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(readonly, copy, nonatomic) UIColor *placeholderColor; // @synthesize placeholderColor=_placeholderColor;
@property(readonly, copy, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;
@property(readonly, nonatomic) struct UIEdgeInsets insets; // @synthesize insets=_insets;
@property(readonly, nonatomic) double barHeight; // @synthesize barHeight=_barHeight;
@property(readonly, nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(readonly, nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
- (void).cxx_destruct;
- (id)initWithFontSize:(double)arg1 cornerRadius:(double)arg2 barHeight:(double)arg3 insets:(struct UIEdgeInsets)arg4 placeholder:(id)arg5 placeholderColor:(id)arg6 backgroundColor:(id)arg7 contentViewBackgroundColor:(id)arg8 textFieldTextColor:(id)arg9 textFieldTintColor:(id)arg10 searchIconColor:(id)arg11 clearIconColor:(id)arg12 cancelButtonTextColor:(id)arg13 cancelButtonLeftInset:(double)arg14 cancelButtonRightInset:(double)arg15 rightButtonStyle:(long long)arg16 keyboardAppearance:(long long)arg17 returnKeyType:(long long)arg18 autocorrectionType:(long long)arg19 autocapitalizationType:(long long)arg20;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;

@end

