//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGListDiffable.h"

@class IGSearchLoadingItemViewModelConfiguration, NSString;

@interface IGSearchLoadingItemViewModel : NSObject <IGListDiffable>
{
    NSString *_query;
    IGSearchLoadingItemViewModelConfiguration *_configuration;
}

+ (id)viewModelWithQuery:(id)arg1;
@property(readonly, nonatomic) IGSearchLoadingItemViewModelConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, copy, nonatomic) NSString *query; // @synthesize query=_query;
- (void).cxx_destruct;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (id)description;
- (id)initWithQuery:(id)arg1 configuration:(id)arg2;

@end

