//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGGroupedTableViewController.h"

#import "IGBusinessFacebookPageClaimServiceDelegate.h"
#import "IGConnectExistingPageFlowDelegate.h"
#import "IGInAppBadgeListener.h"
#import "IGSettingsSearch.h"

@class IG4BLogger, IGBusinessConversionFacebookPageDataSource, IGBusinessFacebookPageClaimService, IGSettingsBusinessModel, IGUserSession, NSString;

@interface IGSettingsBusinessViewController : IGGroupedTableViewController <IGBusinessFacebookPageClaimServiceDelegate, IGInAppBadgeListener, IGConnectExistingPageFlowDelegate, IGSettingsSearch>
{
    id _paymentsNotificationObserver;
    IGUserSession *_userSession;
    IGBusinessFacebookPageClaimService *_pageClaimService;
    IGBusinessConversionFacebookPageDataSource *_facebookPageDataSource;
    IGSettingsBusinessModel *_businessModel;
    IG4BLogger *_pageClaimLogger;
}

@property(retain, nonatomic) IG4BLogger *pageClaimLogger; // @synthesize pageClaimLogger=_pageClaimLogger;
- (void).cxx_destruct;
- (id)analyticsModule;
- (void)inAppBadgeManagerRequiredActionCountDidUpdate;
- (void)connectExistingPageFlow:(id)arg1 didSwitchToPage:(id)arg2;
- (void)_handleFacebookPageInfoFetched:(id)arg1;
- (void)_updateUserPageInfoWithPageID:(id)arg1 logger:(id)arg2;
- (id)_createPageClaimLoggerForFBUserID:(id)arg1;
- (void)_createPageWithFBAccessToken:(id)arg1 claimPageLogger:(id)arg2;
- (void)_claimPageWithFBAccessToken:(id)arg1 claimPageLogger:(id)arg2;
- (void)_loginFacebookWithSuccessHandler:(CDUnknownBlockType)arg1;
- (void)_pageClaimCompletedHandler:(id)arg1 error:(id)arg2 fbAccessToken:(id)arg3 logger:(id)arg4;
- (void)businessFacebookPageClaimServiceDidSelectCreatePage:(id)arg1;
- (void)businessFacebookPageClaimServiceDidSelectConnectToExistingPage:(id)arg1;
- (void)businessFacebookPageClaimServiceDidSelectDismiss:(id)arg1;
- (void)businessFacebookPageClaimServiceDidSelectClaimPage:(id)arg1;
- (void)_pushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)_configureBusinessCell:(id)arg1 forRow:(long long)arg2;
- (void)performActionForBusinessRowType:(long long)arg1;
- (void)performActionForSearchText:(id)arg1 tableView:(id)arg2 indexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (struct UIEdgeInsets)preferredContentInsets;
- (void)_prepareAppearance;
- (void)_didTapBackButton:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 model:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

