//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGSearchAnalyticsLogger, IGSearchSession, NSDate, NSError, NSString, UIScrollView;

@protocol IGSearchChildViewControllerTypeDelegate
- (void)searchChildViewControllerDidFailToLoadNullStateResults:(id)arg1 error:(NSError *)arg2;
- (void)searchChildViewControllerDidLoadNullStateResults:(id)arg1;
- (void)searchChildViewControllerWillLoadNullStateResults:(id)arg1;
- (void)searchChildViewControllerDidTapOnSearchResult:(id)arg1;
- (void)scrollViewDidScroll:(UIScrollView *)arg1;
- (void)childViewControllerWillPushView:(id <IGSearchChildViewControllerType>)arg1;
- (void)childViewController:(id <IGSearchChildViewControllerType>)arg1 pushedTimeDidChange:(NSDate *)arg2;
- (_Bool)isReadyForImpressionLogging;
- (IGSearchSession *)searchSession;
- (NSString *)querySessionId;
- (IGSearchAnalyticsLogger *)searchAnalyticsLogger;
- (NSString *)currentSearchText;
@end

