//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGMediaMetadata, IGShareListManager, IGUserSession, NSString, UIScrollView, UIView, UIViewController<IGAnalyticsModule>;

@protocol IGShareManager <NSObject>
@property(nonatomic) __weak UIViewController<IGAnalyticsModule> *delegate;
@property(readonly, nonatomic) UIScrollView *scrollView;
@property(readonly, nonatomic) _Bool isReadyToShare;
@property(copy, nonatomic) NSString *shareString;
- (void)configureWithHeaderView:(UIView *)arg1;
- (id)initWithMediaMetadata:(IGMediaMetadata *)arg1 shareListManager:(IGShareListManager *)arg2 userSession:(IGUserSession *)arg3;
@end

