//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UICollectionView;

@interface IGShoppingShelfCell : UICollectionViewCell
{
    UICollectionView *_collectionView;
    id <IGShoppingShelfCellDelegate> _delegate;
}

+ (long long)height;
@property(nonatomic) __weak id <IGShoppingShelfCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)scrollToItemAtIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)configureWithCollectionViewDelegate:(id)arg1 collectionViewData:(id)arg2;
- (void)_registerSubCells;
- (id)_collectionViewLayout;
- (void)_setUpCollectionViewWithFrame:(struct CGRect)arg1;
- (void)setPercentVisible:(double)arg1;
- (void)shoppingShelfCellDidDisappear;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

