//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "IGJSONCoding.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class NSString;

@interface IGShoppingPDPSectionSpacingSpec : FBValueObject <IGJSONCoding, NSCopying, NSCoding>
{
    _Bool _displayTopSeparator;
    _Bool _displayBottomSeparator;
    double _topPadding;
    double _bottomPadding;
}

+ (id)valueWithJSONDictionary:(id)arg1 error:(id *)arg2;
@property(readonly, nonatomic) double bottomPadding; // @synthesize bottomPadding=_bottomPadding;
@property(readonly, nonatomic) double topPadding; // @synthesize topPadding=_topPadding;
@property(readonly, nonatomic) _Bool displayBottomSeparator; // @synthesize displayBottomSeparator=_displayBottomSeparator;
@property(readonly, nonatomic) _Bool displayTopSeparator; // @synthesize displayTopSeparator=_displayTopSeparator;
- (id)toJsonDictionary;
- (id)initWithDisplayTopSeparator:(_Bool)arg1 displayBottomSeparator:(_Bool)arg2 topPadding:(double)arg3 bottomPadding:(double)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

