//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGShoppingPurchaseProtectionViewControllerDelegate.h"

@class IGPartialModalSheetViewController, IGUserSession, NSString, UIViewController;

@interface IGShoppingPurchaseProtectionPresentationManager : NSObject <IGShoppingPurchaseProtectionViewControllerDelegate>
{
    UIViewController *_rootViewController;
    IGUserSession *_userSession;
    IGPartialModalSheetViewController *_modalSheetVC;
}

- (void).cxx_destruct;
- (void)presentPurchaseProtectionViewControllerWithRootViewController:(id)arg1;
- (void)purchaseProtectionViewControllerDidUpdateContent:(id)arg1;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

