//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class IGShoppingFeedNetworkRequestConfiguration, NSError, NSString;

@interface IGShoppingFeedNetworkFetchState : FBValueObject <NSCopying, NSCoding>
{
    _Bool _hasLoadedOnce;
    long long _status;
    IGShoppingFeedNetworkRequestConfiguration *_activeRequestConfiguration;
    NSError *_error;
    NSString *_errorMessage;
}

@property(readonly, copy, nonatomic) NSString *errorMessage; // @synthesize errorMessage=_errorMessage;
@property(readonly, copy, nonatomic) NSError *error; // @synthesize error=_error;
@property(readonly, nonatomic) _Bool hasLoadedOnce; // @synthesize hasLoadedOnce=_hasLoadedOnce;
@property(readonly, copy, nonatomic) IGShoppingFeedNetworkRequestConfiguration *activeRequestConfiguration; // @synthesize activeRequestConfiguration=_activeRequestConfiguration;
@property(readonly, nonatomic) long long status; // @synthesize status=_status;
- (void).cxx_destruct;
- (id)initWithStatus:(long long)arg1 activeRequestConfiguration:(id)arg2 hasLoadedOnce:(_Bool)arg3 error:(id)arg4 errorMessage:(id)arg5;

@end

