//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGShoppingFeedNetworkerDelegate.h"
#import "IGTaggingSearchDataSource.h"

@class IGShoppingFeedNetworker, IGShoppingProductTaggingDataModel, IGUserSession, NSString;

@interface IGShoppingProductSearchDataSource : NSObject <IGShoppingFeedNetworkerDelegate, IGTaggingSearchDataSource>
{
    IGUserSession *_userSession;
    unsigned long long _productSourceType;
    IGShoppingFeedNetworker *_networker;
    IGShoppingProductTaggingDataModel *_dataModel;
    NSString *_selectedSourcePk;
    NSString *_query;
    id <IGTaggingSearchDataSourceDelegate> _delegate;
}

@property(nonatomic) __weak id <IGTaggingSearchDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_requestFeedWithAction:(long long)arg1 isPullToRefresh:(_Bool)arg2;
- (void)feedNetworker:(id)arg1 didLoadResponse:(id)arg2 requestConfiguration:(id)arg3;
- (void)feedNetworker:(id)arg1 didUpdateFetchState:(id)arg2;
- (_Bool)isLoading;
- (id)filteredResults;
- (void)tryLoadingMoreResults;
- (void)filterWithQuery:(id)arg1;
- (id)initWithUserSession:(id)arg1 productSourceType:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

