//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"

@class NSString, UIColor, UIViewController<IGSlideshowFeedPreviewPresentable>, UIViewController<IGSlideshowFeedPreviewPresenter>;

@interface IGSlideshowFeedPreviewPresentationAnimationController : NSObject <UIViewControllerAnimatedTransitioning>
{
    UIViewController<IGSlideshowFeedPreviewPresenter> *_presenter;
    UIViewController<IGSlideshowFeedPreviewPresentable> *_presentable;
    UIColor *_backgroundColor;
    double _progressForSecondPhase;
    _Bool _isPresenting;
}

- (void).cxx_destruct;
- (void)_animateDismissalTransition:(id)arg1;
- (void)_animatePresentationTransition:(id)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (id)initWithPresenter:(id)arg1 presentable:(id)arg2 progressForSecondPhase:(double)arg3 isPresenting:(_Bool)arg4 backgroundColor:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

