//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGSlideshowNUXView;

@protocol IGSlideshowConfigurationType <NSObject>
- (_Bool)scrubberCanBeScrolledFromAnywhere;
- (_Bool)showPageIndicator;
- (long long)closeButtonLocation;
- (_Bool)showCloseButton;
- (_Bool)fullHeightTapTargets;
- (IGSlideshowNUXView *)nuxViewWithSize:(struct CGSize)arg1;
- (_Bool)shouldUseSafeAreaInsets;
- (CDStruct_b4323d61)scrubberConfiguration;
- (_Bool)shouldShowHeaderView;
@end

