//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGUserSession, NSString;

@interface IGSlideshowLogger : NSObject
{
    NSString *_analyticsModule;
    IGUserSession *_userSession;
}

- (void).cxx_destruct;
- (void)_logEvent:(id)arg1 extras:(id)arg2;
- (void)logDismissedWithExitPoint:(long long)arg1 itemIndex:(long long)arg2;
- (void)logViewedCommentsWithFeedItem:(id)arg1 itemIndex:(long long)arg2 entryPoint:(long long)arg3 isInline:(_Bool)arg4;
- (void)logNavigatedToItem:(id)arg1 atItemIndex:(long long)arg2 itemMediaIndex:(long long)arg3 fromItemIndex:(long long)arg4 fromItemMediaIndex:(long long)arg5 method:(long long)arg6 gestureLocationInfo:(id)arg7;
- (void)logContentAreaGesture:(long long)arg1 withItem:(id)arg2 locationInfo:(id)arg3 itemIndex:(long long)arg4 action:(long long)arg5;
- (id)initWithAnalyticsModule:(id)arg1 userSession:(id)arg2;

@end

