//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGSliderStickerView;

@protocol IGSliderStickerViewDelegate <NSObject>
- (void)sliderStickerViewDidReceiveTapOnEmoji:(IGSliderStickerView *)arg1;
- (void)sliderStickerView:(IGSliderStickerView *)arg1 didEndSlidingEmojiWithValue:(double)arg2 inStickerViewMode:(long long)arg3;
- (void)sliderStickerViewDidBeginSlidingEmoji:(IGSliderStickerView *)arg1;
- (void)sliderStickerViewDidChangeText:(IGSliderStickerView *)arg1;
@end

