//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGSlideshowGestureHandler.h"

@interface IGSlideshowGestureHandlerNoSingleTap : NSObject <IGSlideshowGestureHandler>
{
    long long _likeGesture;
}

- (_Bool)handlesGesture:(long long)arg1 atNormalizedLocation:(struct CGPoint)arg2;
- (long long)actionForGesture:(long long)arg1 atNormalizedLocation:(struct CGPoint)arg2;
- (id)initWithLikeGesture:(long long)arg1;

@end

