//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "IGStoryCameraModeSwitcherItem.h"

@class NSString, UILabel;

@interface IGStoryCameraModeCell : UICollectionViewCell <IGStoryCameraModeSwitcherItem>
{
    _Bool _topAligned;
    UILabel *_label;
}

+ (double)contentWidthForText:(id)arg1 constrainedSize:(struct CGSize)arg2;
@property(readonly, nonatomic) UILabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (void)setFocused:(_Bool)arg1;
- (void)configureWithTitle:(id)arg1 topAligned:(_Bool)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

