//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton, UIImageView, UILabel;

@interface IGStoryViewersExpiredUpsellView : UIView
{
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
    UIButton *_actionButton;
    long long _viewType;
    double _bottomInset;
    id <IGStoryViewersExpiredUpsellViewDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_actionTapped:(id)arg1;
- (void)layoutSubviews;
- (id)initWithType:(long long)arg1 reelTitle:(id)arg2 bottomInset:(double)arg3 delegate:(id)arg4;

@end

