//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGTapButton;

@protocol IGStoryPreviewFooterViewType <NSObject>
@property(nonatomic) _Bool isShareToFacebookShortCutEnabled;
@property(readonly, nonatomic) IGTapButton *sendButton;
@property(readonly, nonatomic) IGTapButton *storyButton;
@property(nonatomic) __weak id <IGStoryPreviewFooterViewDelegate> delegate;
- (_Bool)shoulAdjustOffsetFromMediaView;
- (_Bool)isShowingDownloadButton;
- (void)setButtonsEnabled:(_Bool)arg1;
@end

