//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class IGGradientView, IGRemoteImageView, NSURL, UIImage, UIImageView, UILabel;

@interface IGStoryCarouselCell : UICollectionViewCell
{
    _Bool _hasError;
    _Bool _hideViewerCount;
    long long _viewerCount;
    NSURL *_imageURL;
    UIImage *_preloadedImage;
    IGRemoteImageView *_imageView;
    IGGradientView *_bottomGradient;
    UIImageView *_eyeImageView;
    UILabel *_viewersLabel;
}

@property(readonly, nonatomic) UILabel *viewersLabel; // @synthesize viewersLabel=_viewersLabel;
@property(readonly, nonatomic) UIImageView *eyeImageView; // @synthesize eyeImageView=_eyeImageView;
@property(readonly, nonatomic) IGGradientView *bottomGradient; // @synthesize bottomGradient=_bottomGradient;
@property(readonly, nonatomic) IGRemoteImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIImage *preloadedImage; // @synthesize preloadedImage=_preloadedImage;
@property(readonly, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(nonatomic) _Bool hideViewerCount; // @synthesize hideViewerCount=_hideViewerCount;
@property(nonatomic) long long viewerCount; // @synthesize viewerCount=_viewerCount;
@property(nonatomic) _Bool hasError; // @synthesize hasError=_hasError;
- (void).cxx_destruct;
- (void)setImageURL:(id)arg1 module:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

