//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "IGListDiffable.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class IGStorySuggestionUnit, NSArray;

@interface IGStorySuggestionUnitViewModel : FBValueObject <IGListDiffable, NSCopying, NSCoding>
{
    IGStorySuggestionUnit *_suggestionUnit;
    NSArray *_trayViewModels;
}

@property(readonly, copy, nonatomic) NSArray *trayViewModels; // @synthesize trayViewModels=_trayViewModels;
@property(readonly, copy, nonatomic) IGStorySuggestionUnit *suggestionUnit; // @synthesize suggestionUnit=_suggestionUnit;
- (void).cxx_destruct;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (id)initWithSuggestionUnit:(id)arg1 trayViewModels:(id)arg2;

@end

