//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGReel, IGStoryDataController, NSError, NSString;

@protocol IGStoryDataControllerStoryMediaPreviewListener
- (void)storyDataController:(IGStoryDataController *)arg1 didReturnNoMediaPreviewForReelPK:(NSString *)arg2 refreshType:(long long)arg3 updateDuration:(double)arg4;
- (void)storyDataController:(IGStoryDataController *)arg1 fetchMediaPreviewDidFailForReelPK:(NSString *)arg2 error:(NSError *)arg3 refreshType:(long long)arg4 updateDuration:(double)arg5;
- (void)storyDataController:(IGStoryDataController *)arg1 didFetchMediaPreviewForReel:(IGReel *)arg2 refreshType:(long long)arg3 updateDuration:(double)arg4;
@end

