//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGStoryExtendedGalleryViewController, NSArray;

@protocol IGStoryExtendedGalleryViewControllerDelegate <NSObject>
- (_Bool)prefersStatusBarHidden;
- (void)extendedGalleryViewController:(IGStoryExtendedGalleryViewController *)arg1 didSelectAssets:(NSArray *)arg2;
@end

