//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGStyledString.h"

@interface IGStyledString (DirectTextMessage)
+ (id)styledStringFromTitle:(id)arg1 text:(id)arg2 textCheckingTypes:(unsigned long long)arg3 isOnlyEmoji:(_Bool)arg4 shouldDisableLinks:(_Bool)arg5 reelOwner:(id)arg6 stringStyles:(id)arg7;
@end

