//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIGestureRecognizer;

@protocol IGStoryCTAInteractionControllerDelegate <NSObject>
- (_Bool)storyCTAInteractionControllerShouldUseDismissGesture:(UIGestureRecognizer *)arg1 inDirection:(unsigned long long)arg2;
- (void)storyCTAInteractionControllerDidBeginInteraction;
@end

