//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "IGJSONCoding.h"
#import "IGLoadMoreResponseType.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class NSArray, NSString;

@interface IGStoryBrushResponse : FBValueObject <IGLoadMoreResponseType, IGJSONCoding, NSCopying, NSCoding>
{
    NSString *_versionID;
    NSArray *_brushes;
}

+ (id)valueWithJSONDictionary:(id)arg1 error:(id *)arg2;
@property(readonly, copy, nonatomic) NSArray *brushes; // @synthesize brushes=_brushes;
@property(readonly, copy, nonatomic) NSString *versionID; // @synthesize versionID=_versionID;
- (void).cxx_destruct;
- (id)initWithVersionID:(id)arg1 brushes:(id)arg2;
- (id)maxId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

