//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableOrderedSet;

@interface IGStoryViewersDataSource : NSObject
{
    NSMutableArray *_viewers;
    NSMutableOrderedSet *_viewerIDs;
    _Bool _isExpired;
}

@property(nonatomic) _Bool isExpired; // @synthesize isExpired=_isExpired;
- (void).cxx_destruct;
- (void)insertViewer:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addViewer:(id)arg1;
- (id)storyViewers;
- (id)init;

@end

