//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGBackgroundTask.h"

@class IGFileCoordinator, IGRequestToken, IGUserSession, NSString;

@interface IGStoryAPIBackgroundFetchTask : NSObject <IGBackgroundTask>
{
    IGUserSession *_userSession;
    IGFileCoordinator *_cachedTrayFileCoordinator;
    IGRequestToken *_token;
    _Bool _shouldCacheAPIResponse;
    CDUnknownBlockType _completionHandler;
    id <IGStoryAPIBackgroundFetchTaskDelegate> _delegate;
}

@property(nonatomic) __weak id <IGStoryAPIBackgroundFetchTaskDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cancel;
- (void)executeWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithUserSession:(id)arg1 shouldCacheAPIResponse:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

