//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGListSectionController.h"

#import "IGListDisplayDelegate.h"
#import "IGStorySectionControllerType.h"

@class IGStorySuggestionUnitViewModel, NSString;

@interface IGStoryTraySuggestionCardSectionController : IGListSectionController <IGStorySectionControllerType, IGListDisplayDelegate>
{
    IGStorySuggestionUnitViewModel *_model;
    struct CGSize _cellSize;
    id <IGStoryTraySuggestionCardSectionControllerDelegate> _delegate;
    double _percentCollapsed;
    id <IGStorySectionCollapsibleControllerDataSource> _dataSourceDelegate;
}

@property(nonatomic) __weak id <IGStorySectionCollapsibleControllerDataSource> dataSourceDelegate; // @synthesize dataSourceDelegate=_dataSourceDelegate;
@property(nonatomic) double percentCollapsed; // @synthesize percentCollapsed=_percentCollapsed;
- (void).cxx_destruct;
- (id)_visibleSuggestionsCardCell;
- (void)setPercentCollapsed:(double)arg1 withCellSize:(struct CGSize)arg2;
- (void)updateCellSize:(struct CGSize)arg1;
- (void)configureWithInitialCellSize:(struct CGSize)arg1;
- (void)listAdapter:(id)arg1 didEndDisplayingSectionController:(id)arg2 cell:(id)arg3 atIndex:(long long)arg4;
- (void)listAdapter:(id)arg1 willDisplaySectionController:(id)arg2 cell:(id)arg3 atIndex:(long long)arg4;
- (void)listAdapter:(id)arg1 didEndDisplayingSectionController:(id)arg2;
- (void)listAdapter:(id)arg1 willDisplaySectionController:(id)arg2;
- (void)didSelectItemAtIndex:(long long)arg1;
- (void)didUpdateToObject:(id)arg1;
- (id)cellForItemAtIndex:(long long)arg1;
- (struct CGSize)sizeForItemAtIndex:(long long)arg1;
- (long long)numberOfItems;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

