//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGBouncyCollectionViewCell.h"

@class IGStoryMusicBrowserDisclosureIndicator, IGStoryMusicBrowserRoundedImageView, NSString, NSURL, UIImage, UILabel;

@interface IGStoryMusicBrowserGenreCell : IGBouncyCollectionViewCell
{
    IGStoryMusicBrowserRoundedImageView *_albumArtImageView;
    UILabel *_genreTitleLabel;
    IGStoryMusicBrowserDisclosureIndicator *_disclosureIndicator;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *genreTitle;
@property(retain, nonatomic) NSURL *albumArtURL;
@property(retain, nonatomic) UIImage *albumArtImage;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

