//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGStoryTrayCollectionViewConfiguration, IGStoryTraySectionHeaderConfiguration;

@interface IGStoryTraySectionConfiguration : NSObject
{
    _Bool _prefetchVisibleItemsOnDisplay;
    _Bool _prefetchItemsOnScroll;
    _Bool _supportsCollapsibleTray;
    _Bool _isIndexInReverseOrder;
    IGStoryTrayCollectionViewConfiguration *_collectionViewConfig;
    IGStoryTraySectionHeaderConfiguration *_headerConfig;
    long long _numberOfNeighborsToFetch;
}

+ (id)_feedTrayConfigurationWithCollectionViewConfig:(id)arg1 headerConfig:(id)arg2 trayCellStyle:(long long)arg3;
+ (id)directAppStatusTrayConfiguration;
+ (id)relatedHashtagStoriesTrayConfiguration;
+ (id)storiesBrowsingGridConfigurationWithSupportsMuting:(_Bool)arg1;
+ (id)trayInViewerTrayConfigurationWithSupportsMuting:(_Bool)arg1;
+ (id)suggestedHighlightsTrayConfiguration;
+ (id)highlightsInFeedUnitConfigWithTitle:(id)arg1 subtitle:(id)arg2 actionButtonTitle:(id)arg3;
+ (id)localBusinessTrayConfiguration;
+ (id)profileSuggestedHighlightsTrayConfigurationWithBackgroundColor:(id)arg1 hasBottomBorder:(_Bool)arg2 bottomInset:(double)arg3 leftPadding:(double)arg4;
+ (id)profileHighlightsTrayConfigurationWithBackgroundColor:(id)arg1 hasBottomBorder:(_Bool)arg2 bottomInset:(double)arg3 leftPadding:(double)arg4;
+ (id)suggestionUnitTrayConfigurationWithTitle:(id)arg1;
+ (id)_inFeedUnitTrayConfigurationWithHeaderConfig:(id)arg1 trayCellStyle:(long long)arg2;
+ (id)_inFeedUnitTrayConfigurationWithHeaderConfig:(id)arg1;
+ (id)inFeedUnitTrayConfigurationWithTitle:(id)arg1;
+ (id)inFeedUnitTrayConfiguration;
+ (id)adActivityTrayConfiguration;
+ (id)exploreFeedStoryTrayConfiguration;
+ (id)minimizedStoryTrayConfiguration;
+ (id)mainFeedStoryTrayConfiguration:(id)arg1;
@property(nonatomic) _Bool isIndexInReverseOrder; // @synthesize isIndexInReverseOrder=_isIndexInReverseOrder;
@property(nonatomic) _Bool supportsCollapsibleTray; // @synthesize supportsCollapsibleTray=_supportsCollapsibleTray;
@property(nonatomic) long long numberOfNeighborsToFetch; // @synthesize numberOfNeighborsToFetch=_numberOfNeighborsToFetch;
@property(nonatomic) _Bool prefetchItemsOnScroll; // @synthesize prefetchItemsOnScroll=_prefetchItemsOnScroll;
@property(nonatomic) _Bool prefetchVisibleItemsOnDisplay; // @synthesize prefetchVisibleItemsOnDisplay=_prefetchVisibleItemsOnDisplay;
@property(readonly, nonatomic) IGStoryTraySectionHeaderConfiguration *headerConfig; // @synthesize headerConfig=_headerConfig;
@property(readonly, nonatomic) IGStoryTrayCollectionViewConfiguration *collectionViewConfig; // @synthesize collectionViewConfig=_collectionViewConfig;
- (void).cxx_destruct;
- (long long)trayIndex:(id)arg1;
- (long long)headerIndex:(id)arg1;
- (_Bool)showHeaderCell:(id)arg1;
@property(readonly, nonatomic) _Bool hasHeader;
- (id)initWithCollectionViewConfig:(id)arg1 headerConfig:(id)arg2;

@end

