//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGStoryNetegoViewDelegate.h"

@class IGStoryNetegoModel, IGUserSession;

@interface IGStoryNetegoManager : NSObject <IGStoryNetegoViewDelegate>
{
    IGUserSession *_userSession;
    IGStoryNetegoModel *_storyNetegoModel;
    unsigned long long _netegoCellState;
}

@property(nonatomic) unsigned long long netegoCellState; // @synthesize netegoCellState=_netegoCellState;
- (void).cxx_destruct;
- (unsigned long long)getCurrentStoryNetegoCellState;
- (_Bool)canOpenCTA;
- (id)generatedIntentTargetWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)fullScreenSectionControllerDidEndDisplaying;
- (void)configureWithStoryNetegoModel:(id)arg1;
- (id)initWithUserSession:(id)arg1;

@end

