//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGPassthroughView.h"

#import "IGStoryCameraDirectCenterHeaderViewDelegate.h"
#import "IGStoryCameraHeaderViewType.h"

@class IGAREffectAttributionPillView, IGStackView, IGStoryCameraDirectCenterHeaderView, IGStoryCameraDirectHeaderViewConfig, IGTapButton, NSString, UIControl;

@interface IGStoryCameraDirectHeaderView : IGPassthroughView <IGStoryCameraDirectCenterHeaderViewDelegate, IGStoryCameraHeaderViewType>
{
    IGStoryCameraDirectHeaderViewConfig *_config;
    IGStoryCameraDirectCenterHeaderView *_centerHeaderView;
    IGTapButton *_closeButton;
    IGStackView *_topControlsView;
    IGPassthroughView *_controlsView;
    IGAREffectAttributionPillView *_arEffectAttributionView;
    UIControl *_muteButton;
    id <IGStoryCameraHeaderViewDelegate> _delegate;
}

@property(nonatomic) __weak id <IGStoryCameraHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIControl *muteButton; // @synthesize muteButton=_muteButton;
@property(readonly, nonatomic) IGAREffectAttributionPillView *arEffectAttributionView; // @synthesize arEffectAttributionView=_arEffectAttributionView;
- (void).cxx_destruct;
- (void)cameraDirectCenterHeaderViewDidTap:(id)arg1;
- (void)_muteButtonTapped;
- (void)_closeButtonTapped;
- (void)_showCenterHeader:(_Bool)arg1 withTransitionDuration:(double)arg2;
- (void)addTopControl:(id)arg1;
- (void)setMuteButtonState:(_Bool)arg1;
- (void)setMuteButtonHidden:(_Bool)arg1;
- (void)hideCloseView:(_Bool)arg1;
- (void)hideAllViewsExceptClose:(_Bool)arg1;
- (void)hideAllViewsExceptTopControls:(_Bool)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutIfNeeded;
- (void)setNeedsLayout;
- (id)initWithConfig:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

