//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface IGStoryMediaExportOptions : NSObject
{
    _Bool _shouldShareToCloseFriends;
    _Bool _shouldShareToFB;
}

@property(readonly, nonatomic) _Bool shouldShareToFB; // @synthesize shouldShareToFB=_shouldShareToFB;
@property(readonly, nonatomic) _Bool shouldShareToCloseFriends; // @synthesize shouldShareToCloseFriends=_shouldShareToCloseFriends;
- (id)initWithShouldShareToCloseFriends:(_Bool)arg1 shouldShareToFB:(_Bool)arg2;

@end

