//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGStoryTrayCell.h"

@interface IGStoryTrayNuxCell : IGStoryTrayCell
{
}

- (_Bool)presentationAnimationNeedsCrossfade;
- (id)presentationAnimationToView;
- (id)presentationAnimationFromView;
- (id)profilePictureView;
- (void)setShowError:(_Bool)arg1;
- (void)setLoading:(_Bool)arg1;
- (void)configureWithViewModel:(id)arg1;
- (void)didMoveToWindow;

@end

