//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIView, UIViewController<IGPresentableStoryViewer>;

@protocol IGStoryViewerPresentationAnimationProtocol <NSObject>
- (void)configureWithProfileImageView:(UIView *)arg1 viewer:(UIViewController<IGPresentableStoryViewer> *)arg2 isPresenting:(_Bool)arg3 presentingFromView:(UIView *)arg4 dismissingToView:(UIView *)arg5 shouldFadeInProfileImageView:(_Bool)arg6 shouldScaleTransformToView:(_Bool)arg7 shouldCrossFadeOnTransformAnimation:(_Bool)arg8;
- (void)configureWithProfileImageView:(UIView *)arg1 viewer:(UIViewController<IGPresentableStoryViewer> *)arg2 isPresenting:(_Bool)arg3;
@end

