//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGStoryStickerViewControllerNavigationDelegate.h"
#import "IGStoryStickerViewControllerScrollDelegate.h"
#import "IGStoryStickerViewControllerSelectionDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class IGDirectionalPanGestureRecognizer, IGStoryStickerViewController, IGUserSession, NSArray, NSString, UIButton, UIView, UIVisualEffectView;

@interface IGStoryStickerSingleTabViewController : IGViewController <IGStoryStickerViewControllerSelectionDelegate, IGStoryStickerViewControllerNavigationDelegate, IGStoryStickerViewControllerScrollDelegate, UIGestureRecognizerDelegate>
{
    IGUserSession *_userSession;
    NSArray *_items;
    unsigned long long _state;
    IGStoryStickerViewController *_stickerVC;
    UIVisualEffectView *_blurEffectView;
    UIButton *_chevronView;
    UIView *_trayContainerView;
    double _initialY;
    IGDirectionalPanGestureRecognizer *_panGesture;
    id <IGStoryStickerSingleTabViewControllerStickerSelectionDelegate> _stickerSelectionDelegate;
}

@property(nonatomic) __weak id <IGStoryStickerSingleTabViewControllerStickerSelectionDelegate> stickerSelectionDelegate; // @synthesize stickerSelectionDelegate=_stickerSelectionDelegate;
- (void).cxx_destruct;
- (void)stickerViewController:(id)arg1 scrollViewDidScroll:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectFundraiserStickerTrayModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectCountdownHomeWithStickerTrayModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectMusicStickerModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectProductStickerModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectGalleryStickerModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectGIFSearchStickerModel:(id)arg2;
- (void)stickerViewController:(id)arg1 wantsDismissAnimated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)stickerViewController:(id)arg1 didSelectCountdownStickerTrayModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectMusicTrack:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectQuizStickerTrayModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectQuestionAnswerStickerModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectSliderStickerModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectMentionStickerModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectHashtagStickerModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectInternalStickerModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectGalleryVideoSticker:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectGalleryImageSticker:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectCameraStickerModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectLocationStickerModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectMemoriesSticker:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectDateSticker:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectTimeStickerModel:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectAnimatedSticker:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectStaticSticker:(id)arg2;
- (void)stickerViewController:(id)arg1 didSelectEmoji:(id)arg2;
- (void)stickerViewControllerDidSelectLike:(id)arg1;
- (void)stickerViewController:(id)arg1 didSelectPollStickerModel:(id)arg2;
- (void)_handlePan:(id)arg1;
- (void)_setupPanGesture;
- (void)_setState:(unsigned long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_setState:(unsigned long long)arg1 animated:(_Bool)arg2;
- (double)_trayContainerViewOriginYWithState:(unsigned long long)arg1;
- (void)_updateBottomInset;
- (double)_initialPaddingForContainerView;
- (void)_didTapChevronButton:(id)arg1;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (id)analyticsModule;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 items:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

