//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIViewController<IGStoryCreationDrawingViewControllerType>;

@protocol IGStoryCreationDrawingViewControllerDelegate <NSObject>
- (void)drawingViewControllerFinishedSelectingColorFromScreen:(UIViewController<IGStoryCreationDrawingViewControllerType> *)arg1;
- (void)drawingViewControllerBeganSelectingColorFromScreen:(UIViewController<IGStoryCreationDrawingViewControllerType> *)arg1;
- (void)drawingViewControllerDidDismiss:(UIViewController<IGStoryCreationDrawingViewControllerType> *)arg1;
- (void)drawingViewControllerDidBeginEditing:(UIViewController<IGStoryCreationDrawingViewControllerType> *)arg1;
@end

