//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGBouncyCollectionViewCell.h"

@class IGRadioButtonView, IGStoryMusicBrowserSongCellContentView, NSString, NSURL, UIImage;

@interface IGStoryMusicBrowserSongCell : IGBouncyCollectionViewCell
{
    IGStoryMusicBrowserSongCellContentView *_songContentView;
    IGRadioButtonView *_selectedView;
    _Bool _markedSelected;
    id <IGStoryMusicBrowserSongCellDelegate> _delegate;
    unsigned long long _selectionStyle;
}

@property(nonatomic, getter=isMarkedSelected) _Bool markedSelected; // @synthesize markedSelected=_markedSelected;
@property(nonatomic) unsigned long long selectionStyle; // @synthesize selectionStyle=_selectionStyle;
@property(nonatomic) __weak id <IGStoryMusicBrowserSongCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_didTapPlayPauseButton:(id)arg1;
@property(nonatomic) double playbackProgress;
@property(nonatomic, getter=isStalled) _Bool stalled;
@property(nonatomic, getter=isPlaying) _Bool playing;
@property(nonatomic) _Bool isExplicit;
@property(copy, nonatomic) NSString *artistName;
@property(copy, nonatomic) NSString *songTitle;
@property(retain, nonatomic) NSURL *albumArtURL;
@property(retain, nonatomic) UIImage *albumArtImage;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

