//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UILabel, UISwitch;

@interface IGStoryToggleAccessoryView : UIView
{
    UISwitch *_toggleSwitch;
    UILabel *_descriptionLabel;
    id <IGStoryToggleAccessoryViewDelegate> _delegate;
}

@property(nonatomic) __weak id <IGStoryToggleAccessoryViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_toggleSwitched:(id)arg1;
@property(retain, nonatomic) NSString *descriptionString;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithToggleOn:(_Bool)arg1;

@end

