//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGHighlightCoverPreviewView, IGTapButton, UIButton, UILabel;

@interface IGSuggestedHighlightEndCardOverlayView : UIView
{
    IGHighlightCoverPreviewView *_coverPreviewView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIButton *_addToProfileButton;
    UIButton *_removeButton;
    IGTapButton *_dismissButton;
    id <IGSuggestedHighlightEndCardOverlayViewDelegate> _delegate;
    double _dismissButtonTopPadding;
}

@property(nonatomic) double dismissButtonTopPadding; // @synthesize dismissButtonTopPadding=_dismissButtonTopPadding;
@property(nonatomic) __weak id <IGSuggestedHighlightEndCardOverlayViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_dismissTapped;
- (void)_removeButtonTapped:(id)arg1;
- (void)_addToProfileButtonTapped:(id)arg1;
- (void)configureWithTitle:(id)arg1 coverImageModel:(id)arg2 analyticsModule:(id)arg3;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

