//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CAAnimationDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class IGTag<IGTagViewAccessibility>, IGTapButton, NSString, UIControl, UIImageView, UILongPressGestureRecognizer, UIPanGestureRecognizer;

@interface IGTagView : UIView <UIGestureRecognizerDelegate, CAAnimationDelegate>
{
    UIView *_expandedView;
    UIImageView *_leftBGView;
    UIImageView *_rightBGView;
    double _caretPosition;
    _Bool _shouldRemoveAfterAnimation;
    UIPanGestureRecognizer *_panRecognizer;
    struct CGPoint _panGestureInitialCenter;
    struct CGPoint _panGestureInitialLocation;
    UIView *_innerContentView;
    _Bool _expanded;
    _Bool _isMoving;
    _Bool _flipped;
    _Bool _isEditable;
    _Bool _isActive;
    IGTag<IGTagViewAccessibility> *_objectTag;
    id <IGTagViewDelegate> _delegate;
    UIControl *_contentView;
    UILongPressGestureRecognizer *_pressRecognizer;
    IGTapButton *_removeButton;
    double _proposedCaretPosition;
    struct CGPoint _position;
}

@property(nonatomic) double proposedCaretPosition; // @synthesize proposedCaretPosition=_proposedCaretPosition;
@property(nonatomic) double caretPosition; // @synthesize caretPosition=_caretPosition;
@property(nonatomic) _Bool isActive; // @synthesize isActive=_isActive;
@property(nonatomic) _Bool isEditable; // @synthesize isEditable=_isEditable;
@property(nonatomic) _Bool flipped; // @synthesize flipped=_flipped;
@property(readonly, nonatomic) _Bool isMoving; // @synthesize isMoving=_isMoving;
@property(nonatomic) struct CGPoint position; // @synthesize position=_position;
@property(readonly, nonatomic) IGTapButton *removeButton; // @synthesize removeButton=_removeButton;
@property(readonly, nonatomic) UILongPressGestureRecognizer *pressRecognizer; // @synthesize pressRecognizer=_pressRecognizer;
@property(readonly, nonatomic) UIControl *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) __weak id <IGTagViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool expanded; // @synthesize expanded=_expanded;
@property(readonly, nonatomic) IGTag<IGTagViewAccessibility> *objectTag; // @synthesize objectTag=_objectTag;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (void)repositionWithCaretAtPosition:(double)arg1;
- (void)shrink:(_Bool)arg1 animated:(_Bool)arg2;
- (void)show:(_Bool)arg1 withAnimation:(long long)arg2;
- (void)setExpanded:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_updateBackgroundImages;
- (void)_onDragExit;
- (void)_onTouchDown;
- (void)_onTap;
- (void)setObjectTag:(id)arg1;
- (void)_onRemove;
- (void)_removeAndNotifyDelegate:(_Bool)arg1;
- (void)remove;
- (double)_currentWidth;
- (void)_hideAndRemove;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)_scaleUp;
- (struct CGPoint)_caretPointWithCenter:(struct CGPoint)arg1;
- (void)_handlePanFromRecognizer:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)didMoveToSuperview;
- (void)reposition;
- (struct CGRect)proposedFrame;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (long long)tagViewType;
- (id)initWithObjectTag:(id)arg1 innerContentView:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

