//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class IGTabBarTooltipPresentationCollapseBehaviour;

@interface IGTabBarTooltipPresentationConfig : FBValueObject <NSCopying, NSCoding>
{
    CDUnknownBlockType _dismissCompletion;
    IGTabBarTooltipPresentationCollapseBehaviour *_collapseBehaviour;
}

@property(readonly, copy, nonatomic) IGTabBarTooltipPresentationCollapseBehaviour *collapseBehaviour; // @synthesize collapseBehaviour=_collapseBehaviour;
@property(readonly, copy, nonatomic) CDUnknownBlockType dismissCompletion; // @synthesize dismissCompletion=_dismissCompletion;
- (void).cxx_destruct;
- (id)initWithDismissCompletion:(CDUnknownBlockType)arg1 collapseBehaviour:(id)arg2;

@end

