//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGActionSheetDelegate.h"

@class IGFeedItem, IGMediaManager, IGTVViewerLoggingContext, IGUserSession, NSString, UIViewController;

@interface IGTVFeedItemActionsController : NSObject <IGActionSheetDelegate>
{
    IGUserSession *_userSession;
    IGFeedItem *_feedItem;
    IGMediaManager *_mediaManager;
    UIViewController *_hostingViewController;
    IGTVViewerLoggingContext *_loggingContext;
    NSString *_channelPK;
    _Bool _shouldShowReportOrganicItemActionSheet;
    _Bool _shouldShowHideAdReasonActionSheet;
    id <IGTVFeedItemActionsControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <IGTVFeedItemActionsControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)actionSheetFinishedHiding;
- (void)actionSheetDismissedWithButtonTitled:(id)arg1;
- (void)_presentAboutAdsWebviewForFeedItem:(id)arg1;
- (void)_reportSponsoredItemWithSourceOfTapping:(id)arg1;
- (void)_showHideAdReasonActionSheet;
- (void)_showReportOrganicItemActionSheet;
- (void)_showDeleteItemAlert:(CDUnknownBlockType)arg1 cancelBlock:(CDUnknownBlockType)arg2;
- (id)_sponsoredItemButtons;
- (id)_organicItemButtons;
- (id)_buttons;
- (void)show;
- (id)initWithUserSession:(id)arg1 feedItem:(id)arg2 mediaManager:(id)arg3 hostingViewController:(id)arg4 loggingContext:(id)arg5 channelPK:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

