//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableOrderedSet;

@interface IGTVGuideChannelsListDataController : NSObject
{
    NSMutableOrderedSet *_channelDataSourcesOrderedSet;
    NSArray *_channelDataSources;
    id <IGTVChannelDataSourceType> _myChannelDataSource;
    id <IGTVChannelDataSourceType> _pushedProfileChannelDataSource;
}

@property(readonly, nonatomic) id <IGTVChannelDataSourceType> pushedProfileChannelDataSource; // @synthesize pushedProfileChannelDataSource=_pushedProfileChannelDataSource;
@property(readonly, nonatomic) id <IGTVChannelDataSourceType> myChannelDataSource; // @synthesize myChannelDataSource=_myChannelDataSource;
@property(readonly, nonatomic) NSArray *channelDataSources; // @synthesize channelDataSources=_channelDataSources;
- (void).cxx_destruct;
- (void)appendOrReplacePushedProfileChannelDataSource:(id)arg1;
- (void)updateWithTVGuideChannelDataSources:(id)arg1 myChannelDataSource:(id)arg2;
- (id)initWithUserSession:(id)arg1;

@end

