//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UIButton, UILabel, UISwitch;

@interface IGTVFacebookCrossPostToggle : UIView
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UIActivityIndicatorView *_indicatorView;
    UISwitch *_toggleSwitch;
    UIButton *_facebookConnectButton;
}

@property(readonly, nonatomic) UIButton *facebookConnectButton; // @synthesize facebookConnectButton=_facebookConnectButton;
@property(readonly, nonatomic) UISwitch *toggleSwitch; // @synthesize toggleSwitch=_toggleSwitch;
- (void).cxx_destruct;
- (void)configureWithSubtitle:(id)arg1 toggleState:(long long)arg2;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)init;

@end

