//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "IGTVBrowseLongPressHideHandling.h"

@class CALayer, IGGradientView, IGRefreshSpinner, IGTVBrowseBlurredOverlayView, IGTVBrowseHighlightDetailsView, NSString, UIView;

@interface IGTVBrowseHighlightVideoCell : UICollectionViewCell <IGTVBrowseLongPressHideHandling>
{
    UIView *_videoContainerView;
    UIView *_videoView;
    IGGradientView *_gradientView;
    IGTVBrowseHighlightDetailsView *_detailsView;
    double _videoOffset;
    CALayer *_highlightOverlay;
    id <IGTVBrowseLongPressHideHandlingDelegate> _longPressDelegate;
    IGTVBrowseBlurredOverlayView *_blurredOverlayView;
    UIView *_staticLoadingView;
    UIView *_chromeView;
    IGRefreshSpinner *_refreshSpinner;
}

@property(readonly, nonatomic) IGRefreshSpinner *refreshSpinner; // @synthesize refreshSpinner=_refreshSpinner;
@property(readonly, nonatomic) UIView *chromeView; // @synthesize chromeView=_chromeView;
@property(readonly, nonatomic) UIView *staticLoadingView; // @synthesize staticLoadingView=_staticLoadingView;
@property(retain, nonatomic) UIView *videoView; // @synthesize videoView=_videoView;
@property(readonly, nonatomic) IGTVBrowseBlurredOverlayView *blurredOverlayView; // @synthesize blurredOverlayView=_blurredOverlayView;
@property(nonatomic) __weak id <IGTVBrowseLongPressHideHandlingDelegate> longPressDelegate; // @synthesize longPressDelegate=_longPressDelegate;
- (void).cxx_destruct;
- (void)configureOverlayWithFeedItem:(id)arg1 videoOffset:(double)arg2 analyticsModule:(id)arg3;
- (void)_longPressDetected:(id)arg1;
- (void)prepareForReuse;
- (void)setHighlighted:(_Bool)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

