//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IGViewController.h"

#import "IGNavigationControllerDelegate.h"
#import "IGTVCoverPickerPreviewViewControllerDelegate.h"
#import "IGTVEditorViewControllerDelegate.h"
#import "IGTVGalleryViewControllerDelegate.h"
#import "IGTVMetadataEditorDelegate.h"

@class IGNavigationController, IGTVCoverPickerPreviewViewController, IGTVCreationAnalyticsSession, IGTVEditorViewController, IGTVGalleryViewController, IGTVMetadataEditorViewController, IGTVUploadTask, IGUserSession, NSString, UIView;

@interface IGTVCreationFlowViewController : IGViewController <IGTVEditorViewControllerDelegate, IGTVGalleryViewControllerDelegate, IGTVMetadataEditorDelegate, IGNavigationControllerDelegate, IGTVCoverPickerPreviewViewControllerDelegate>
{
    IGUserSession *_userSession;
    IGNavigationController *_navigationController;
    IGTVGalleryViewController *_galleryViewController;
    IGTVCoverPickerPreviewViewController *_coverPickerPreviewViewController;
    IGTVEditorViewController *_editorViewController;
    IGTVMetadataEditorViewController *_metadataEditorViewController;
    UIView *_selectedGalleryCell;
    IGTVUploadTask *_uploadTask;
    IGTVCreationAnalyticsSession *_creationAnalytics;
    id <IGTVCreationFlowViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <IGTVCreationFlowViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_logInvalidVideoSelectionWithAsset:(id)arg1 minimumDuration:(double)arg2 maximumDuration:(double)arg3;
- (id)analyticsModule;
- (void)tvMetadataEditor:(id)arg1 didTapBackWithCurrentPostTitle:(id)arg2;
- (void)tvMetadataEditor:(id)arg1 didTapPostWithComposition:(id)arg2 uploadMetadata:(id)arg3;
- (void)coverPickerPreviewViewController:(id)arg1 didTapNextWithComposition:(id)arg2;
- (void)editorViewController:(id)arg1 didTapNextWithComposition:(id)arg2;
- (void)galleryViewController:(id)arg1 didSelectAsset:(id)arg2 withThumbnail:(id)arg3 fromView:(id)arg4;
- (void)galleryViewControllerDidTapClose:(id)arg1;
- (void)navigationController:(id)arg1 willNavigateToViewController:(id)arg2 animated:(_Bool)arg3;
- (void)navigationController:(id)arg1 didNavigateToViewController:(id)arg2 animated:(_Bool)arg3;
- (void)navigationController:(id)arg1 didPopViewController:(id)arg2 animated:(_Bool)arg3;
- (id)childViewControllerForStatusBarStyle;
- (id)childViewControllerForStatusBarHidden;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 creationAnalytics:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

