//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSNumber, NSString;

@interface IGTVGalleryViewControllerConfig : FBValueObject <NSCopying, NSCoding>
{
    _Bool _showIneligibleVideoContent;
    NSString *_defaultTitle;
    NSString *_headerText;
    long long _preferredMediaType;
    long long _assetCollectionSubtype;
    NSNumber *_maximumDuration;
    NSNumber *_minimumDuration;
}

@property(readonly, nonatomic) _Bool showIneligibleVideoContent; // @synthesize showIneligibleVideoContent=_showIneligibleVideoContent;
@property(readonly, copy, nonatomic) NSNumber *minimumDuration; // @synthesize minimumDuration=_minimumDuration;
@property(readonly, copy, nonatomic) NSNumber *maximumDuration; // @synthesize maximumDuration=_maximumDuration;
@property(readonly, nonatomic) long long assetCollectionSubtype; // @synthesize assetCollectionSubtype=_assetCollectionSubtype;
@property(readonly, nonatomic) long long preferredMediaType; // @synthesize preferredMediaType=_preferredMediaType;
@property(readonly, copy, nonatomic) NSString *headerText; // @synthesize headerText=_headerText;
@property(readonly, copy, nonatomic) NSString *defaultTitle; // @synthesize defaultTitle=_defaultTitle;
- (void).cxx_destruct;
- (id)initWithDefaultTitle:(id)arg1 headerText:(id)arg2 preferredMediaType:(long long)arg3 assetCollectionSubtype:(long long)arg4 maximumDuration:(id)arg5 minimumDuration:(id)arg6 showIneligibleVideoContent:(_Bool)arg7;

@end

