//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IGTVVideoControlsView;

@protocol IGTVVideoControlsViewDelegate
- (void)videoControlsViewDidPressSkip:(IGTVVideoControlsView *)arg1;
- (void)videoControlsViewDidPressCTA:(IGTVVideoControlsView *)arg1;
- (void)videoControlsViewDidPressPlayPause:(IGTVVideoControlsView *)arg1;
- (void)videoControlsViewProgressScrubbingEnded:(IGTVVideoControlsView *)arg1;
- (void)videoControlsViewProgressScrubbingChanged:(IGTVVideoControlsView *)arg1;
- (void)videoControlsViewProgressScrubbingBegan:(IGTVVideoControlsView *)arg1;
@end

