//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "IGListDiffable.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class IGBadgingTooltipToken, NSString, NSURL;

@interface IGTVBadgingTooltipViewModel : FBValueObject <IGListDiffable, NSCopying, NSCoding>
{
    IGBadgingTooltipToken *_badgingTooltipToken;
    NSString *_authorPK;
    NSString *_mediaPK;
    NSURL *_coverPhotoURL;
    NSString *_videoTitle;
    NSString *_authorName;
    NSString *_durationString;
    NSString *_durationAccessibilityString;
    NSString *_viewCountString;
    NSString *_viewCountAccessibilityString;
}

@property(readonly, copy, nonatomic) NSString *viewCountAccessibilityString; // @synthesize viewCountAccessibilityString=_viewCountAccessibilityString;
@property(readonly, copy, nonatomic) NSString *viewCountString; // @synthesize viewCountString=_viewCountString;
@property(readonly, copy, nonatomic) NSString *durationAccessibilityString; // @synthesize durationAccessibilityString=_durationAccessibilityString;
@property(readonly, copy, nonatomic) NSString *durationString; // @synthesize durationString=_durationString;
@property(readonly, copy, nonatomic) NSString *authorName; // @synthesize authorName=_authorName;
@property(readonly, copy, nonatomic) NSString *videoTitle; // @synthesize videoTitle=_videoTitle;
@property(readonly, copy, nonatomic) NSURL *coverPhotoURL; // @synthesize coverPhotoURL=_coverPhotoURL;
@property(readonly, copy, nonatomic) NSString *mediaPK; // @synthesize mediaPK=_mediaPK;
@property(readonly, copy, nonatomic) NSString *authorPK; // @synthesize authorPK=_authorPK;
@property(readonly, copy, nonatomic) IGBadgingTooltipToken *badgingTooltipToken; // @synthesize badgingTooltipToken=_badgingTooltipToken;
- (void).cxx_destruct;
- (_Bool)isEqualToDiffableObject:(id)arg1;
- (id)diffIdentifier;
- (id)initWithBadgingTooltipToken:(id)arg1 authorPK:(id)arg2 mediaPK:(id)arg3 coverPhotoURL:(id)arg4 videoTitle:(id)arg5 authorName:(id)arg6 durationString:(id)arg7 durationAccessibilityString:(id)arg8 viewCountString:(id)arg9 viewCountAccessibilityString:(id)arg10;

@end

