//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGRemoteImageView, IGTVCreationFlowNavigationBar, IGTVMetadataInputView, IGTextView, UIScrollView;

@interface IGTVPostUploadMetadataEditorView : UIView
{
    UIView *_sectionSeparator;
    UIScrollView *_contentScrollView;
    IGTVCreationFlowNavigationBar *_navigationBar;
    IGRemoteImageView *_coverPhotoImageView;
    IGTVMetadataInputView *_titleInputView;
    IGTextView *_descriptionTextView;
}

@property(readonly, nonatomic) IGTextView *descriptionTextView; // @synthesize descriptionTextView=_descriptionTextView;
@property(readonly, nonatomic) IGTVMetadataInputView *titleInputView; // @synthesize titleInputView=_titleInputView;
@property(readonly, nonatomic) IGRemoteImageView *coverPhotoImageView; // @synthesize coverPhotoImageView=_coverPhotoImageView;
@property(readonly, nonatomic) IGTVCreationFlowNavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
@property(readonly, nonatomic) UIScrollView *contentScrollView; // @synthesize contentScrollView=_contentScrollView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

