//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class IGPath, NSDictionary, NSString;

@interface IGUploadAudioItem : FBValueObject <NSCopying, NSCoding>
{
    IGPath *_audioFilePath;
    NSString *_uploadId;
    NSDictionary *_uploadParams;
    NSString *_mediaKey;
}

@property(readonly, copy, nonatomic) NSString *mediaKey; // @synthesize mediaKey=_mediaKey;
@property(readonly, copy, nonatomic) NSDictionary *uploadParams; // @synthesize uploadParams=_uploadParams;
@property(readonly, copy, nonatomic) NSString *uploadId; // @synthesize uploadId=_uploadId;
@property(readonly, copy, nonatomic) IGPath *audioFilePath; // @synthesize audioFilePath=_audioFilePath;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAudioFilePath:(id)arg1 uploadId:(id)arg2 uploadParams:(id)arg3 mediaKey:(id)arg4;

@end

