//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "IGUserListSelectableCellType.h"

@class IGUser, IGUserContentView, NSString, UIButton, UIView;

@interface IGUserListFavoritesCell : UICollectionViewCell <IGUserListSelectableCellType>
{
    IGUser *_user;
    IGUserContentView *_userContentView;
    UIView *_separator;
    UIView *_accessibilityHelperView;
    UIButton *_addLabel;
    UIButton *_removeLabel;
    _Bool _userSelected;
    id <IGUserListFavoriteSelectionDelegate> delegate;
    unsigned long long _selectionCellType;
}

@property(nonatomic) unsigned long long selectionCellType; // @synthesize selectionCellType=_selectionCellType;
@property(nonatomic) _Bool userSelected; // @synthesize userSelected=_userSelected;
@property(nonatomic) __weak id <IGUserListFavoriteSelectionDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)_configureAccessibilityLabelForUser:(id)arg1 selected:(_Bool)arg2;
- (void)_updateWithSelection:(_Bool)arg1;
- (void)_removeFromList;
- (void)_addToList;
- (void)configureCellWithUser:(id)arg1 module:(id)arg2;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

