//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGUsernameLabel, NSString;

@interface IGUsernameTitleView : UIView
{
    IGUsernameLabel *_usernameLabel;
    NSString *_username;
    _Bool _isVerified;
    double _fontSize;
    long long _maxCharacterLengthToDisplay;
}

- (void).cxx_destruct;
- (struct CGSize)_constrainedLabelSizeThatFits:(struct CGSize)arg1;
- (id)_usernameToDisplay;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)configureWithUsername:(id)arg1 isVerified:(_Bool)arg2;
- (id)initWithFontSize:(double)arg1 maxCharacterLengthToDisplay:(long long)arg2;
- (id)initWithFontSize:(double)arg1;

@end

