//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGVideoPlaybackStateManager;

@protocol IGVideoPlaybackStateManagerDelegate <NSObject>
- (void)stateManager:(IGVideoPlaybackStateManager *)arg1 didEndWithState:(long long)arg2;
- (void)stateManager:(IGVideoPlaybackStateManager *)arg1 didAttemptInvalidTransitionFromState:(long long)arg2 toState:(long long)arg3;
- (void)stateManager:(IGVideoPlaybackStateManager *)arg1 didPerformValidTransitionFromState:(long long)arg2 toState:(long long)arg3;
- (void)stateManager:(IGVideoPlaybackStateManager *)arg1 didStartWithState:(long long)arg2;
@end

