//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IGSimpleButton, IGVideoGlyphView, UIImageView;

@interface IGVideoIndicatorView : UIView
{
    UIView *_glyphView;
    IGSimpleButton *_playGlyph;
    IGSimpleButton *_pauseGlyph;
    IGSimpleButton *_errorGlyph;
    IGVideoGlyphView *_videoGlyph;
    UIImageView *_igtvGlyph;
    long long _indicatorState;
}

@property(nonatomic) long long indicatorState; // @synthesize indicatorState=_indicatorState;
- (void).cxx_destruct;
- (void)setAccessibilityTraits:(unsigned long long)arg1;
- (void)setAccessibilityLabel:(id)arg1;
- (void)_showIGTV:(_Bool)arg1;
- (void)_showLoading:(_Bool)arg1;
- (void)_showError:(_Bool)arg1;
- (void)_showPause:(_Bool)arg1;
- (void)_showPlay:(_Bool)arg1;
- (id)_generateGlyphButtonWithFrame:(struct CGRect)arg1 image:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

