//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IGVideoCallParticipantsContainerDataSourceDelegate.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSString, UICollectionView, UICollectionViewFlowLayout;

@interface IGVideoCallParticipantsContainerViewController : UIViewController <UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, IGVideoCallParticipantsContainerDataSourceDelegate>
{
    UICollectionViewFlowLayout *_layout;
    long long _containerType;
    long long _cellLayoutStyle;
    UICollectionView *_collectionView;
}

@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (double)_avatarPaddingForCellLayoutStyle:(long long)arg1;
- (double)_collectionViewWidthForLayoutStyle:(long long)arg1;
- (void)_updateCollectionViewLayoutIfNecessary;
- (void)participant:(id)arg1 atIndexPath:(id)arg2 didUpdateAudioEnabledState:(_Bool)arg3;
- (void)participantsAvatarDataSourceDidUpdate;
- (void)viewDidLayoutSubviews;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (id)initWithParticipantContainerType:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

