//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBIvarBasedEqualityObject.h"

#import "NSCoding.h"

@class IGGIFSource, IGVideoComposition;

@interface IGVideoSource : FBIvarBasedEqualityObject <NSCoding>
{
    unsigned long long _subtype;
    IGVideoComposition *_videoComposition;
    IGGIFSource *_gif;
}

+ (id)videoComposition:(id)arg1;
+ (id)gif:(id)arg1;
- (void).cxx_destruct;
- (void)matchVideoComposition:(CDUnknownBlockType)arg1 gif:(CDUnknownBlockType)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

