//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IGFeedItem, IGFeedItemTracker, NSDictionary, NSString, NSURL;

@interface IGWatchAndMoreLoggingContext : NSObject
{
    IGFeedItem *_feedItem;
    IGFeedItemTracker *_tracker;
    NSString *_sessionID;
    NSString *_module;
    NSString *_action;
    NSURL *_url;
    NSDictionary *_extraDict;
    unsigned long long _entrySource;
}

- (void).cxx_destruct;
- (id)_buildExtraDictionaryWithPageCellState:(id)arg1;
- (void)_logEvent:(id)arg1 withExtraDictionary:(id)arg2;
- (void)notifyDismissWithSource:(unsigned long long)arg1;
- (void)notifyContentViewDragWithExtra:(id)arg1;
- (void)notifyContentViewTap;
- (void)notifyImpression;
- (id)module;
- (id)initWithFeedItem:(id)arg1 watchAndMoreType:(unsigned long long)arg2 url:(id)arg3 pageCellState:(id)arg4 entrySource:(unsigned long long)arg5;

@end

