//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IGInteractiveDismissTransitionControllerType.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UIViewControllerAnimatedTransitioning.h"

@class IGGestureCoordinatingScrollView, NSString, UIColor, UIView, UIViewController;

@interface IGZoomTransitionController : NSObject <UIViewControllerAnimatedTransitioning, UIScrollViewDelegate, UIGestureRecognizerDelegate, IGInteractiveDismissTransitionControllerType>
{
    UIView *_presentingViewControllerSnapshot;
    UIView *_dimmingView;
    IGGestureCoordinatingScrollView *_scrollView;
    _Bool _useSlideOffDismiss;
    UIView *_presentationSource;
    id <IGInteractiveDismissTransitionControllerDelegate> _delegate;
    UIViewController *_presentedViewController;
}

@property(nonatomic) _Bool useSlideOffDismiss; // @synthesize useSlideOffDismiss=_useSlideOffDismiss;
@property(readonly, nonatomic) __weak UIViewController *presentedViewController; // @synthesize presentedViewController=_presentedViewController;
@property(nonatomic) __weak id <IGInteractiveDismissTransitionControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIView *presentationSource; // @synthesize presentationSource=_presentationSource;
- (void).cxx_destruct;
- (void)scrollViewWillBeginDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (id)animationControllerForDismissedController:(id)arg1;
- (id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3;
- (void)prepareForDismissFromShare;
@property(retain, nonatomic) UIColor *dimmingBackgroundColor;
- (void)hideDimmingView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

