//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol KFAnimationPlaybackControllerProtocol <NSObject>
@property(readonly, nonatomic) double progress;
- (void)didMutateAsset;
- (id <KFAnimationPlaybackControllerProtocol>)repeatForever;
- (id <KFAnimationPlaybackControllerProtocol>)repeatCount:(long long)arg1;
- (id <KFAnimationPlaybackControllerProtocol>)seekToProgress:(double)arg1;
- (id <KFAnimationPlaybackControllerProtocol>)stop;
- (id <KFAnimationPlaybackControllerProtocol>)pause;
- (id <KFAnimationPlaybackControllerProtocol>)play;
@end

