//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MAIAppStoreFetchCoordinator : NSObject
{
    _Bool _allowMultiCache;
    id <MAIAppStoreFetchCoordinatorAnalyticsDelegate> _analyticDelegate;
}

@property(nonatomic) __weak id <MAIAppStoreFetchCoordinatorAnalyticsDelegate> analyticDelegate; // @synthesize analyticDelegate=_analyticDelegate;
- (void).cxx_destruct;
- (void)_loadStoreProductViewController:(id)arg1 withSKStoreProductParams:(id)arg2;
- (id)_sharedCacheManager;
- (void)clearAllCache;
- (void)clearFetchedAppStoreWithITunesIdentifier:(id)arg1;
- (id)storeProductViewControllerFromITunesIdentifier:(id)arg1;
- (void)fetchAppStoreWithSKStoreProductParams:(id)arg1 isPrefetchEnabled:(_Bool)arg2 shouldUseBackgroundThread:(_Bool)arg3 onInitialized:(CDUnknownBlockType)arg4;
- (id)initWithShouldAllowMultiCache:(_Bool)arg1;

@end

