//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSString;

@interface MAIAppStoreLaunchedAnalytics : FBValueObject <NSCopying, NSCoding>
{
    _Bool _isPreloadingEnabled;
    NSString *_iTunesIdentifier;
    double _loadDuration;
}

@property(readonly, nonatomic) double loadDuration; // @synthesize loadDuration=_loadDuration;
@property(readonly, copy, nonatomic) NSString *iTunesIdentifier; // @synthesize iTunesIdentifier=_iTunesIdentifier;
@property(readonly, nonatomic) _Bool isPreloadingEnabled; // @synthesize isPreloadingEnabled=_isPreloadingEnabled;
- (void).cxx_destruct;
- (id)initWithIsPreloadingEnabled:(_Bool)arg1 iTunesIdentifier:(id)arg2 loadDuration:(double)arg3;

@end

