//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTBridgeModule.h"

@protocol NativeIGPostInsightsReactModuleSpec <RCTBridgeModule>
- (void)toggleNavigationBar:(double)arg1 hideActionBar:(_Bool)arg2;
- (void)didFinishLoading:(double)arg1;
@end

