//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTBridgeModule.h"

@class NSArray, NSString;

@protocol NativeIGInsightsStoryPresenterReactModuleSpec <RCTBridgeModule>
- (void)openStoryViewerForMediaIDs:(NSArray *)arg1 focusedMediaID:(NSString *)arg2 thumbnailReactTag:(double)arg3 surface:(NSString *)arg4;
@end

