//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIScrollView;

@protocol RCTBackedTextInputDelegate <NSObject>
- (void)textInputDidChangeSelection;
- (void)textInputDidChange;
- (_Bool)textInputShouldChangeTextInRange:(struct _NSRange)arg1 replacementText:(NSString *)arg2;
- (void)textInputDidReturn;
- (_Bool)textInputShouldReturn;
- (void)textInputDidEndEditing;
- (_Bool)textInputShouldEndEditing;
- (void)textInputDidBeginEditing;
- (_Bool)textInputShouldBeginEditing;

@optional
- (void)scrollViewDidScroll:(UIScrollView *)arg1;
@end

