//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RCTNavigationOptionsUtils : NSObject
{
}

+ (id)parseTranslationPayload:(id)arg1;
+ (id)resolveNavigationOptions:(id)arg1 withParams:(id)arg2 translator:(CDUnknownFunctionPointerType)arg3;
+ (id)resolveNavigationOptions:(id)arg1 withURL:(id)arg2 translator:(CDUnknownFunctionPointerType)arg3;
+ (id)translateNavigationOptions:(id)arg1 translator:(CDUnknownFunctionPointerType)arg2;

@end

