//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RTCYUVPlanarBuffer.h"

@protocol RTCMutableYUVPlanarBuffer <RTCYUVPlanarBuffer>
@property(readonly, nonatomic) char *mutableDataV;
@property(readonly, nonatomic) char *mutableDataU;
@property(readonly, nonatomic) char *mutableDataY;
@end

